### ISSUE TITLE
How to develop ion locally?

### ISSUE THREAD

**Issue by leo-petrucci** [sst/ion#1002]
I'm interested in contributing, but I haven't been able to figure out how to develop Ion locally.

So far:
- clone the repo
- `bun install`
- `cd platform && bun run build`

Then I'm able to use the SST cli by running `go run ./cmd/sst`.

What's confusing me is how I can use this alongside a local SST project to check that it's working correctly. Is there any way to use the local CLI with a local project?

**Comment by thdxr** [comment]
marking this as done for now lmk if you have other issues

**Comment by jayair** [comment]
Added this to https://github.com/sst/ion?tab=readme-ov-file#running-locally
