### ISSUE TITLE
`sst dev` using random keys for env. Can't find out where it is pulling that data from

### ISSUE THREAD

**Issue by sshadmand** [sst/ion#1006]
As described in Discord thread: https://discord.com/channels/983865673656705025/983865673656705028/1281763868753793075

Notice the set keys as **5O** and **UP**

```
# .env.production
FUNNY=".env.production"
AWS_REGION="us-east-1"
AWS_ACCESS_KEY_ID="AK.....5O"
AWS_SECRET_ACCESS_KEY="g0.....UP"
```

```
# ~/.aws/credentials
[default]
AWS_ACCESS_KEY_ID = AK...5O
AWS_SECRET_ACCESS_KEY = g0...UP
```

```
# api/users/route.ts
console.log("AA", process.env.FUNNY, process.env.AWS_ACCESS_KEY_ID);
console.log("BB", process.env.AWS_SECRET_ACCESS_KEY, process.env.AWS_REGION);
```

```
#> yarn  sst dev
```

Logs on /api/users in console.log. Notice Notice the set keys as **AA** and **TD**

```
✓ Compiled /api/users in 2.6s (1973 modules)
AA .env.production AS...AA
BB CV...TD us-east-1
```

Then I kill it and rerun it. No changes to code base or anything...

```
#> yarn  sst dev
```

Logs on /api/users in console.log. Notice Notice the set keys as **M3** and **Q7**

```
AA .env.production AS...M3
BB XT...Q7 us-east-1
```

**Comment by sshadmand** [comment]
From Discord...

DAX: it should not match your ~/.aws/credentials - it uses temporary credentials generated when it starts.  is there something that's actually not working? 

Me: Ohhhh. I get it now. Generating keys each start is expected. Nothing breaking per se other than the inability to use the keys. Knowing it is expected helps. I ended up pushing the env vars to the `sst.config.ts` and now they show up in the routes.ts. THX

```
export default $config({
  app(input) {
    return {
      ...
      providers: {
        aws: {
          region: "us-east-1",
        },
      },
    };
  },
  async run() {
     ...
    const environment = {
      AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
      AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    };
     ...
    const web = new sst.aws.Nextjs("MyWeb", {
      domain: {
        name: `${subdomain}.${domain}`,
      },
      environment,
```

Closing.

**Comment by sshadmand** [comment]
I take that back. It worked if not creating, but when deploying a new env it is not allowed:

   Lambda: CreateFunction, https response error StatusCode: 400, RequestID: 759817d3-c7be-4948-893c-9e36dfc937ce, InvalidParameterValueException: Lambda was unable to
 configure your environment variables because the environment variables you have provided contains reserved keys that are currently not supported for modification. Re
served keys used in this request: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

**Comment by thdxr** [comment]
you should not be passing keys manually like this into your nextjs app<br>sst already generates the right credentials and injects them in - you can just use them<br><br>do not pass through hardcoded credentials
