### ISSUE TITLE
Docs: Live Lambda doesnt support event streaming

### ISSUE THREAD

**Issue by dested** [sst/ion#1014]
This took a while to track down but the live lambda handler doesn't support streaming. To be honest, I don't know how this _could_ work given the realtime writing, but it should at least be documented somewhere. If you agree, I'll find a spot and submit a PR!

**Comment by thdxr** [comment]
yeah there actually is a way to make it work because we made the underlying bridge stream based but this probably isn't super high priority at the moment<br><br>you're right we should document it

**Comment by jayair** [comment]
Yeah I'll add it

**Comment by Ilia-TheNetworkFirm** [comment]
This is the example workaround

```ts
import { streamHandle, handle } from 'hono/aws-lambda';

import app from './app';

export const handler = process.env.SST_LIVE ? handle(app) : streamHandle(app);
```

**Comment by iokhotnikov** [comment]
This is the example workaround:

```ts
import { streamHandle, handle } from 'hono/aws-lambda';

import app from './app';

export const handler = process.env.SST_LIVE ? handle(app) : streamHandle(app);
```

**Comment by jayair** [comment]
<img width="753" alt="Screenshot 2024-09-21 at 3 38 44 PM" src="https://github.com/user-attachments/assets/53c15603-6885-47dc-8976-a58ef9dab5c5">
