### ISSUE TITLE
Stopping / killing the SST dev multiplexer keeps the NextJS process running

### ISSUE THREAD

**Issue by benjamindell** [sst/ion#1027]
It should kill the NextJS process so that when you next start SST dev, NextJS can restart gracefully too. Currently it sees that port 3000 is still open and so starts (now a second) NextJS process on port 3001.

**Comment by sb55555** [comment]
Same issue here on 3.0.125

**Comment by sb55555** [comment]
fixed on 3.0.133

**Comment by thdxr** [comment]
is just x fixed or is both fixed?

**Comment by sb55555** [comment]
both are fixed on my side

**Comment by jayair** [comment]
@benjamindell?

**Comment by benjamindell** [comment]
Yep looks good so far :)
