### ISSUE TITLE
Custom origin server and s3 origin options for SSR site plan

### ISSUE THREAD

**Issue by rmarscher** [sst/ion#1030]
Hi. My app has an s3 bucket to hold media uploads and an additional lambda Function to process those uploads. I wanted to route to them using the CDN distribution created by my SSR site. I _could_ create another Router and route from there to the SSR site CDN. That seems a bit wasteful. But would that be a better solution?

#996 proposes a solution to accept custom origins for the SSR site plan.

I published a demo in a public repo. The code to add the s3 origin and function are commented out here https://github.com/rmarscher/waku-sst-demo/blob/main/infra/website.ts#L28-L70

My SSR site component has a beforePlanValidate arg to hook into updating the plan. https://github.com/rmarscher/waku-sst-demo/blob/main/infra/components/waku.ts#L615-L617

Thank you!

**Comment by fwang** [comment]
Appreciate the PR! We have something planed.

In the meanwhile, i believe u can transform the `cdn` and modify the origins. Here's a thread of someone trying to transform the `cdn` - https://discord.com/channels/983865673656705025/1227658579046174872. Hope this helps until the feature gets added.

**Comment by rmarscher** [comment]
OK sounds good. It's possible I missed `orderedCacheBehaviors` as the right property to transform. I can go ahead and close this.
