### ISSUE TITLE
Examples: review basic auth examples

### ISSUE THREAD

**Issue by fwang** [sst/ion#1039]
- `StaticSite` with basic auth: https://github.com/sst/ion/tree/dev/examples/aws-static-site-basic-auth
- `Nextjs` with basic auth: https://github.com/sst/ion/tree/dev/examples/aws-nextjs-basic-auth

**Comment by jayair** [comment]
https://sst.dev/docs/examples/#aws-nextjs-basic-auth

https://sst.dev/docs/examples/#aws-static-site-basic-auth

Done
