### ISSUE TITLE
Examples: fix static-site example

### ISSUE THREAD

**Issue by fwang** [sst/ion#1040]
The `aws-static-site` example is broken. The `path` is set to the `dist` folder, but the folder doesn't exist in the repo.
https://github.com/sst/ion/tree/dev/examples/aws-static-site

You can reference the `aws-static-site-basic-auth` example. Its `path` is set to the `site` folder with a simple `index.html`
https://github.com/sst/ion/tree/dev/examples/aws-static-site-basic-auth

**Comment by jayair** [comment]
@thdxr keeps breaking it lol

<img width="657" alt="Screenshot 2024-09-11 at 1 35 42 PM" src="https://github.com/user-attachments/assets/e24c2248-45d9-4f4e-b8b3-346a328e2f79">
