### ISSUE TITLE
CongitoUserPool does not update successfully on deploy (Regression)

### ISSUE THREAD

**Issue by joshwils82** [sst/ion#1075]
This error is back on deploys with a cognito user pool.  It was previous reported here: https://github.com/sst/ion/issues/617 and a fix in a dependency resolved it for a while.  However, it is now back on version 3.1.12 of sst.

It may be worth exposing the ignoreChanges pulumi option which will allow a work around to be put in place.

**Comment by fwang** [comment]
Can u give this a try:
```ts
const pool = new sst.aws.CognitoUserPool("MyPool", {
  transform: {
    userPool: (args, opts) => {
      opts.ignoreChanges = ["schemas"];
    }
  }
});
```

btw, Is it an upstream Pulumi/Terraform issue? If so, could u link to the GH issue?

**Comment by joshwils82** [comment]
Yes, that works, thanks! I believe it is an upstream issue.
