### ISSUE TITLE
Can't properly attach lambda authorizer function.

### ISSUE THREAD

**Issue by gablabelle** [sst/ion#1085]
Hello,

I'm trying to set an authorizer function on my ApiGatewayV2 that would check if the domain is allowed but it seems that `authorizer.handler` never runs even though the API call to `api.hello` returns 401 `{ "message": "Unauthorized" }`

https://sst.dev/docs/component/aws/apigatewayv2/#auth-lambda

```ts
import {
  bucket,
 allowedDomainsTable,
} from './storage';

export const apiGateway = new sst.aws.ApiGatewayV2('ApiGateway', {
  transform: {
    route: {
      handler: {
        link: [
          bucket,
          allowedDomainsTable,
        ],
      },
    },
  },
});

const myAuthorizer = apiGateway.addAuthorizer({
  name: 'myAuthorizer',
  lambda: {
    function: 'packages/functions/src/authorizer.handler',
  },
});

const defaultRouteOptions = {
  auth: {
    lambda: myAuthorizer.id,
  },
};

apiGateway.route(
  'GET /hello',
  'packages/functions/src/api.hello',
  defaultRouteOptions,
);
```

When removing defaultRouteOptions the `api.hello` runs correctly. Here is the `authorizer.handler` function:

```ts
import type {
  APIGatewayAuthorizerHandler,
  APIGatewayAuthorizerEvent,
  StatementEffect,
} from 'aws-lambda';

export const handler: APIGatewayAuthorizerHandler = async (
  event: APIGatewayAuthorizerEvent,
) => {
  console.log('authorizer event', event);

  return generatePolicy('user', 'Allow', event.methodArn);
};

const generatePolicy = (
  principalId: string,
  effect: StatementEffect,
  resource: string,
) => {
  return {
    principalId,
    policyDocument: {
      Version: '2012-10-17',
      Statement: [
        {
          Action: 'execute-api:Invoke',
          Effect: effect,
          Resource: resource,
        },
      ],
    },
  };
};
```

**Comment by paolostyle** [comment]
Since your authorizer is returning an IAM policy and I can see your event is typed as `APIGatewayRequestAuthorizerEvent` and not `APIGatewayRequestAuthorizerEventV2`, I believe you need to add `response` and `payload` attributes like this:
```
const myAuthorizer = apiGateway.addAuthorizer({
  name: 'myAuthorizer',
  lambda: {
    function: 'packages/functions/src/authorizer.handler',
    response: 'iam',
    // payload: '1.0', // not sure about this, but my authorizer's event uses APIGatewayRequestAuthorizerEventV2 type
  },
});
```

**Comment by gablabelle** [comment]
@paolostyle, I'm new to AWS and SST, and for now I'm just trying to get the most simple authorizer handler to run. I guess that I don't even need an IAM policy for my use case simply a simple boolean.

That being said, when deploying using `pnpm sst deploy --stage develop`, I get the same response in POSTMAN calling the `api.hello` function

```json
{
    "message": "Unauthorized"
}
```

and I get the following error in the `authorizer.handler` lambda function Triggers:

```
The API with ID 0hla11xcfd doesn’t include a route with path /* having an integration arn:aws:lambda:us-east-1:345594572775:function:artfcl-develop-ApiGatewayAuthorizerMyAuthorizerFunctionFunction.
```

and the same Trigger error when running `pnpm sst dev`:

```
The API with ID pruc2z9xc5 doesn’t include a route with path /* having an integration arn:aws:lambda:us-east-1:345594572775:function:artf-gablabelle-ApiGatewayAuthorizerMyAuthorizerFunctionFunction.
```

If I click on the Test button to trigger a test call I can see the request coming in the SST console.

**So for me nothing ever works.**

Here is my updated code using `simple` instead of `iam`

```ts
const myAuthorizer = apiGateway.addAuthorizer({
  name: 'myAuthorizer',
  lambda: {
    function: 'packages/functions/src/authorizer.handler',
    response: 'simple',
    payload: '2.0',
  },
});

const defaultRouteOptions = {
  auth: {
    lambda: myAuthorizer.id,
  },
};

apiGateway.route(
  'GET /hello',
  'packages/functions/src/api.hello',
  defaultRouteOptions,
);
```

the `packages/functions/src/authorizer.handler` function:

```ts
import {
  APIGatewayRequestSimpleAuthorizerHandlerV2,
  APIGatewayRequestAuthorizerEventV2,
  APIGatewaySimpleAuthorizerResult,
} from 'aws-lambda';

export const handler: APIGatewayRequestSimpleAuthorizerHandlerV2 = async (
  event: APIGatewayRequestAuthorizerEventV2,
): Promise<APIGatewaySimpleAuthorizerResult> => {
  console.log('handler authorizer event', event);

  // Your authorization logic here
  const isAuthorized = true; // Replace with your actual authorization check

  return {
    isAuthorized,
  };
};
```

**Comment by paolostyle** [comment]
Ah in that case you can also set `identitySources` in `lambda` to `[]`. I believe by default it requires use of the Authorizer header, if you just testing it out and don't have a specific solution in mind then that should help

**Comment by gablabelle** [comment]
@paolostyle It works if I use `identitySources: []` or if I simply add a dummy authorization header in POSTMAN. Thanks for your time and help. I'll close the issue.

"Skill issue!" 😉

**Comment by gablabelle** [comment]
@paolostyle maybe you know the answer to this one? https://github.com/sst/ion/issues/1094
