### ISSUE TITLE
How can I link a resource so that my authorizer function can access it?

### ISSUE THREAD

**Issue by gablabelle** [sst/ion#1094]
How can I link a resource so that my authorizer function can access it?

The resource (DynamoDB table) is accessible in the `api.hello` function but not in the authorizer function. I am getting the error `Error: "AllowedDomains" is not linked in your sst.config.ts`.

```ts
export const apiGateway = new sst.aws.ApiGatewayV2('ApiGateway', {
  transform: {
    route: {
      handler: {
        link: [
          allowededDomainsTable,
        ],
      },
    },
  },
});

const myAuthorizer = apiGateway.addAuthorizer({
  name: 'myAuthorizer',
  lambda: {
    function: 'packages/functions/src/authorizer.handler',
    response: 'simple',
    payload: '2.0',
    identitySources: [],
  },
});

const defaultRouteOptions = {
  auth: {
    lambda: myAuthorizer.id,
  },
};

apiGateway.route(
  "GET /hello",
  "packages/functions/src/api.hello",
  defaultRouteOptions
);
```

**Comment by gablabelle** [comment]
@paolostyle Thank you very much, it works! You're totally right, linking only the resources that are actually needed per endpoint is much better. Thanks again!

Do you have any recommandations on a good Youtube walkthrough video on SST that would cover most of this stuff ?

**Comment by jayair** [comment]
Maybe not exactly what you are looking for but there's the terminal video: https://www.youtube.com/watch?v=POlZS8PcyZw

**Comment by gablabelle** [comment]
> Maybe not exactly what you are looking for but there's the terminal video: https://www.youtube.com/watch?v=POlZS8PcyZw

Just finished watching it and this is amazing stuff! Thanks mate!

**Comment by gablabelle** [comment]
> Maybe not exactly what you are looking for but there's the terminal video: https://www.youtube.com/watch?v=POlZS8PcyZw

@jayair Just finished watching it and this is amazing stuff! Thanks mate!
