### ISSUE TITLE
Docs: Issue with Cognito JWT auth: Setting the authorization type to JWT requires a valid JWT authorizer

### ISSUE THREAD

**Issue by deweller** [sst/ion#1104]
When I try to create an API Gateway v2 with this code:

```typescript
import { userPool, userPoolClient } from "./auth";

export const api = new sst.aws.ApiGatewayV2("LDDAPI", {
    domain:
        $app.stage === "production"
            ? {
                  name: "ldd-api.leapfroggroup.com",
              }
            : undefined,
});

api.route("POST /generate/embedurl", "packages/functions/src/generate-embed-url.main", {
    auth: {
        jwt: {
            audiences: [userPoolClient.id],
            issuer: $interpolate`https://cognito-idp.${aws.getArnOutput(userPool).region}.amazonaws.com/${userPool.id}`,
        },
    },
});
```

I get this error:

> creating API Gateway v2 Route: operation error ApiGatewayV2: CreateRoute, https response error StatusCode: 400, RequestID: xxxxxxx, BadRequestException: Invalid authorizer ID specified. Setting the authorization type to JWT requires a valid JWT authorizer.: provider=aws@6.52.0

This might be a documentation issue, but the correct way to do this is not clear at all to me after reading the docs.

**Comment by jayair** [comment]
Yeah I can add this to the docs

**Comment by jayair** [comment]
<img width="610" alt="Screenshot 2024-09-23 at 5 27 30 PM" src="https://github.com/user-attachments/assets/4eff2c9b-cb08-45d8-b8e4-0ff9064fdfed">
