### ISSUE TITLE
feature: add ability to set predefined iam role

### ISSUE THREAD

**Issue by antoine-js** [sst/ion#113]
Let's say we want to manage roles externally and so we don't want ion to create those roles automatically for us.

We would then expect an option such as:

```typescript
new sst.aws.Nextjs("MyWeb", {
  // Probably not at this exact place but just to show the idea
  role: "arn:aws:iam:${accoundId}:role/my-role"
});
```

I know it looks somehow similar to serverless framework but I believe its an important points for companies that are strict about role creations.

**Comment by fwang** [comment]
Yeah that makes sense. Let me chat w/ the team real quick and get back to you.

**Comment by fwang** [comment]
In 0.0.242, u can pass in a role to a function - https://ion.sst.dev/docs/component/aws/function/#role

And for `Nextjs`, u set the server function's `role` using transform:
```ts
new sst.aws.Nextjs("MyWeb", {
  transform: {
    server: (args) => {
      args.role = "arn:aws:iam:${accoundId}:role/my-role";
    }
  }
});
```
https://ion.sst.dev/docs/component/aws/nextjs/#transform-server

**Comment by antoine-js** [comment]
Thanks a lot for the quick work @fwang ! But I guess now we would also need the same feature for the image optimizer function as this also involves automatic role creation (which makes CLI command fails if you dont have permission).

Essentially I think this feature should be there for every role creations involved in SST/ion
