### ISSUE TITLE
Unable to reference an existing authorizer function for ApiGatewayV1

### ISSUE THREAD

**Issue by srenault** [sst/ion#1144]
Currently I don't see anyway to reference an existing function when adding a new authorizer to `ApiGatewayV1`. 
I tried to pass the `arn` instead of the handler path without any success.
Another attempt I had was to use the `userPools` method (because I saw it's the only case where SST doesn't create a lambda) and use the transform function to update `authorizerUri`. But it ended up with the following error :
```
TypeError: Cannot read properties of undefined (reading 'nodes')
       at createAuthorizer (file:///Volumes/sredata/dev/prismicio/obelix/.sst/platform/src/components/aws/apigatewayv1-authorizer.ts:130:32)
       at new ApiGatewayV1Authorizer (file:///Volumes/sredata/dev/prismicio/obelix/.sst/platform/src/components/aws/apigatewayv1-authorizer.ts:64:24)
       at ApiGatewayV1.addAuthorizer (file:///Volumes/sredata/dev/prismicio/obelix/.sst/platform/src/components/aws/apigatewayv1.ts:1029:12)
       at services/document-search/infra/search.ts (file:///Volumes/sredata/dev/prismicio/obelix/services/document-search/infra/search.ts:26:24)
       at services/document-search/infra/mod.ts (file:///Volumes/sredata/dev/prismicio/obelix/services/document-search/infra/mod.ts:6:1)
       at run (file:///Volumes/sredata/dev/prismicio/obelix/sst.config.ts:33:31)
       at run (file:///Volumes/sredata/dev/prismicio/obelix/.sst/platform/src/auto/run.ts:32:20)
       at file:///Volumes/sredata/dev/prismicio/obelix/eval.ts:4:22
```

Finally I came up with following solution:

```typescript
const authorizer = api.addAuthorizer({
	name: "custom-authorizer",
	ttl: 0,
	identitySource: "",
	requestFunction: {
		handler: "services/dummy-authorizer/src/index.handler",
	},
	transform: {
		authorizer: {
			authorizerUri: authorizerFunction.invokeArn,
		},
	},
})
```

In this solution I let SST creating the lambda even though I don't use it.
Is there anything I'm missing here?
Also I'm pretty sure I spot a bug with `userPools` as well.

**Comment by fwang** [comment]
@srenault If u have an existing lambda authorizer with id ie. `xxxx`, u can use it directly:
```ts
const api = new sst.aws.ApiGatewayV1("MyApi");
api.route("GET /token", "index.handler", {
  auth: { custom: "xxxx" },
});
```

u don't need to call `addAuthorizer` to create a new authorizer.

lemme know if this works for u.

**Comment by srenault** [comment]
My understanding is I need to create for each ApiGateway a new authorizer that all point to the same lambda authoriser so I don't think it would work.

**Comment by greenlynx** [comment]
Im also hitting this issue - when trying to create a Cognito authorizer I'm getting the `Cannot read properties of undefined (reading 'nodes')` error.

It appears to be caused by https://github.com/sst/ion/commit/6d6a782ba4ab1ead77c01a11fc617debd85a8f36 - it changes line 130 in `platform/src/components/aws/apigatewayv1-authorizer.ts` from:

```ts
authorizerUri: fn?.nodes.function.invokeArn,
```

to:

```ts
authorizerUri: fn!.nodes.function.invokeArn,
```

Note removal of the optional chaining operator. When creating a Cognito authorizer, no lambda is created, so `fn` is `undefined`and this line errors. Manually reverting the change on this line appears to fix the issue for me.

**Comment by greenlynx** [comment]
Has anyone from the project got time to look at my PR please? I've not contributed before so am not sure of the process, but it's a one-liner and should be quick to review 😄
