### ISSUE TITLE
sst dev becomes unresponsive on ctrl-c with a Rails process running

### ISSUE THREAD

**Issue by zacwood9** [sst/ion#1146]
Steps to reproduce:

- start a Rails project in sst dev mode (using `sst.x.DevCommand` or via a service as in the `aws-rails` example)
- wait for rails process to start running
- press ctrl-c to exit sst dev, or select the rails process and press `x` to kill
- sst dev becomes unresponsive

**Comment by jayair** [comment]
Hmm @fwang you worked on this example, did it happen to you?

Also, I'm going to test this over the next week.

**Comment by thdxr** [comment]
is this with mac?

**Comment by thdxr** [comment]
btw i made a bunch of changes to how we spawn processes in the last week can you try it again?

**Comment by zacwood9** [comment]
Confirmed fixed in `3.1.67`, thanks @thdxr! And FYI yes this was with Mac.
