### ISSUE TITLE
Pulumi Cloudflare v5.39.1 is broken

### ISSUE THREAD

**Issue by danielfrg** [sst/ion#1147]
I installed new versions of the providers today and I think version 5.39.1 the [pulumi-cloudflare](https://github.com/pulumi/pulumi-cloudflare/releases/tag/v5.39.1) is broken with SST. Downgrading to 5.39.0 made it work.

Error:

```
|  Error
|  TypeError: pulumi.runtime.invokeOutput is not a function
|      at Module.getZoneOutput (/Users/danrodriguez/code/inmatura/lapalabradeldia.com/.sst/platform/node_modules/@pulumi/getZone.ts:133:27)
|      at infra/dns.ts (file:///Users/danrodriguez/code/inmatura/lapalabradeldia.com/infra/dns.ts:11:32)
|      at init_dns (file:///Users/danrodriguez/code/inmatura/lapalabradeldia.com/.sst/platform/sst.config.1727319069633.mjs:21:56)
```

Another minor bug, when setting the version to a wrong value (for example for pulimi cloudflare `v5.39.0` and running `bun run dev` it got stucked into the `installing providers...` even after I CTRL+C it.

Thanks for all the work guys, love the idea and product :D

**Comment by kane50613** [comment]
same here, wondering how can i have a fixed pulumi version?

**Comment by partmor** [comment]
I've had a similar situation, also using cloudflare.
BUT for me cloudflare 5.39.1 worked; what was causing trouble was aws provider 6.53.0.
Pinning aws to 6.52.0 made it work in my case

**Comment by brunocleite** [comment]
> I've had a similar situation, also using cloudflare. BUT for me cloudflare 5.39.1 worked; what was causing trouble was aws provider 6.53.0. Pinning aws to 6.52.0 made it work in my case

Same as me, setting version to `6.52.0` fixed it. In case somebody else needs to know how to use a fixed version:

```
// noinspection JSUnusedGlobalSymbols
export default $config({
  app(input) {
    return {
      name: "....",
      removal: isDeveloperStage(input?.stage) ? "remove" : "retain",
      home: "aws",
      providers: {
        aws: "6.52.0",
      }
    };
  },
  async run() {
    ...
  },
});
```

**Comment by fwang** [comment]
Fixed in the latest release.

Please re-open if issue persists.
