### ISSUE TITLE
Lambda env vars inconsistent with dev and deploy

### ISSUE THREAD

**Issue by jl4nz** [sst/ion#1172]
When you use dev mode, you get `SST_APP` and `SST_STAGE` as env var in lambda. Using deploy, the lambda function gets `SST_RESOURCE_App` with the object keys `name` and `stage`. 

Is it possible to have the same definition keys for these vars?

**Comment by NeoFoxxo** [comment]
While prod does lack the `SST_STAGE` variable, the `SST_Resource_App` variable is still in dev mode. 

So I just get the stage from that variable but you can get the app name too.
```
const env: { name: string; stage: string } = JSON.parse(
	process.env.SST_RESOURCE_App as string
)

if (env.stage === "prod") {

}
```

**Comment by jl4nz** [comment]
Yes, you're right, `SST_Resource_App` is in dev too, but what would be the consensus then? 

1. Doesn't make sense too me have duplicated data in the env vars
2. For me, is easier to have this in two vars instead of parsing the `SST_Resource_App`.

**Comment by leoalves** [comment]
Is there a reason why you are using `process.env` instead of  `import { Resource } from 'sst'`

**Comment by NeoFoxxo** [comment]
There's not a reason I think I just didn't realise that you could access it `Resource` as well. Or maybe I was getting some weird type errors.

> Is there a reason why you are using `process.env` instead of `import { Resource } from 'sst'`

**Comment by jl4nz** [comment]
+1 

I don't remember seeing in the docs that you can access from the sst `Resource.App`, but it's there now and it's great!
https://sst.dev/docs/reference/sdk/#defaults, thanks!

However, I still think the variable names should be unified :)

**Comment by jayair** [comment]
Yeah we recommend not relying on those environment variables. Treat them as something SST uses internally.

Closing for now.
