### ISSUE TITLE
How to link for python codebase?

### ISSUE THREAD

**Issue by agamm** [sst/ion#1186]
I want to use the https://sst.dev/docs/linking concept in a fastapi project (using Cluser). Is that possible?

**Comment by jayair** [comment]
Yeah we do it here https://sst.dev/docs/start/aws/express

**Comment by agamm** [comment]
Amazing! Thanks for the update.

**Comment by jayair** [comment]
I'll create a separate Python example but you can check your environment variables based on how that example is setup.

**Comment by agamm** [comment]
The whole point of this issue is that it's hard to find an example of the SDK for python, right?
