### ISSUE TITLE
provider request: Add support to Neon (Serverless Postgres)

### ISSUE THREAD

**Issue by eduardo3g** [sst/ion#1199]
Hi SST team

[Neon](https://neon.tech/), the serverless Postgres solution, is getting a lot of traction lately.

They do have a [Terraform provider](https://registry.terraform.io/providers/kislerdm/neon/latest/docs), so it'd be great to have this type of support like you did for Planetscale and used in the [Terminal repo](https://github.com/terminaldotshop/terminal/blob/dev/infra/database.ts).

**Comment by EnriqueRuvalcaba** [comment]
I completely agree! Having SST support for Neon would make integrations much easier. It’d be great to see Neon supported like Planetscale!

**Comment by ajotaos** [comment]
I would love to have this feature available as well

**Comment by sevgit** [comment]
+1 been thinking about this too

**Comment by marceloclp** [comment]
+1

**Comment by thdxr** [comment]
`sst add neon` should now work

this is powered by our new https://github.com/sst/provider repository where you can submit a PR to adapt any terraform provider to sst

**Comment by eduardo3g** [comment]
Amazing, thanks Dax! I'll give it a try ASAP.
