### ISSUE TITLE
IoT doesn't reconnect after leaving `sst dev` running overnight

### ISSUE THREAD

**Issue by jayair** [sst/ion#121]
Functions in live don't respond and the CLI doesn't show anything.

The `.sst/sst.log` has `mqtt reconnecting`.

**Comment by dmeehan1968** [comment]
I seem to get this is the machine is left unattented and sleeps

**Comment by dmeehan1968** [comment]
I also note that I get this if the network connection drops (e.g. general network connectivity issue), the server doesn't seem to re-establish the connection and I'm seeing 'endpoint discovery' failures which require me to restart sst dev.
