### ISSUE TITLE
cloudflare: config provider configuration issues (`accountId`, `apiToken` ignored)

### ISSUE THREAD

**Issue by qw-in** [sst/ion#122]
Continuation from #93

The only way I can successfully deploy a cloudflare worker (with `apiToken` auth) is by passing environment variables:

```shell
CLOUDFLARE_DEFAULT_ACCOUNT_ID="..." CLOUDFLARE_API_TOKEN="..." sst deploy
```

Passing these in `sst.config.ts` no longer throws validation errors (as seen in #93) but does not actually seem to set the values. The following config throws a cloudflare api error:

```ts
{
  home: "aws", // in case relevant
  providers: {
    cloudflare: {
      // @note: `accountId` is not in the types, but in some examples
      accountId: "...",
      apiToken: "..."
    }
  }
```

```shell
sst deploy

A request to the Cloudflare API (/accounts/undefined/workers/subdomain) failed.
```

I don't think any of the provider config values are making it to pulumi?. Trying the above with the `accountId` set via environment variable:

```shell
CLOUDFLARE_DEFAULT_ACCOUNT_ID="my-account" sst deploy

A request to the Cloudflare API (/accounts/my-account/workers/scripts/my-workerscript/subdomain) failed.
```

---

I'll give fixing it a shot out of interest, but I've never written go in my life so pretty low chance it will be helpful lol. ~If you have any docs on how to build/run the local sst that would be awesome. I'd be happy to add it to a like `contributing.md` if you're into that kind of thing too~ edit: this seems to work `goreleaser build --snapshot --single-target`

**Comment by thdxr** [comment]
Yeah we're still working on cloudflare docs / design so there's some confusing stuff. so from your logs `apiToken` is not actually ignored - we currently require you to pass in `CLOUDFLARE_DEFAULT_ACCOUNT_ID` with the cloudflare provider

reason for this is the underlying cloudflare provider does not have this concept, but we want to include it. unfortunately extending the args with it does not work well so we're relegated to an environment variable

still thinking this through but hopefully that helps

**Comment by thdxr** [comment]
just to make it a bit more clear you have to do `CLOUDFLARE_DEFAULT_ACCOUNT_ID=xxx sst deploy` AND have `apiToken` specified in the providers.cloudflare block

**Comment by thdxr** [comment]
going to close this for now as we're working through the design of all this - feel free to reopen if you have issues

**Comment by qw-in** [comment]
@thdxr for me the cloudflare provider config is ignored when `home: "aws"` - tried my hand at fixing it in #128

**Comment by thdxr** [comment]
our design is a bit weird right now so unfortunately that PR probably is looking at the wrong approach

we don't want to touch *anything* when you are simply using a provider, can you explain to me what config is being ignored when home is "aws" ? provider config should just be passed through

**Comment by thdxr** [comment]
i just tested with the following config and it worked for me

```
/// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app(input) {
    return {
      name: "test",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: {
        cloudflare: {
          apiToken: "xxxx",
        },
      },
    };
  },
  async run() {
    const fn = new sst.aws.Function("MyFunction", {
      handler: "./src/index.handler",
      streaming: true,
      url: true,
      timeout: "15 minutes",
      copyFiles: [
        {
          from: "./package.json",
        },
      ],
    });
    const worker = new sst.cloudflare.Worker("MyWorker", {
      handler: "./src/index.ts",
    });
    return {
      url: fn.url,
    };
  },
});
```

**Comment by qw-in** [comment]
Thanks for taking a look, makes sense I'll close the pr


I swear I was getting different behaviour - I'll try to reproduce when I can. I'll make an example report if I can

**Comment by qw-in** [comment]
Still was having issues but I've just decided to move to a `.env` file, it's cleaner anyway and seems like this issue is just specific to me. Cheers 🍻
