### ISSUE TITLE
Migrate from open-next to @opennextjs/aws starting from version 3.1.4

### ISSUE THREAD

**Issue by Chenalejandro** [sst/ion#1227]
Currently if I try to use openNextVersion: "3.1.4" the deployment will fail.

**Comment by sommeeeer** [comment]
#1271

**Comment by MisterJimson** [comment]
Is there a workaround for sstv2?

**Comment by sommeeeer** [comment]
> Is there a workaround for sstv2?

use custom `buildCommand`.
