### ISSUE TITLE
Subscribe/Route design change

### ISSUE THREAD

**Issue by fwang** [sst/ion#124]
Currently there's no way to get the Function created from:
```ts
queue.subscribe("index.handler");
api.route("GET /", "index.handler");
```

Will have the above functions return the function.

**Comment by fwang** [comment]
Implemented in v0.0.254

**Comment by dror-weiss** [comment]
@fwang , I need to get a route's function role.
I'm doing this now like this:
```ts
    const routeFunction = route.function.name.apply(name =>
      aws.lambda.getFunction({ functionName: name })
    );
const role = routeFunction.role;
```

Is there a better way to do it? (`.sst/platform/src/components/aws/function` doesn't expose it)

**Comment by jayair** [comment]
Btw, `.route` returns this https://ion.sst.dev/docs/component/aws/apigatewayv2/#apigatewayv2route

**Comment by dror-weiss** [comment]
@jayair , `.route` doesn't have a `.role` property, hence my solution.
I guess I will need to open a new feature retuest.

**Comment by jayair** [comment]
@dror-weiss Oh does `.function.nodes.role` work?

**Comment by dror-weiss** [comment]
@jayair Yes! thanks!!
