### ISSUE TITLE
secretArn and clusterArn undefined AWS RDS, Next.js, Drizzle

### ISSUE THREAD

**Issue by lxhan** [sst/ion#1293]
Using AWS RDS, Next.js, Drizzle and getting this error when trying to do migration or open drizzle studio:

<img width="471" alt="image" src="https://github.com/user-attachments/assets/02ba3bc6-d716-4445-a1ab-9f5c15c585ae">

<img width="664" alt="image" src="https://github.com/user-attachments/assets/5868d2b7-3373-4eee-9db5-df449d40de71">

<img width="473" alt="image" src="https://github.com/user-attachments/assets/20e7e10a-8227-477b-897f-b9c98858c6db">

Everything deployed with no errors, just can't get ARN

_Originally posted by @lxhan in https://github.com/sst/ion/issues/623#issuecomment-2415963312_

**Comment by nhamilton1** [comment]
What version of sst are you on? `3.1.70` and after uses RDS Postgres instead of aurora. You would have to change it to `new sst.aws.Postgres.v1` to use aurora. 

https://sst.dev/docs/component/aws/postgres-v1/

**Comment by lxhan** [comment]
> What version of sst are you on? `3.1.70` and after uses RDS Postgres instead of aurora. You would have to change it to `new sst.aws.Postgres.v1` to use aurora.
> 
> https://sst.dev/docs/component/aws/postgres-v1/

I'm on sst version 3.2.26 and following this guide https://sst.dev/docs/start/aws/drizzle and this one from drizzle https://orm.drizzle.team/docs/connect-aws-data-api-pg. 
So this part:
```
secretArn: Resource.MyPostgres.secretArn,
resourceArn: Resource.MyPostgres.clusterArn,
```
is for Aurora only? What should I do if I want to use RDS?

**Comment by nhamilton1** [comment]
The drizzle docs for this have not been updated yet and it's showing the old way of doing it. The new way would look something like this:

```ts
// drizzle.config.ts
import { defineConfig } from "drizzle-kit";
import { Resource } from "sst";

export default defineConfig({
  dialect: "postgresql",
  dbCredentials: {
    user: Resource.PostgresDatabase.username,
    password: Resource.PostgresDatabase.password,
    host: Resource.PostgresDatabase.host,
    port: Resource.PostgresDatabase.port,
    database: Resource.PostgresDatabase.database,
  },
  schema: ["./src/**/*.sql.ts"],
  out: "../../migrations",
});

```  

```ts
// sst.config.ts
/// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app(input) {
    return {
      name: "project-name-here",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    const vpc = new sst.aws.Vpc("IonVPC", {
      bastion: true, // make sure to enable this so you can use sst tunnel to connect to the database from your local machine
    });

    const database = new sst.aws.Postgres("PostgresDatabase", {
      vpc,
      proxy: true,
    });

    new sst.aws.Nextjs("NextjsSite", {
      vpc,
      link: [database],
    });
  },
});
```

```ts
import { Resource } from "sst";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";

const client = new Pool({
  user: Resource.PostgresDatabase.username,
  password: Resource.PostgresDatabase.password,
  database: Resource.PostgresDatabase.database,
  host: Resource.PostgresDatabase.host,
  port: Resource.PostgresDatabase.port,
});

export const db = drizzle(client, {
  logger:
    process.env.DRIZZLE_LOG === "true"
      ? {
          logQuery(query, params) {
            console.log("query:", query);
            console.log("params:", params);
          },
        }
      : undefined,
});
```

**Comment by lxhan** [comment]
Thank you very much!

**Comment by katsikasQ** [comment]
> What version of sst are you on? `3.1.70` and after uses RDS Postgres instead of aurora. You would have to change it to `new sst.aws.Postgres.v1` to use aurora.
> 
> https://sst.dev/docs/component/aws/postgres-v1/

Thank you for your comment. I was wondering what happened there.

What was wrong by using Amazon Aurora Serverless v2?
And from now on, how are we supposed to deploy  Serverless Postgres?

**Comment by nhamilton1** [comment]
here is what Dax said about it on [discord](https://discord.com/channels/983865673656705025/1293503527418855476/1293953384109445223). I will also copy the text here: 

```
the pain points with aurora is
- expensive to start
- quirky incompatibilities with normal postgres stuff
- data api ended up being really crappy in practice
- all of this is worth it if you are expecting extremely large scale

most people would be fine with regular RDS which has none of those problems and we added sst tunnel to make it easy to connect to even without the data api, so we figured it's the default

we will likely rename the old setup to sst.aws.Aurora for people who want it - our thinking is if you're expecting that level of scale you know what you're doing and can opt into aurora 
```
