### ISSUE TITLE
Drizzle/Postrges example is out of date

### ISSUE THREAD

**Issue by RockBacon9922** [sst/ion#1304]
The drizzle postgress example is out of date.

[https://sst.dev/docs/start/aws/drizzle](https://sst.dev/docs/start/aws/drizzle)

In the example it connects to the db using a secretarn and a clusterarn.

According to my research secretarn and clusterarn are no longer a property on sst.aws.postgress

**Comment by zohaibakber** [comment]
https://github.com/sst/ion/commit/2be58378b4b22d8d1161a2dba7ff44529668bd9b

**Comment by ajotaos** [comment]
Is it possible to include in the example a way to mimic the behavior that dev and deploy had on migrations on v2?

**Comment by jayair** [comment]
Yeah updated it yesterday. Closing this now. 

@ajotaos right now the migration process is a bit manual. We do have some plans on what we need to do to automate it.
