### ISSUE TITLE
Removing the SSM param used for secrets stalls deploys

### ISSUE THREAD

**Issue by jayair** [sst/ion#133]
The deploy is just stuck on `Deploying...`. We should fail the build with the right error.

https://discord.com/channels/983865673656705025/1177071497974648952/1223306110505582782

**Comment by jayair** [comment]
From Dax:

> maybe i shoulda put DO_NOT_DELETE in the key name

**Comment by thdxr** [comment]
added warning to SSM description + it prints a proper error in 0.0.239
