### ISSUE TITLE
Missing dev mode permissions when functions are assigned a custom role

### ISSUE THREAD

**Issue by trinitrotoluene** [sst/ion#145]
I previously used something equivalent to this snippet as the execution role for my functions:

```
  const role = new Role(stack, "Role", {
    assumedBy: new ServicePrincipal("lambda.amazonaws.com"),
    managedPolicies: [...],
  });
```

and ported this over to be 

```
    const executionRole = new aws.iam.Role("LambdaExecutionRole", {
      assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({
        Service: "lambda.amazonaws.com",
      }),
      managedPolicyArns: [...],
    });
```

when running in live mode this started throwing errors relating to missing various IoT permissions that I assume were being implicitly added before.

**Comment by WayneBuckhanan** [comment]
Looks like [v2 functions](https://github.com/sst/sst/blob/d67d9c99b1882dddb1219a482d4956d66a47c4db/packages/sst/src/constructs/Function.ts#L1000) and [ion Functions](https://github.com/sst/ion/blob/7097d7abfd5941e2babbfc6232876658a1a98c74/pkg/platform/src/components/aws/function.ts#L1225) both apply similar policies:
```
actions: ["iot:*"],
resources: ["*"],
```

**Comment by fwang** [comment]
When an existing IAM role is passed in, the Function uses the role as is. The use case I had in mind is: IAM roles are created centrally by the security team. Developers are not allowed to create roles or attaching additional policies to the roles they are provided with. It is expected that the roles come w/ required permissions.

Does that make sense? /cc @trinitrotoluene @WayneBuckhanan

**Comment by trinitrotoluene** [comment]
@fwang I'm not 100% sure that I understand the rationale here - I agree that for a regular `sst deploy` you wouldn't want random other permissions injected - but this change is specific to `sst dev` which won't work unless you attach an `IoT:*` policy to either all roles created by the function, which adds unnecessary permissions to the role created by regular deploys, _or_ you add some boilerplate to change which policies are attached based on `$app.stage` (not sure what the correct way to tell you're in live lambda mode is).

Either way, I think it should at the very least get a mention in places like this https://ion.sst.dev/docs/component/aws/function/#role

e.g.

> If you're setting a custom execution role for your Function, it must be granted `IoT:*` permissions for live lambda debugging to work correctly. You can conditionally attach this by checking [insert whatever best practice for telling you're in dev mode is].
