### ISSUE TITLE
Lambda code not rebuilding on infrastructure changes with SST Dev

### ISSUE THREAD

**Issue by cbsluke** [sst/ion#148]
I have noticed the following issue and not sure if it is picked up:

1. Create Gateway
2. Run sst dev
3. Modify lambda in gateway code (auto rebuilds)
4. Modify the sst.config or some part of the infra
5. Try modify lambda code again and it doesn't rebuild.

Only way I have found to get this building automatically again is by doing a sst remove or sometimes just causing the whole lambda to deploy again. Any ideas?

**Comment by thdxr** [comment]
I made some changes to how this all works, v0.0.250 potentially will fix it

**Comment by thdxr** [comment]
will mark as done, let me know if it comes back
