### ISSUE TITLE
Need a way to easily set `links` and potentially other defaults for all `ApiGatewayV2` lambda functions  

### ISSUE THREAD

**Issue by lagnat** [sst/ion#151]
Similar to sst v2 `new Api(... { defaults: ... } )`

**Comment by jayair** [comment]
https://discord.com/channels/983865673656705025/1177071497974648952/1224540483536293919

**Comment by fwang** [comment]
Currently, it can be done like this:
```ts
const defaults = { timeout: "5 seconds" };
api.route("GET /a", { handler: "src/a.handler", ...defaults });
api.route("GET /b", { handler: "src/b.handler", ...defaults });
```

We will probably implement something like this:
```ts
const api = new Api("MyApi", {
  transform: {
    routes: {
      function: {
        timeout: "5 seconds",
      }
    }
  }
});
```

**Comment by jayair** [comment]
Added in https://github.com/sst/ion/releases/tag/v0.0.331

Docs: https://ion.sst.dev/docs/component/aws/apigatewayv2/#transform-route
