### ISSUE TITLE
Feat: Fallbacks for secrets

### ISSUE THREAD

**Issue by jayair** [sst/ion#162]
Figure out how we want to do fallbacks for secrets

**Comment by oyed** [comment]
would be awesome to get this - been using ion a little while now and the only struggle with onboarding devs is lack of secret fallback requiring me to dish out loads of secrets to everyone

**Comment by alekseyrozh** [comment]
Same it almost returns the need for .env files

**Comment by thdxr** [comment]
released in v3.0.81
