### ISSUE TITLE
feat: default to production when running `sst deploy`

### ISSUE THREAD

**Issue by AdditionAddict** [sst/ion#193]
Following the docs `sst deploy` uses personal stage by default rather than default stage production.

Alternative: update docs with `sst deploy --stage production`

ion 0.0.270

**Comment by AdditionAddict** [comment]
@arpadgabor To be fair, I managed to confuse myself as the what the default behaviour should be. A default `dev` would look a touch weird without the "local" tag in the sst console. Idk, maybe it's fine as is?

**Comment by arpadgabor** [comment]
Thing is, there's a difference in behaviour between `deploy` and `dev`. `sst dev` deploys dummy code into your lambdas and that code forwards requests to a local server that is running on your computer. `sst deploy` will create a full-fledged deploy. Personally, I don't want to ever "deploy" to a local stage, as I use that for local development. However when I do want to do a `deploy` I want it to go into a place where all components work completely in the cloud.

Also, there are cases when you want to exclude a resource from a cloud deployment (e.g. databases or other heavy/expensive resources), so an `sst deploy` that targets a local stage could potentially crash.

**Comment by jayair** [comment]
@AdditionAddict is this from the quick starts? Like this one for example, https://ion.sst.dev/docs/start/nextjs

We've changed some things in Ion with how frontends work in your personal stage. It makes it quicker to deploy your app from your personal stage.

Maybe we can add a separate note that tells people to deploy to prod with a separate stage.

**Comment by AdditionAddict** [comment]
@jayair yeah the remix one, was just surprised coming from sst v2

I basically never want to deploy personal, it'd always be staging/production

**Comment by jayair** [comment]
Yeah I'll write a separate doc on "Going to production" but for the quick start it's okay to deploy your personal stage.

Closing this for now.
