### ISSUE TITLE
Astro Server Route cannot receive POST, PUT, or DELETE requests, resulting in a 403 error

### ISSUE THREAD

**Issue by gel1123** [sst/ion#196]
I am building a system using the `<form>` tag and Astro's server endpoints. I have defined a route in the Astro server endpoints to handle POST requests. However, after deploying with SST, POST requests to this route result in a 403 error in the AWS environment. I think this is because the SST Ion's Astro component, by default, only permits HTTP methods like GET, HEAD, and OPTIONS for server routes, and does not allow PUT, DELETE, or POST. Currently, it seems there are no options within the Astro component settings to change the permitted HTTP methods.

If I'm operating Astro in SSR (Server-Side Rendering), I would really like to be able to receive POST, PUT, and DELETE requests in Server Routes. I suspect the issue might be due to the CloudFront origin group, which, by specification, origin group only allows configurations for GET, HEAD, and OPTIONS...

I have created a repository that reproduces this issue: 

https://github.com/gel1123/astro-sandbox-001

**Comment by fwang** [comment]
@gel1123 you'd need to specify the server routes in ur `astro-config.mjs` like this — https://github.com/sst/sst/tree/master/packages/astro-sst#server-routes

We are working on some improvements so that you won't need to do this. I will keep you posted.

**Comment by gel1123** [comment]
@fwang 
Thank you so much for your help; I really appreciate it!
