### ISSUE TITLE
Using transforms in conjunction with `Remix` is unreliable

### ISSUE THREAD

**Issue by mhodgson** [sst/ion#198]
Using the `$transform` function or using the `transform` parameter for `sst.aws.Remix` can lead to broken builds without a clear indication of why. For example, one might want to add a property to the `nodejs` config.
```typescript
$transform(sst.aws.Function, (args) => {
  args.nodejs = {
    format: "esm"
  }
});
```
Unfortunately this *overwrites* the default config that is set by the `sst.aws.Remix` construct. In this case it removes the polyfill that is added [here](https://github.com/sst/ion/blob/dev/pkg/platform/src/components/aws/remix.ts#L557). 

One way to overcome this is to deep merge the configs, but this can potentially lead to other subtle issues (when you really do want to overwrite an entire object/array): 
```typescript
import merge from "deepmerge";

new sst.aws.Remix("VBOTApp", {
  transform: {
    server: (args) => merge(args, functionDefaults),
  }
});
```

Another example of unexpected outcomes:
```typescript
$transform(sst.aws.Function, (args) => {
  args.environment = {
    FOO: "Bar"
  }
});
```
This code does not result in the environment variable being added the function. Instead, in the case of `sst.aws.Remix`, the user needs to declare env variables this way for them to take effect: 
```typescript
new sst.aws.Remix("Example", {
  environment: {
    FOO: "bar"
  }
});
```

All of these issues can be worked around with careful consideration and merging, but the current development experience is frustrating since these are unexpected issues that are difficult to track down.

**Comment by JanStevens** [comment]
I like to add a more general case, using following global `$transform`

```typescript
$transform(sst.aws.Function, (args) => {
  args.timeout = '30 seconds';
  args.memory = '1024 MB';
  args.environment = {
    NODE_OPTIONS: '--enable-source-maps',
    ENV: $app.stage,
  };
  args.logging = {
    retention: '3 months',
  };
});
```

And later on defining a function as

```typescript
new sst.aws.Function('AppsyncAuthorizer', {
  handler: 'src/appsync/authorizer.handler',
  role: role.arn,
  memory: '128 MB',
  nodejs: {
    minify: true,
    sourcemap: false,
  },
});
```

The above function ends up with `1024MB` memory where one would expect it to be 128MB (since we "overwrite" it for this specific case here.

I would expect that `$transform` sets global defaults, but allow per function overwrite

**Comment by jayair** [comment]
Yeah transform is a little different, it's transforming the args before they are passed into the component. So I could do something like this:

```ts
$transform(sst.aws.Function, (args) => {
  args.memory = args.memory || '1024 MB';
});
new sst.aws.Function('FunctionA', {
  handler: 'index.handler',
  memory: '128 MB',
});
new sst.aws.Function('FunctionB', {
  handler: 'index.handler',
});
```
