### ISSUE TITLE
Feature: GraphQL with AppSync

### ISSUE THREAD

**Issue by toddjcrane** [sst/ion#205]
Requesting feature parity with SST v2 with regards to GraphQL with AppSync.

https://sst.dev/examples/how-to-create-a-serverless-graphql-api-with-aws-appsync.html

**Comment by thelegendtubaguy** [comment]
Would be extra awesome if we got some SST candy inside of resolver code as well.  Thinking stuff like access to $app.name and $app.stage.  Would have to be some sort of template I guess.

**Comment by cgcompassion** [comment]
It's Christmas! https://ion.sst.dev/docs/component/aws/app-sync/
