### ISSUE TITLE
feat(nextjs): Ability to pass environment variables to imageOptimization or transform the function

### ISSUE THREAD

**Issue by cmanou** [sst/ion#212]
Would be great if either a transform or environment variables were exposed for the imageOptimization function so that the new `OPENNEXT_STATIC_ETAG` env var can be set. 

https://open-next.js.org/inner_workings/components/image_optimization 

Happy to help implement if there is a decision on best way to expose it.

**Comment by cmanou** [comment]
@fwang did you have any thoughts on this as I said I am more than happy to  implement it. Just unsure whether you would prefer just exposing environment as an additional param in here https://github.com/sst/ion/blob/72fab0f5805e09c673cf781a4e5e2dc24fbd4750/pkg/platform/src/components/aws/nextjs.ts#L322-L338 or swapping that param to be a transform which is probably more of a breaking change?

**Comment by fwang** [comment]
@cmanou we just added an imageOptimization.staticEtag flag — https://github.com/sst/ion/pull/272

Will be in v0.0.323
