### ISSUE TITLE
Nextjs: permissions and environment not passed to function

### ISSUE THREAD

**Issue by dmeehan1968** [sst/ion#215]
It appears that neither the `args.permissions` nor `args.environment` members are passed to the underlying function during creation. Those members are explicitly set when creating the `defaultFunctionProps` without reference to any passed in `args`.

See [https://github.com/sst/ion/issues/213#issuecomment-2049592634](https://github.com/sst/ion/issues/213#issuecomment-2049592634) for workaround.

Related: [https://github.com/sst/ion/issues/213](https://github.com/sst/ion/issues/213)

**Comment by ghardin1314** [comment]
+1 experiencing this issue. Thanks for providing the workaround

**Comment by fwang** [comment]
Should be fixed in [v0.0.324](https://github.com/sst/ion/releases/tag/v0.0.324).

Feel free to reopen if the issue persists.
