### ISSUE TITLE
Feat: Set API function defaults

### ISSUE THREAD

**Issue by jayair** [sst/ion#222]
Got a couple of requests

https://discord.com/channels/983865673656705025/1177071497974648952/1228382859161632930
https://discord.com/channels/983865673656705025/1177071497974648952/1228370718761291786

**Comment by aquarazorda** [comment]
This is the only thing that's missing for me to fully move to ion.

**Comment by JoeCase** [comment]
@aquarazorda Using a workaround right now in the mean time which seems to be working and isn't too much extra:
`  async run() {
    const defaultFuncProps = { link: [] };
    const bucket = new sst.aws.Bucket("Bucket");
    defaultFuncProps.link.push(bucket);

    const api = new sst.aws.ApiGatewayV2("Api");

    api.route("GET /", {
      ...defaultFuncProps,
      handler: "functions/api/health.handler",
    });
  },`
