### ISSUE TITLE
console invoke does not work with hono.

### ISSUE THREAD

**Issue by michael-land** [sst/ion#232]
with console

![CleanShot 2024-04-13 at 00 03 00@2x](https://github.com/sst/ion/assets/33362998/90d1c284-4a48-4af9-8792-3db518871fed)

with curl

![CleanShot 2024-04-13 at 00 03 51@2x](https://github.com/sst/ion/assets/33362998/e1e5e276-3bc2-49bf-816b-000fc13db58b)

to reproduce:

1. run this example https://github.com/sst/ion/tree/dev/examples/aws-hono
2. open console
3. invoke function

**Comment by thdxr** [comment]
if you invoke a function from the console you are sending an empty payload (unless you specify one) - the lambda function is expecting a full web request event<br><br>best to trigger from the url using your preferred method - can then replay them in the console
