### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by arobida** [sst/ion#235]
The cloudflare examples all give me the same error when running the cli command:

```bash
sst dev
```

The cli outputs this error:

```bash
arobida Dev/projects/ssthono via
11:32 on :
sst dev
v1.1.3 via
@ v21.7.1 took 3s
panic: runtime error: index out of range [0] with length o
goroutine 1 [running]:
github.com/sst/ion/pkg/project/provider. (*CloudflareProvider). Init(0x1400016f4d0, 10x1400016f3b0?, 0x140 16f3e0)
/home/runner/work/ion/ion/pkg/project/provider/cloudflare.go:62 +0x458
github.com/sst/ion/pkg/project. (*Project).LoadHome(0x14000522840)
/home/runner/work/ion/ion/pkg/project/project.go:217 +0x19c
main.initProject (0x14000614050)
/home/runner/work/ion/ion/cmd/sst/main.go: 1544 +0x63c
main.init. func15(0x14000614050)
/home/runner/work/ion/ion/cmd/sst/main.go: 1155 +0x34
main.run()
/home/runner/work/ion/ion/cmd/sst/main.go: 158 +0x6cc
main.main ( )
/home/runner/work/ion/ion/cmd/sst/main.go:50 +0x130
```

It's happened on multiple machines now and I have even cloned an example from the repo to try and make it work. 

Here is a video showing the error:
https://github.com/sst/ion/assets/22987334/1b0849b4-b764-4b52-8040-4e0db4eae53d

**Comment by thdxr** [comment]
what format of API key are you using?

**Comment by arobida-adzz** [comment]
> what format of API key are you using?

I'm using the api token and followed the link in the example for making a cloudflare token

I have tried:
1. exporting the token in my terminal
2. placing the token inside the provider directly in the sst.config.ts
3. placing it in a .env file

All attempts end up producing the same error

**Comment by nourmalaeb** [comment]
actually no issue when i set an env variable for `CLOUDFLARE_DEFAULT_ACCOUNT_ID`

**Comment by arobida** [comment]
When you set it in a .env file? Or do you export them from the terminal?

**Comment by nourmalaeb** [comment]
Yes — set it in an .env file. I also found out that the .env file will be read if it’s named `.env` but not if it is `.env.local`. 

My .env file looks like this:

```
AWS_ACCESS_KEY_ID=<access_key_id>
AWS_SECRET_ACCESS_KEY=<secret_access_key>
CLOUDFLARE_DEFAULT_ACCOUNT_ID=<account_id>
CLOUDFLARE_API_TOKEN=<token>
```

**Comment by thdxr** [comment]
version v0.0.342 should give you a better error message around this

**Comment by arobida** [comment]
The zone dns template in with cloudflare apitokens but it did work with the workers token template.
