### ISSUE TITLE
feat: Allow configuration of 'exclude' files/directories for dev mode file watching

### ISSUE THREAD

**Issue by dmeehan1968** [sst/ion#237]
When running `sst dev --verbose` I can see that its using a file watcher to know when to rebuild changes.  This seems to be detecting changes in my `.git` folder, and settings updates from my IDE (Jetbrains PHPstorm), which are unnecessary to track.  It would be helpful if sst have a config option to provide one or more patterns to exclude from watching.  Whilst it doesn't seem to excessively affect performance, it might help it 'play nice' with other tools.

**Comment by thdxr** [comment]
can you list all the folders that should be ignored? even if we allow it to be customized we need to have an extensive default list - i'm adding .git to it now

**Comment by dmeehan1968** [comment]
Given that the list of folders is likely to be in the user domain, I don't think it should be pre-populated, nor would it be easy to predict.  Another case would be dotfolders or project dirs used by IDE's, as they usually don't contain code associated with the build.  Merely providing an optional 'excludes' array of regexes or globs would probably suffice.

**Comment by jererobles** [comment]
I have over 10k assets in `public/` and it feels like sst should not be watching this folder because `sst dev` crashes with:

```
time=2024-04-18T15:51:16.605+03:00 level=ERROR msg="exited with error" err="\"/Users/xxxxx/myproject/public/resources/figure/xxxxxx.png\": too many open files"
```

**Comment by jayair** [comment]
@jererobles Which version of Ion?
