### ISSUE TITLE
Support external resources

### ISSUE THREAD

**Issue by ennioVisco** [sst/ion#243]
A key aspect to allow migration to Ion is being able to ["link"](https://ion.sst.dev/docs/linking/) resources that are not defined as Ion ones (e.g. a pre-existing S3 bucket), either by allowing to link standard AWS arn-based resources and/or by allowing to link Pulumi resources define outside of Ion!

**Comment by ennioVisco** [comment]
The new `Linkable` API documented in https://github.com/sst/ion/releases/tag/v0.1.53 seems to fit for the purpose, although a few examples would definitely be beneficial w.r.t linking entire resources (e.g. a pre-existing S3 bucket)

**Comment by jayair** [comment]
Yeah adding the docs for this https://ion.sst.dev/docs/component/linkable/

**Comment by jayair** [comment]
Closing for now
