### ISSUE TITLE
Allow to specify the lambda name / configurable linking name

### ISSUE THREAD

**Issue by JanStevens** [sst/ion#244]
Hi,

For cloudwatch log groups you can overwrite the name of the log group (which is handy) but for Lambda functions this is not possible, in the transformation the current lambda name is not defined and setting it explicitly does nothing

```typescript
transform: {
  function: (args) => {
    // This logs { name: undefined }
    console.log({ name: args.name });
    // This does nothing
    args.name = 'i-would-like-to-set-the-name-explicitly'
  },
}
```

Personally I'm not a huge fan of the current naming convention, since it mixes dashes with camelcase strings like `app-stage-WebhookHandlerFunction`. When you need to quickly look for a function or log group its hard to scan these kind of strings. Also the `Function` at the end is meaningless information since it's a lambda so obviously its a function (also in cloudwatch its prefixed with `/aws/lambda` so its obvious).

Looking at the code I think this is mainly done for supporting linking resources but what about the following idea:

- remove the resource name requirements so it aligns better with how pulumi defines resources (it needs to be unique but you can use whatever naming scheme you want)
- allow every component to specify a name so you can have a different Pulumi component name vs actual name of the resource in AWS console
- for linking automatically use the `PascalCase` of the name resource but also allow to make it configurable (with `linksName` or something else)

**Comment by JanStevens** [comment]
Didn't knew you could also add `$transform` on pulumi resources so the following 2 transformations will make all lambda and log group names consistent

```typescript
import { depascalize } from 'fast-case';

const appName = `${$app.name}-${$app.stage}`;

$transform(aws.lambda.Function, (args) => {
  // removes the app name / stage prefix and Function suffix
  const cleanedName = depascalize(
    args.name
      ?.toString()
      ?.replace(`${appName}-`, '')
      ?.replace('Function', '') ?? '',
    '-',
  );
  // builds up the name of the function
  args.name = `${appName}-${cleanedName}`;
});

$transform(sst.aws.Function, (args) => {
  args.transform = {
    logGroup: (logGroupArgs) => {
      // ensures standerised naming
      const cleanedName = depascalize(
        logGroupArgs.name
          ?.toString()
          ?.replace(`/aws/lambda/${appName}-`, '')
          ?.replace('Function', '') ?? '',
        '-',
      );
      logGroupArgs.name = `/aws/lambda/${appName}-${cleanedName}`;
    }
    ...args.transform
  }

})
```

**Comment by jayair** [comment]
@san4d open a new issue for exposing log group through transform?

**Comment by fwang** [comment]
@JanStevens two changes were made recently:
- `Function` now takes `name` https://ion.sst.dev/docs/component/aws/function/#name
- Component names don't have to be pascal case (though still recommended). ie. this works now
```ts
// in sst.config.ts
new sst.aws.Function("my-function", { ... });

// in lambda code
Resource["my-function"]
```

Feel free to reopen if i missed anything.

**Comment by shellscape** [comment]
@fwang I think the docs need an update here https://sst.dev/docs/components/#name to reflect the (outstanding btw) changes you made for allowing hyphenated names et al.
