### ISSUE TITLE
Non-unique component names when using awsx.ecs.FargateTaskDefinition

### ISSUE THREAD

**Issue by fredrikahs** [sst/ion#250]
When creating an `awsx.ecs.FargateTaskDefinition` I get the following issue:

```
|  Creating    MyTaskDefinition awsx:ecs:FargateTaskDefinition → MyTaskDefinition aws:ecs:TaskDefinition
|  Created     MyTaskDefinition awsx:ecs:FargateTaskDefinition → MyTaskDefinition aws:ecs:TaskDefinition
|  Error        Invalid component name "MyTaskDefinition". Component names must be unique.
⠼  Finalizing...time=2024-04-16T13:31:16.747Z level=INFO msg="done running stack command"
time=2024-04-16T13:31:16.747Z level=INFO msg="stack command complete"
⠇  Finalizing...time=2024-04-16T13:31:17.143Z level=INFO msg="INFO putting links app=sst-infrastructure stage=dev"

×  Failed
   Invalid component name "MyTaskDefinition". Component names must be unique.
```

I'm guessing this has to do with the awsx package creating it's own internal components with the same name? See https://github.com/pulumi/pulumi-awsx/blob/master/awsx-classic/ecs/taskDefinition.ts#L81

Is there any way to get around this?

**Comment by devakrishna33** [comment]
https://github.com/sst/ion/blob/f670ca504d9b6b66665f78febbd986a569f099c7/pkg/platform/src/auto/run.ts#L63

I have logged the args here it's coming as `
{
  args: {
    resource: LifecyclePolicy {
      __pulumiResource: true,
      __pulumiType: 'aws:ecr/lifecyclePolicy:LifecyclePolicy',
      __transformations: [Array]
    },
    type: 'aws:ecr/lifecyclePolicy:LifecyclePolicy',
    name: 'populatefensworkerrepository',
    props: { policy: undefined, repository: undefined, registryId: undefined },
    opts: {
      version: '6.32.0',
      urn: 'urn:pulumi:dev::misc::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::populatefensworkerrepository'
    }
  }
}
`

since type is not starting with pulumi it's not ignored, instead we can have a condition like `
if (args.opts.urn?.startsWith("urn:pulumi")) {
  return;
}
`

this seems to fix the problem for now

**Comment by fwang** [comment]
Relaxed naming convention in https://github.com/sst/ion/commit/a3fd8fa92d559c91b89731faa6a9b843c60f95af. This will be possible in the next release.
