### ISSUE TITLE
Configure vpc for next.js lambda?

### ISSUE THREAD

**Issue by danielbush** [sst/ion#261]
Is it possible to configure vpc, subnets and security group (and execution role) for the default lambda deployed by `sst.aws.Nextjs`?  (similar to https://ion.sst.dev/docs/component/aws/function/#vpc ).  If not, is it planned?

**Comment by kane50613** [comment]
Same problem here, tried `nextjs.nodes.server.apply()` seems like not the right way.

**Comment by kane50613** [comment]
maybe we could patch `createServersAndDistribution` manually in `ssr-site.ts` as a temp solution.

**Comment by danielbush** [comment]
If you do something let me know.  I'll look at it again today.

**Comment by danielbush** [comment]
> Same problem here, tried `nextjs.nodes.server.apply()` seems like not the right way.

@kane50613  Incidentally, did you get anywhere with that?

**Comment by kane50613** [comment]
> > Same problem here, tried `nextjs.nodes.server.apply()` seems like not the right way.
> 
> @kane50613 Incidentally, did you get anywhere with that?

modify `buildServerOrigin` function add `vpc` prop then it works

**Comment by kane50613** [comment]
Updated solution in #266

**Comment by danielbush** [comment]
Did one also, took me to just now to test it in my setup.  I think I got my version to push in the subnets, security groups and the permissions.

**Comment by fwang** [comment]
Added support in v0.0.324
