### ISSUE TITLE
Fails to create DNS records with wildcard alias on CloudFlare (Error: Component names must be unique.)

### ISSUE THREAD

**Issue by RyanTheAllmighty** [sst/ion#289]
Currently I have a Nextjs application that I'm deploying and using CloudFlare as a DNS provider:

```ts
        new sst.aws.Nextjs('App', {
            domain: {
                name: "example.com",
                aliases: ["*.example.com"],
                dns: sst.cloudflare.dns(),
            },
        });
```

Doing that, ACM will request 2 validations, one for the root domain and then one for the wildcard, but they will both have the same record name:

```json
[
    {
        "domainName": "example.com",
        "resourceRecordName": "_f43842aab9d472519d2848ded75b8d71.example.com.",
        "resourceRecordType": "CNAME",
        "resourceRecordValue": "_91de14983a25616568229b958b2c1830.mhbtsbpdnt.acm-validations.aws."
    },
    {
        "domainName": "*.example.com",
        "resourceRecordName": "_f43842aab9d472519d2848ded75b8d71.example.com.",
        "resourceRecordType": "CNAME",
        "resourceRecordValue": "_91de14983a25616568229b958b2c1830.mhbtsbpdnt.acm-validations.aws."
    }
]
```

This ends up failing a deploy with the below

> ×  Failed
>   Invalid component name "AppCdnSslCNAMERecordF43842aab9d472519d2848ded75b8d71examplecom". Component names must be unique.

Because the `resourceRecordName` is used as part of the name, it fails due to not being unique.

The same also happens when it tries to create the actual DNS record pointing to the CloudFront distribution:

> ×  Failed
>   Invalid component name "AppCdnCNAMERecordExamplecom". Component names must be unique.

Seems like when it's creating the names for those, it's running through `sanitizeToPascalCase` and then stripping the `*.` so the names end up being the same as seen at https://github.com/sst/ion/blob/dev/pkg/platform/src/components/cloudflare/dns.ts#L70

I'm not sure of the correct fix, but for me I'm currently applying the below changes in my GitHub workflow to get around this issue for now and it works for me by deduplicating the DNS records for validation, and then in the CloudFlare DNS provider, changing the name suffix to explicitly change `*` to `star` which definitely feels a bit icky, but for now works to unblock me:

https://github.com/sst/ion/blob/dev/pkg/platform/src/components/aws/dns-validated-certificate.ts#L56-L71
```diff
function createDnsRecords() {
      return all([dns, certificate.domainValidationOptions]).apply(
        ([dns, options]) =>
-         options.map((option) =>
+         options.filter((option, index, self) =>
+           index === self.findIndex((t) => (
+             t.resourceRecordName === option.resourceRecordName
+           ))
+         ).map((option) =>
            dns.createRecord(
              name,
              {
                type: option.resourceRecordType,
                name: option.resourceRecordName,
                value: option.resourceRecordValue,
              },
              { parent },
            ),
          ),
      );
    }
```

https://github.com/sst/ion/blob/dev/pkg/platform/src/components/cloudflare/dns.ts#L70
```diff
    return output(record).apply((record) => {
-     const nameSuffix = sanitizeToPascalCase(record.name);
+     const nameSuffix = sanitizeToPascalCase(record.name.replaceAll("*", "star"));
      const zoneId = lookupZone();
      const dnsRecord = createRecord();
```

**Comment by fwang** [comment]
@RyanTheAllmighty can you set domain name to `*.example.com` directly?

```ts
        new sst.aws.Nextjs('App', {
            domain: {
                name: "*.example.com",
                dns: sst.cloudflare.dns(),
            },
        });
```

**Comment by RyanTheAllmighty** [comment]
> @RyanTheAllmighty can you set domain name to `*.example.com` directly?
> 
> ```ts
>         new sst.aws.Nextjs('App', {
>             domain: {
>                 name: "*.example.com",
>                 dns: sst.cloudflare.dns(),
>             },
>         });
> ```

@fwang It will work yes as there are no conflicting names/records, but `*.example.com` doesn't cover `example.com` so there's no cert or DNS record generated for the apex domain. If you need me to confirm that I can, just will take some time, but from my OP it wouldn't seem to be an issue

**Comment by fwang** [comment]
ah that makes sense.. lemme take a look

**Comment by ericc59** [comment]
I'm also seeing this on AWS

**Comment by guidefari** [comment]
+1 to facing this on AWS.
Even `sst dev` won't work, throwing the same error.

What I've tried:
- `sst remove` & `sst refresh`
- Manually deleting:
  - DNS records: A, AAAA, CNAME
  - Cloudfront distros
  - S3 buckets

**Comment by danielsharvey** [comment]
@guidefari See my experience and fixes in #927 and #928. It may be relevant and my fixes may work for you.

**Comment by fwang** [comment]
Fixed in this commit https://github.com/sst/ion/commit/257e7e2cbcf22e2bed611e6525fb17ee03cf282f. Fix is in v3.0.79

**Comment by guidefari** [comment]
thanks @danielsharvey @fwang 🫡
I don't remember how I eventually fixed it, but I did😅

**Comment by rayli09** [comment]
anyone care to share how they resolved this?
