### ISSUE TITLE
TTL is missing from sst.dynamodb

### ISSUE THREAD

**Issue by TheKnightCoder** [sst/ion#290]

**Comment by JanStevens** [comment]
You can easily do that with the transform property

```
transform: {
  table: {
    ttl: { attributeName: 'expiresAt', enabled: true },
  },
},
```

**Comment by fwang** [comment]
Thanks @JanStevens!

In v0.0.326, you can set `ttl` as a top level arg for the `Dynamo` component — https://ion.sst.dev/docs/component/aws/dynamo/#ttl
