### ISSUE TITLE
AWS_SESSION_TOKEN renewal

### ISSUE THREAD

**Issue by dmeehan1968** [sst/ion#303]
The following code is used when creating the environment for a NextJs app.

https://github.com/sst/ion/blob/b7f18f1495b6e485705b8eb4643be176f354db8e/pkg/server/server.go#L224-L229

When creating an AWS SDK client for use in a route handler, it picks up the AWS_SESSION_TOKEN which is a temporary credential that appears to have an expiry of 1 hour.  This means that the server can only be 'up' for one hour before the client instance can no longer be used.   Given that the credentials are always being picked up from the environment, there isn't a way to refresh the session token.

I've struggled to find any definitive answer on how to go about token creation.  Are there any recommendations on how to approach this?

**Comment by dmeehan1968** [comment]
The above code is preceeded by `AssumeRole` to get the token, but that requires the function's RoleArn to be passed in the environment (to be able to do renewal in the route handler).  Interestingly, as best as I can see, when the Function is prepared there is no role (the server transform the function props but the role is undefined) and NextJs doesn't expose a 'role' transform.

**Comment by dmeehan1968** [comment]
> the assume role call can probably specify a longer duration - i'll fix

I think this is something that should be handled within the nextjs app.  On a busy site where the function is constantly 'up', the client connection will need refreshing, and endpoint rediscovery is part of that.

I'm not actually clear how the credential provision works, AWS seem to have little guidance, maybe because most Lambda's will cold start often enough for it not to be a problem.

I also wonder if this is actually only a problem on the dev server, as the Go code I presume is part of the proxying.

**Comment by thdxr** [comment]
this issue should not happen in production - aws will always restart the lambda container *before* the token expires<br><br>it may happen in your dev server though

**Comment by thdxr** [comment]
for `sst dev <target>` in 0.0.343 it's been upped to 12 hours
