### ISSUE TITLE
Feat Request - Split NextJS routes in more than one lambda

### ISSUE THREAD

**Issue by dev2xl** [sst/ion#306]
Maybe this is already possible but I couldn't find any reference on the docs.

It would be great to be able to `assign different memory size, and timeouts`, for the different routes on a NextJS app.

If someone has a workaround or knows how to do this, please share. Thanks!

**Comment by fwang** [comment]
Hi @dev2xl, do u mind sharing a bit more about your use case:
- Do u have a specific route that does something compute intensive?
- Does it work if you could set a large memory/cpu/timeout across all your routes?
- Do you see using a large memory/cpu/timeout being a temporary solution, and eventually specific routes need to run on container?

**Comment by NamesMT** [comment]
Nextjs itself (or any current framework I think) doesn't support splitting routes into multiple functions.
One way you can achieve what you want is setting up additional "job" functions, and invoke them from your main function.

**Comment by dev2xl** [comment]
I have managed to do this with open-next config on the v3 version as they stated on their website. Thanks for everything.

**Comment by NamesMT** [comment]
Wait what? @dev2xl
If you have time could you public a repo that uses this?, Or maybe link some related docs?
Super interested in this, but couldn't find the related docs for it.
Have never heard of this native support by Next to split routes to multiple functions.
