### ISSUE TITLE
Unexpected error occurred

### ISSUE THREAD

**Issue by DropeHenrique** [sst/ion#315]
Erro to run  `sst` in windows
![image](https://github.com/sst/ion/assets/71158141/64b489c7-be79-4d72-97f9-1086a457e5e3)

**Comment by jayair** [comment]
Is this with WSL?

**Comment by meza** [comment]
I have this with WSL, Powershell and on mac with brew. 
![image](https://github.com/sst/ion/assets/211977/60b94d81-a3d7-42c2-a1b2-61ce6c8a3b07)
![image](https://github.com/sst/ion/assets/211977/513af074-9270-4b65-93fe-aae87540cae7)

**Comment by jayair** [comment]
Can you try it with `NO_BUN=true`?

https://github.com/sst/ion/issues/142

**Comment by jayair** [comment]
Closing this for now. Feel free to a open a new issue if it pops up.
