### ISSUE TITLE
Trying to link a Cognito User Pool

### ISSUE THREAD

**Issue by thelegendtubaguy** [sst/ion#319]
I'm following the monorepo design such that my folder structure looks like this:
<img width="366" alt="image" src="https://github.com/sst/ion/assets/95944177/a4c3df0d-5f88-418b-ba6d-7ae12f41141e">

I have several different functions in my functions package, each with mostly unique "links" to other resources.  I've defined one like so:
```ts
const connectionFunction = new sst.aws.Function('ConnectionFunction', {
    handler: './packages/functions/src/ApiConnection.handler',
    link: [apiTable, bus, userPool ],
    memory: '128 MB',
    timeout: '10 seconds',
})
```

However when I ran this lambda I was told that "UserPool" was not linked (the resource name on `userPool`).  The `sst-env.d.ts` is mysteriously missing any reference to "UserPool".
```ts
import "sst"
declare module "sst" {
  export interface Resource {
    ApiTable: {
      name: string
      type: "sst.aws.Dynamo"
    }
    EventsTable: {
      name: string
      type: "sst.aws.Dynamo"
    }
  }
}
export {}
```

Do I need to have the same `link` on every function to get this to show up?  I don't really want to give permissions to my user pool to every function if they don't need it.  Thanks!

And thank you for introducing me to Pulumi.  Working with this has been such a dream compared to CDK.

**Comment by thelegendtubaguy** [comment]
Oh my `userPool` is a Pulumi resource, not an SST Ion component.  I'm going to guess that's it :D

**Comment by thelegendtubaguy** [comment]
I have switched to the very newly released `CognitoUserPool` SST component and it still isn't linking.  Maybe I'm just too early to using it?

**Comment by fwang** [comment]
Hey @thelegendtubaguy what r u trying to do w/ the user pool in ConnectionFunction?

**Comment by thelegendtubaguy** [comment]
It'd be nice to access the user pool ID.  The function is specifically doing list users, update user attributes, and add user to groups.

I was able to work around this by specifying permissions on the function and setting the user pool id as an env var for now.

**Comment by fwang** [comment]
Added in v0.0.325.

Now when u link [`CognitoUserPool`](https://ion.sst.dev/docs/component/aws/cognito-user-pool/#links), you can access `Resource.MyUserPool.id`, and the function has `cognito-idp:*` permission on the user pool arn.

Feel free to reopen if this doesn't work for you.

**Comment by thelegendtubaguy** [comment]
Awesome!  Thank you!
