### ISSUE TITLE
Windows binaries not created since version 0.0.195

### ISSUE THREAD

**Issue by meza** [sst/ion#322]
Hi,

I was hoping to be able to use SST@ion with windows as I've seen the installation instructions on the docs. Unfortunately scoop can only grab 0.0.195 because that's the last version that had a windows binary released.

Is that intentional?

**Comment by jayair** [comment]
Yeah WSL only right now. Windows support is on the roadmap though.

I opened an issue to track it: https://github.com/sst/ion/issues/347
