### ISSUE TITLE
Add CLI support for sourcing env from different files

### ISSUE THREAD

**Issue by colemahatmccreary** [sst/ion#350]
Opening this at Dax's request: https://discord.com/channels/983865673656705025/1177071497974648952/1234854834696618024

The CLI should support automatically sourcing environment variables from a stage-specific file (e.g. .env.$stage) if available

It should also provide an override argument allowing you to specify a path to any arbitrary .env file

**Comment by thdxr** [comment]
oh turns out we already support `.env.<stage>`

**Comment by colemahatmccreary** [comment]
So to override this behavior should i just use dotenv? i could explain my use case more, but basically i need multiple stages (other than prod and dev) to share the same set env variables (e.g. every feature branch deploys to ```--stage=<branchname>``` but should all source from ```.env.feature```
