### ISSUE TITLE
Cloudflare: Unable to properly delete a resource after manually deleting it

### ISSUE THREAD

**Issue by ruchernchong** [sst/ion#359]
Received this error: 

> |  Error       MyDatabase sst:cloudflare:D1 → MyDatabaseDatabase cloudflare:index:D1Database failed to delete D1 database: error from makeRequest: The database 365cdad9-fdaf-40ea-b6fd-ba48abed39ec could not be found (7404)
|  Deleted     Test sst:cloudflare:D1 → TestDatabase cloudflare:index:D1Database

> ×  Failed
   MyDatabase sst:cloudflare:D1 → MyDatabaseDatabase cloudflare:index:D1Database
   failed to delete D1 database: error from makeRequest: The database 365cdad9-fdaf-40ea-b6fd-ba48abed39ec could not be found (7404)

This happened after accidental deleting of a database directly on Cloudflare. This is a dev database.

**Comment by jayair** [comment]
Should also add that `sst refresh` didn't work.

**Comment by ruchernchong** [comment]
> Should also add that `sst refresh` didn't work.

Right. Missing this information.

However, @thdxr suggested me to use `sst state edit` and manually delete that lingering resource. I tried it and it worked.

I will be closing this now.
