### ISSUE TITLE
Cannot reset stack

### ISSUE THREAD

**Issue by teemuvayrynen** [sst/ion#363]
I had an issue with configuration so I needed to delete items manually from my AWS account. After that the sst deloyment broke and I cannot find a way to reset the state. Basically I would need to do hard reset for everything but sst always gets the previous configuration. Also, the sst remove is not working.

**Comment by urosbelov** [comment]
I had a same error first time when I tried sst ion. I deleted main S3 Bucket and I didn't know how to completely reset sst ion...

My temporary fix:
1. Open AWS CloudTrail Console
2. Navigate to Event History
3. I found name of sst ion autogenerated S3 Bucket that I deleted
4. Create new S3 Bucket with same name

**Comment by thdxr** [comment]
calling `sst refresh` should help if you did things in the aws console outside of sst (please do not do this)

**Comment by jayair** [comment]
Closing this for now.
