### ISSUE TITLE
How to handle AWS cache policy limit

### ISSUE THREAD

**Issue by nserbass** [sst/ion#368]
**Use case**: My team is using SST to deploy a Nextjs application in multiple stage environments for testing feeatures before deploy to production (another env  deployed by sst).

**Problem:** Due to aws cloudfront cache policy limit, we can't create too many environments because we reach the limit quickly (20)

I've followed your documentation about transform function. I've tried several implementations but always creates a new one and throws errors with missing defaultCacheBehavior parameters:

```typescript
new sst.aws.Nextjs("MyWeb", {
  environment,
  transform: {
    cdn: {
      defaultCacheBehavior: {
        cachePolicyId: 'f99c40f2-50bf-4215-8023-125e7a46fb0e'
      }
    }
  },
});
```

```typescript
new sst.aws.Nextjs("MyWeb", {
  environment,
  transform: {
    cdn: (cdnArgs) => {
      cdnArgs.defaultCacheBehavior = {
        cachePolicyId: 'f99c40f2-50bf-4215-8023-125e7a46fb0e'
      }
    }
  },
});
```

```typescript
// it doesn't throw errors but creates a new cache policy as well
new sst.aws.Nextjs("MyWeb", {
  environment,
  domain: customDomain,
  transform: {
    cdn: (args) => ({
      ...args,
      defaultCacheBehavior: {
        ...args.defaultCacheBehavior,
        cachePolicyId: 'f99c40f2-50bf-4215-8023-125e7a46fb0e'
      }
    })
  }
});
```

Any ideas? 

Thank you!

**Comment by eschaefer** [comment]
Just chiming in to +1 this since we have a similar limit for our team. I imagine this would be a common use-case for teams that work in big orgs with arbitrary limits on cache policies.

**Comment by jayair** [comment]
Yeah this sounds like something we should try and handle internally. Let me ask the team.

**Comment by cgcompassion** [comment]
Note: In SST 2 this was possible as per these docs: https://docs.sst.dev/constructs/NextjsSite#reusing-cloudfront-cache-policies

**Comment by iliaamiri** [comment]
This was [addressed and solved](https://github.com/sst/sst/issues/899) by @fwang before in SST 2 and I've never had an issue with it. And, it's a blocker for my case due to AWS' hard limit of 20 cache policies. 

Will really appreciate an update on this :heart: :pray:

**Comment by josejames** [comment]
Is there any new on this? I'm still using SST 2 for this, and I would like to move on to ion

**Comment by iliaamiri** [comment]
@josejames Same here. The PR is there. They just need to be reviewed by the SST team.

**Comment by jayair** [comment]
Let me bump this up in priority internally.

**Comment by iliaamiri** [comment]
> Let me bump this up in priority internally.

Thanks @jayair. means a lot 🙏

**Comment by iliaamiri** [comment]
@nserbass @josejames @cgcompassion @jschuur @eschaefer 

They added it! :partying_face: 

https://github.com/sst/ion/pull/593#issuecomment-2230198589

**Comment by nserbass** [comment]
> @nserbass @josejames @cgcompassion @jschuur @eschaefer
> 
> They added it! 🥳
> 
> [#593 (comment)](https://github.com/sst/ion/pull/593#issuecomment-2230198589)

that's wonderful! I'm going to use it right now :D

**Comment by jschuur** [comment]
So, just to confirm the approach to use this new cachePolicy setting...

You do one deploy without the setting (in the unlikely event you don't already have a cache policy), then go to CloudFront -> Policies -> Cache in the AWS console, copy the ID and add a cachePolicy setting in `sst.config.ts` to load it from an environment variable or Secret?

**Comment by cgcompassion** [comment]
@jschuur This is for cases where you want to setup one cache policy to be used by all your apps, so you would likely create it manually in the console, or else set up a separate sst app just to maintain your shared resources... You probably wouldn't want to have all your apps relying on each other, or else spinning down one stack would break the others. Then you could either maintain the ID in config, or just hardcode it (it's not a secret).

**Comment by jschuur** [comment]
> @jschuur This is for cases where you want to setup one cache policy to be used by all your apps, so you would likely create it manually in the console, or else set up a separate sst app just to maintain your shared resources... 

I understand the use case. Just asking what the best practice is to get the initial value. Good point about  how you can just set one up manually in the console,  that hadn't occurred to me.

> You probably wouldn't want to have all your apps relying on each other, or else spinning down one stack would break the others. Then you could either maintain the ID in config, or just hardcode it (it's not a secret).

That's actually also a great point and another reason to create your own.

**Comment by jayair** [comment]
Closing for now

**Comment by jayair** [comment]
Docs for Nextjs: https://ion.sst.dev/docs/component/aws/nextjs/#cachepolicy

The other frontends have one too.
