### ISSUE TITLE
Add a linkable Parameter component

### ISSUE THREAD

**Issue by bchilcott** [sst/ion#379]
There should be a parameter component, similar to the old SST v2 `Parameter`, for linking non-secret configuration instead of having to use `environment`. Could look something like:

```ts
const someConfig = new sst.Parameter("SomeConfig", "some-non-secret-value");
// or...
const someConfig = new sst.Parameter("SomeConfig", {
  value: "some-non-secret-value"
});
 
const myFn = new sst.aws.Function("MyFn", {
  handler: "src/functions/MyFn.handler",
  link: [someConfig]
});
```

**Comment by bchilcott** [comment]
> you can actually use `new sst.Secret("SomeConfig", "myvalue")` - does that work for you?

Ah yes that works - thanks. You feel free to close this but I suppose it would be nice if we could link more complex types? Arrays, etc. Definitely not a priority though, this works perfectly.

**Comment by jackblanc** [comment]
Does Secret actually store anything if you set a default value? I'm looking into using this to make D1 HTTP work, but it feels a little hacky. I want to avoid duplicating the value - if Secret doesn't actually store the default, probably fine?
