### ISSUE TITLE
Domain across stages

### ISSUE THREAD

**Issue by felipemotarocha** [sst/ion#391]
How can I set different domains depending on the stage of my app? I want to set a different domain to prod and dev environment.

I didn't see anything on the docs related to that. I know that in SST we could do something like this:

```ts
new NextjsSite(stack, "site", {
  customDomain:
    stack.stage === "prod" ? "my-app.com" : `${stack.stage}.my-app.com`,
});
```

Can someone help me with this please?

**Comment by zohaibakber** [comment]
```ts
 domain: $app.stage === "prod" ? `app.${domain}` : `stage.${domain}`,
 ```
> https://ion.sst.dev/docs/reference/global/

**Comment by thdxr** [comment]
^ yep can see all globals here: [https://ion.sst.dev/docs/reference/global/#\_top](https://ion.sst.dev/docs/reference/global/#\_top)

**Comment by felipemotarocha** [comment]
Thanks so much guys!
