### ISSUE TITLE
AWS Astro example doesn't work

### ISSUE THREAD

**Issue by garysassano** [sst/ion#406]
When clicking the "Upload" button, it opens the "Save as" dialog window and then saves the file to my local instead of uploading it to S3.

**Comment by zohaibakber** [comment]
https://ion.sst.dev/docs/start/aws/astro/#3-create-an-upload-form

> window.location.href = image.url.split("?")[0] || "/";

this line is saving file in local machine example is correct and works fine maybe you are doing something wrong?

**Comment by garysassano** [comment]
You're saying the example sets up an unused S3 bucket and has an "Upload" button that doesn't actually upload to S3. Instead, it takes a file from the user's computer and saves it somewhere else, still on their computer? This seems illogical and confusing.

**Comment by zohaibakber** [comment]
> You're saying the example sets up an unused S3 bucket and has an "Upload" button that doesn't actually upload to S3. Instead, it takes a file from the user's computer and saves it somewhere else, still on their computer? This seems illogical and confusing.

```ts
       const image = await fetch(form!.action, {
          body: file,
          method: "PUT",
          headers: {
            "Content-Type": file.type,
            "Content-Disposition": `attachment; filename="${file.name}"`,
          },
        });

        window.location.href = image.url.split("?")[0] || "/";
 ```
Sunshine example is correct the reason its saves file to your computer is because after doing fetch call it doesn't matter whether response is 4xx or 5xx, last line will always run thats what saves file to your pc, try checking what you are doing wrong my guess is your are not setting headers correctly or something else... check network tab what happens when you try to upload, you can remove this line so file is not saved locally.
> window.location.href = image.url.split("?")[0] || "/";

**Comment by jayair** [comment]
Yeah try commenting out the line @zohaibakber said and see what's going on

**Comment by garysassano** [comment]
Commenting the line works indeed, but I'm not sure I understand why that's present.

**Comment by jayair** [comment]
It shows that the file was uploaded and that you can download it back.

**Comment by garysassano** [comment]
The "Upload" button's current behavior of prompting to save the file locally is counterintuitive. Users expect a confirmation message ("File upload successful" or an error message) after clicking "Upload".

You could add a dropdown menu listing files in the bucket and a separate "Download" button would provide a clear and intuitive way to access uploaded files.

**Comment by garysassano** [comment]
The "Upload" button's current behavior of prompting to save the file locally is counterintuitive. I would normally expect a popup ("File upload successful" or an error message) after clicking "Upload".

You could add a dropdown menu listing files in the bucket and a separate "Download" button would provide a clear and intuitive way to access uploaded files.

**Comment by jayair** [comment]
Yeah I might change this at some point. For now it's a very simple demo that shows that a file is getting uploaded correctly.

**Comment by iamandrewluca** [comment]
> You're saying the example sets up an unused S3 bucket and has an "Upload" button that doesn't actually upload to S3.

It uploads to S3, the tells your browser to open that file from S3, but the browser decides to download the file from S3.
