### ISSUE TITLE
Docs: CLI target flag

### ISSUE THREAD

**Issue by jayair** [sst/ion#420]
Added to `remove`, `refresh`, and `deploy`.

**Comment by creaux** [comment]
Hello @jayair how is this flag actually working.

Assuming following config

```
new sst.aws.Astro('FirstAstro', {...});
new sst.aws.Astro('SecondAstro, {...});
```

Is then intended to use sst cli like `sst deploy --target SecondAstro`? if not how is expected target to work?

**Comment by jayair** [comment]
It takes the URN, you can either get it from your local state file or in the Console:

<img width="1360" alt="Screenshot 2024-07-04 at 7 34 14 PM" src="https://github.com/sst/ion/assets/53023/83c72a9a-2b4e-4e19-9f0e-63431d6ed4ee">

**Comment by nurulhudaapon** [comment]
@jayair For Next.js app I copied the URN of the parent app, but when I execute `sst deploy --target=urn:pulumi:staging::voyage::sst:aws:Nextjs::WebAdmin` it still deploys all app that I've in sst.config.ts.

**Comment by jayair** [comment]
Yeah let me ask the team about it.

Added https://ion.sst.dev/docs/reference/cli/#deploy
