### ISSUE TITLE
EC2 Instance support?

### ISSUE THREAD

**Issue by dev2xl** [sst/ion#452]
I don't see it on the docs. It would be great to be able to easily setup an EC2 instance and install, and upload some scripts, assigning dedicated IP using ion. Idk if this is out of the scope of the project. Thanks

**Comment by jayair** [comment]
Have you tried https://ion.sst.dev/docs/component/aws/cluster/?

**Comment by dev2xl** [comment]
That's for ECS and Fargate that is more expensive than EC2

**Comment by agamm** [comment]
> If you want to use EC2, for now you might have to use the AWS provider directly.
> 
> We might revisit this at some point!

@jayair I'd love an EC2 feature. Is there a guide in the meantime on how to use the AWS provider directly?
