### ISSUE TITLE
Permissions property doesn't work on Remix component

### ISSUE THREAD

**Issue by pablote** [sst/ion#457]
I've added a `permissions` property to a Remix component, like this:

<img width="913" alt="image" src="https://github.com/sst/ion/assets/2463995/b84ca24c-65ba-4e00-9e59-d21942b6b713">

When I deploy this I don't see these permissions being reflected on the lambda's execution role, and because of it trying to use this resources I get a AccessDeniedException from AWS. I've tried bringing the stage down and recreating, but no luck.

Thanks

**Comment by jayair** [comment]
Can you share a screenshot of the function that you were checking on in the AWS Console?

**Comment by pablote** [comment]
This is how it looks on lambda:

<img width="1534" alt="Screenshot 2024-05-24 at 8 54 03 AM" src="https://github.com/sst/ion/assets/2463995/3d72d943-1f4e-4ece-acf6-fb69e22d6a15">

And if I go to IAM:

<img width="1382" alt="image" src="https://github.com/sst/ion/assets/2463995/4d3d0e71-43a5-4227-9e16-50d4335d1bf3">

Btw, I've tried a few things, like adding more permissions, this is an example straight from the docs, but it doesn't seem to make any change:

<img width="546" alt="Screenshot 2024-05-24 at 8 58 34 AM" src="https://github.com/sst/ion/assets/2463995/d1de1dd2-219d-4f42-bbc7-46a78bbe371d">

**Comment by pablote** [comment]
I've managed to get this working. Let me explain what I did because there seem to be some underlying issues with SST.

1) I created a new, clean, Remix app and deployed it with the `permissions` prop setup. Permissions correctly showed up on the Lambda, so the problem must be with my application.
2) I tried sst removing and sst deploying the app again, the problem is this there, permissions don't show up on the Lambda.
3) I sst remove the app, and go looking into AWS. This is the first time I notice sst is not actually removing the app. The lambda, cloudfront distribution, s3 bucket, iam roles, are all still there. Even if try to sst remove it again I get a "already removed" message. If I deploy and remove, it never fails, but it never deletes stuff on AWS.
4) I start to delete stuff manually on AWS, and delete all traces of SST in the project. Sst init again and deploy from scratch. This turned out to be a little more complicated than expected, it'd would keep trying to use a bucket I deleted and bail out because it couldn't find it. Looking for the error in ion code I found that there were some configs in ssm pointing to this bucket. Deleted them all.
5) Deployed the app again and now it's fully working :D.

I understand that poking into AWS generated stuff is not the expected behavior, but at the same time, the tooling doesn't seem to recover from weird cases like the one I fell into.

**Comment by jayair** [comment]
Your app should've been removed on `sst remove`. Unless you are setting the `retain` flag: https://ion.sst.dev/docs/reference/config/#removal

What are you using?

**Comment by pablote** [comment]
`retain` was not being set, and from what I can see it doesn't keep the lambdas unless `retain-all` is used.. anyway, it's working fine now, and `sst remove` correctly deletes everything, it just didn't do it before, I don't know why

**Comment by jayair** [comment]
Weird. Closing this for now.
