### ISSUE TITLE
Discussion: How to use Ion in CI/CD 

### ISSUE THREAD

**Issue by kxseilerjo** [sst/ion#464]
So, I don't know whether this is known or even intentional, but with an Ion version of SST you can't do
> npx sst deploy
in CI/CD environments anymore, or rather you can't use SST over Npx anywhere at all anymore.

So are you supposed to just install the new SST CLI in CI/CD environments as well?

**Comment by thdxr** [comment]
yeah currently people are just running the curl command to install sst in their ci environments<br><br>we will be releasing CI solutions soon
