### ISSUE TITLE
Function timeout is not applying

### ISSUE THREAD

**Issue by thelegendtubaguy** [sst/ion#466]
I have a function that I have defined like so:
```ts
new sst.aws.Function('MyFunction', {
	environment: {
		...
	},
	handler: './apps/functions/src/MyFunction.handler',
	memory: '128 MB',
	timeout: '1 minute',
	live: false,
})
```

It deploys the function correctly with all my env var stuff set, but it does not set the timeout.  I have tried `60 seconds`, I have tried `1 minute`, etc.  I don't think it has anything to do with the service that is triggering the function (eventbridge in this case) because when looking at the function's configuration in the console it shows this:
<img width="278" alt="image" src="https://github.com/sst/ion/assets/95944177/3f50707c-a18c-4d94-b04c-869befb230bf">

**Comment by thelegendtubaguy** [comment]
If I go into the console and change it to a different value than what I have set in code, SST/Pulumi does not update it back to the value I have set in my code.  Seems like this field is not sync'd with SST.

**Comment by jayair** [comment]
Is this in `dev` or `deploy`?

**Comment by thelegendtubaguy** [comment]
Dev, but also the case if I set live to false.

**Comment by jayair** [comment]
If you deploy it, does it set it?

**Comment by thelegendtubaguy** [comment]
Just tested deploying it, no it does not.  It's still set at 10 seconds.

**Comment by jayair** [comment]
If that's the case then run a `sst refresh` first and then do a deploy. More about it here: https://ion.sst.dev/docs/providers/#how-state-works

**Comment by thelegendtubaguy** [comment]
Oh interesting.  That's a major shift from how Terraform works.  Terraform runs a refresh/plan prior to apply so didn't make sense to me. 

Regardless of that this still does not work.  I just did a refresh then deploy and this function on AWS has a timeout of 10 seconds.  Here's its definition:
```ts
new sst.aws.Cron('CheckFailedSubscriptionsCron', {
	schedule: 'rate(1 hour)',
	job: {
		environment: {
			CONDUIT_INDEX: '0',
			APP: $app.name,
			STAGE: $app.stage,
			BUS_ARN: bus.arn,
			BUS: bus.name,
		},
		handler: './apps/functions/src/CheckFailedSubscriptions.handler',
		link: [clientIdSecret, clientSecretSecret, table, apiTable],
		live: false,
		permissions: [
			{
				actions: ['ssm:Get*', 'ssm:PutParameter'],
				resources: ['*'],
			},
		],
		timeout: '2 minutes',
	},
})
```

If I remove the `live: false` it still is set at 10 seconds.  I seemingly can never get it to respect the timeout setting.

**Comment by jayair** [comment]
So if you edit the value in the console and your local state has a different value, a deploy won't update it.

You need to make sure that your state locally matches what you have set in the console.

For the plan part, we have it on the roadmap.

**Comment by thelegendtubaguy** [comment]
Ah okay, another thing that works different.  I guess I didn't realize there wasn't state drift resolution... that seems super odd having come from the Terraform world.

With that in mind, I created a new function.  I touched nothing in the console.  Its timeout was set at 10 seconds.  I added `timeout: "60 seconds"` while running `sst dev`, it noticed the file change and tried to deploy but ultimately changed nothing.

I then tried doing an `sst deploy` and still the function's timeout is set at `10 seconds`.

**Comment by jayair** [comment]
I see the issue might be specific to how Live handles functions. It isn't deploying your function but a proxy with different set of props. So flipping back and forth between dev and deploy might not be updating it.

**Comment by jayair** [comment]
@fwang let's take a look?

**Comment by fwang** [comment]
@thelegendtubaguy hmm.. that's really weird.

I just tried deploying a new app with the Cron job snippet u shared above. And `timeout` is set to 2 minutes in the console.
<img width="1120" alt="Screen Shot 2024-07-30 at 3 53 39 PM" src="https://github.com/user-attachments/assets/fad5e669-654a-48c9-a3e4-f072aa9a2b92">

Maybe try a new SST app with just a single function?

**Comment by thelegendtubaguy** [comment]
Ah, I set a default timeout to 10 seconds.  I suppose we can close this... but is there a way to set defaults and then allow us to overwrite that default per function?

For example, here's what I had:
```
async run() {
		$transform(sst.aws.Function, (args, opts) => {
			args.logging = { retention: '1 month' }
			args.memory = '128 MB'
			args.runtime = 'nodejs20.x'
			args.timeout = '10 seconds'
		})
		await import('./infra')
	},
	```

**Comment by jayair** [comment]
Right now there isn't. But it's something we should look into.
