### ISSUE TITLE
Reference externally managed infrastructure

### ISSUE THREAD

**Issue by jaxxstorm** [sst/ion#472]
I have a bunch of infrastructure I manage with Pulumi already, and I'd like to be able to leverage it. For example, I want to be able to reference a Pulumi VPC with a stack reference.

Ideally I'd be able to leverage Pulumi state as well, so I can use SST to create exports I can reference if required

**Comment by jayair** [comment]
This is for importing existing resources in your SST app?

**Comment by jaxxstorm** [comment]
yes, or referencing their outputs

**Comment by aeons** [comment]
We have a similar setup, where all our infrastructure is in pulumi, but we would like to add a single app using ion, and reference the existing pulumi stacks.

**Comment by jayair** [comment]
Yeah we need to figure out a good pattern for referencing existing resources without having to import them.

**Comment by thdxr** [comment]
managing external infra created by pulumi using a stack reference isn't likely going to be possible - our state system works quite differently and will continue to diverge

you should treat it like external infra created manually - use `aws.foo.getThingOutput(…)` methods to grab references to what you're looking for

**Comment by thdxr** [comment]
going to close for now
