### ISSUE TITLE
the Pinecone Pulumi provider installs the wrong package. 

### ISSUE THREAD

**Issue by eshrager** [sst/ion#473]
i think it needs to install "pinecone-database" not "pinecone" which seems to be a different package entirely. Ii'm using SST Ion 0.0.390

**Comment by jayair** [comment]
Can you share the steps to recreate this?

**Comment by eshrager** [comment]
go here: https://www.pulumi.com/registry/packages/pinecone/installation-configuration/
enter "npm install @pinecone-database/pulumi" into terminal inside my project directory
enter "sst add pinecone"
enter "sst refresh"

the provider will not install. if you check the node_modules for "pinecone" you will see it is the wrong pinecone package, it should be pinecone-database

the sst ion documentation says the name of the provider is the same as the name of the Pulumi registry but for Pinecone, it is not "Pinecone".

**Comment by thdxr** [comment]
does doing `sst add @pinecone-database/pulumi` work?

**Comment by thdxr** [comment]
i confirmed that worked - closing this issue for now
