### ISSUE TITLE
Allow to disable cloudwatch logs when configuring lambdas

### ISSUE THREAD

**Issue by yyaskriloff** [sst/ion#479]
I'm currently working on a project that's using axiom for logging. (They say to disable cloud watch logs when trying there were some errors I assume it's because of this but either way it doesn't matter). Therefore making cloud watch logs redundant. I could set retention period to 1 day but it would be nice to be able do disable them all together.

**Comment by yyaskriloff** [comment]
Something like 

```ts
        const AdsConcater = new sst.aws.Function('AdsConcater', {
            handler: 'packages/functions/src/adsConcater.handler',
            layers: [axiomLoggingLayer],
            logging: false
        })

```

**Comment by fwang** [comment]
In the next release, u can set `logging` to `false` to disable logs.
