### ISSUE TITLE
Add dead letter queue for SQS.

### ISSUE THREAD

**Issue by yyaskriloff** [sst/ion#480]
Adding the ability to add DLQ for SQS, SNS and I believe lambda.

```ts
const dlq = new sst.aws.Queue("DeadLetterQueue", {
  isDLQ: true // or maybe not having to set it
});
 
new sst.aws.Queue("MyQueue", {
  fifo: true,
  deadLetterQueue: dlq
});
 
new sst.aws.SnsTopic("MyTopic", {
  deadLetterQueue: dlq
});
 
```

or maybe even not having to create a new queue

```ts
new sst.aws.Queue("MyQueue", {
  fifo: true,
  deadLetterQueue: true
});
```

**Comment by beeirl** [comment]
@fwang  are dlq a thing in the current version of ion? if not, are there any workarounds?

**Comment by beeirl** [comment]
@fwang  are dlq a thing in the current version of ion? or is a custom component the only way to go about this right now?

**Comment by brunocleite** [comment]
Take a look at this PR, it shows how to add a DLQ
https://github.com/sst/ion/pull/564/files

**Comment by yyaskriloff** [comment]
> @yyaskriloff @beeirl Take a look at this PR, it adds Dead Letter Queue support
> 
> https://github.com/sst/ion/pull/565

Thank you.
