### ISSUE TITLE
Cannot link dynamic pulumi resources

### ISSUE THREAD

**Issue by spiritledsoftware** [sst/ion#486]
I am trying to link custom dynamic resources from pulumi. I have used the following code to try to link my database URLs from Neon:
```ts
sst.Link.makeLinkable(NeonBranch, function () {
      return {
        properties: {
          readOnlyUrl: this.readOnlyUrl,
          readWriteUrl: this.readWriteUrl,
        },
      };
 });
```

But the only thing to show in my types.generated.ts file is the following:
```ts
NeonBranch: {
    type: "pulumi-nodejs.dynamic/theaistudybible.NeonBranch"
}
```

I have followed all rules for adding outputs for dynamic resources outlined here:
https://www.pulumi.com/docs/concepts/resources/dynamic-providers/#dynamic-resource-outputs

**Comment by spiritledsoftware** [comment]
> Commenting because I ran into this recently - the pulumi docs aren't entirely correct (see [this issue](https://github.com/pulumi/docs/issues/11639#issuecomment-2105003085)), you're supposed to prefix the property declarations in the dynamic resource class with `declare`

This did fix the problem! Thank you

**Comment by jayair** [comment]
Can this be closed?

**Comment by spiritledsoftware** [comment]
Yes, issue is filed with pulumi and my code is working now, thanks!
