### ISSUE TITLE
@sst-provider/planetscale config is ignored

### ISSUE THREAD

**Issue by beeirl** [sst/ion#487]
getting this error when passing serviceToken + serviceTokenName in to the provider config. works fine if I use env vars.

``` 
'@sst-provider/planetscale': {
  serviceToken: '###',
  serviceTokenName: '###',
}
```

```
|  Error       DatabasePassword planetscale:index:Password Missing PlanetScale credentials.: You must set either of:
- `PLANETSCALE_ACCESS_TOKEN`
- `PLANETSCALE_SERVICE_TOKEN_NAME` and `PLANETSCALE_SERVICE_TOKEN`
```

**Comment by thdxr** [comment]
if you use latest sst try just doing `sst add planetscale` and configuring it in the `planetscale` block

**Comment by thdxr** [comment]
this seems to be working for me so closing the issue - feel free to reopen

**Comment by itzcull** [comment]
@thdxr, I've downloaded the latest cli, tried running `sst add planetscale`, not getting any indication it's available as a provider
