### ISSUE TITLE
CLI and console.sst.dev/local have no console.log output

### ISSUE THREAD

**Issue by atjeff** [sst/ion#495]
Steps to reproduce:

1. Clone https://github.com/sst/ion/tree/dev/examples/cloudflare-worker
2. Add CLOUDFLARE_API_TOKEN in .env
3. sst init
4. sst dev
5. Add a console log anywhere (first line of fetch to log req perhaps?)
6. Visit or curl generated url 
7. No logs in cli or sst console (sst console /local route just pulses)

There are logs in the cloudflare UI, I just expected to see them from SST somewhere. Is this supported? I did my best to follow the tutorial at https://ion.sst.dev/docs/start/cloudflare/worker/

**Comment by jayair** [comment]
Hmm that is weird. It used to work. We'll take a look.

**Comment by atjeff** [comment]
I should note that I store my state in R2, AWS isn't involved at all. Let me know what files / console data are sensitive and I can send through discord if needed!

**Comment by brapifra** [comment]
Same here. Not sure if it's related to the fact that changes don't get redeployed (using v0.0.393)

**Comment by thdxr** [comment]
this sounds like a bug

**Comment by atjeff** [comment]
Let me know if I sending you my local files is helpful

**Comment by thdxr** [comment]
should be fixed in v0.0.406
