### ISSUE TITLE
`sst deploy` not authenticating with Cloudflare properly

### ISSUE THREAD

**Issue by itzcull** [sst/ion#498]
Version 0.0.398 of ion CLI

I'm using the 'Global API Key' for my Cloudflare account, I'm not able to deploy at all

Trying to set KV values during `sst deploy` step

![Screenshot 2024-05-31 at 10 57 40 PM](https://uploads.linear.app/a959060b-9262-4398-9650-16bf10f1450e/4849dc94-fce9-4dc6-a044-585a66c5b2eb/ba4c8b58-078a-4504-82a5-36e08e5ae4ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5NTkwNjBiLTkyNjItNDM5OC05NjUwLTE2YmYxMGYxNDUwZS80ODQ5ZGM5NC1mY2U5LTRkYzYtYTA0NC01ODVhNjZjNWIyZWIvYmE0YzhiNTgtMDc4YS00NTA0LTgyYTUtMzZlMDhlNWFlNGNlIiwiaWF0IjoxNzE3NDQ2Nzg2LCJleHAiOjMzMjg4MDA2Nzg2fQ.UnBZuonl_thTqggMO7pek91Q5HHVach0uJY0E8FhHpk "=602x")

![Screenshot 2024-05-31 at 11 11 34 PM](https://uploads.linear.app/a959060b-9262-4398-9650-16bf10f1450e/05d3450a-4a9f-4b79-8191-9ae053e2647d/d294cbb8-84eb-4df5-aece-54b95f7002ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5NTkwNjBiLTkyNjItNDM5OC05NjUwLTE2YmYxMGYxNDUwZS8wNWQzNDUwYS00YTlmLTRiNzktODE5MS05YWUwNTNlMjY0N2QvZDI5NGNiYjgtODRlYi00ZGY1LWFlY2UtNTRiOTVmNzAwMmVkIiwiaWF0IjoxNzE3NDQ2Nzg2LCJleHAiOjMzMjg4MDA2Nzg2fQ.tQPiRFCmezrcRUK3tIr9KJmp7GhVGzGL_1OkDrHL7-g "=882x")

The Config

![Screenshot 2024-05-31 at 11 00 15 PM](https://uploads.linear.app/a959060b-9262-4398-9650-16bf10f1450e/371da952-98d5-40c6-9510-e3913f898086/e528bc59-01f0-48de-9dc6-9cb4c3547db7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5NTkwNjBiLTkyNjItNDM5OC05NjUwLTE2YmYxMGYxNDUwZS8zNzFkYTk1Mi05OGQ1LTQwYzYtOTUxMC1lMzkxM2Y4OTgwODYvZTUyOGJjNTktMDFmMC00OGRlLTlkYzYtOWNiNGMzNTQ3ZGI3IiwiaWF0IjoxNzE3NDQ2Nzg2LCJleHAiOjMzMjg4MDA2Nzg2fQ.uKDb4vt1YGLplr4w_Q6kHGp2c4CapzIDdw2jSxSWwYc "=413x")

**Comment by jayair** [comment]
Does setting it in the environment not work? https://ion.sst.dev/docs/start/cloudflare/hono/#set-the-cloudflare-api-token

**Comment by itzcull** [comment]
Removing the provider config value for `apiKey` and just relying on environment variable produces this
![image](https://github.com/sst/ion/assets/49985801/3c55786b-e67e-4230-8bef-301a77863213)

**Comment by itzcull** [comment]
I tried removing explicit configuration, still the same issue as outlined in issue description

![image](https://github.com/sst/ion/assets/49985801/030f43a9-a4dd-45e6-8fc6-fd59525a381c)

**Comment by itzcull** [comment]
`sst deploy` was able to create a KV namespace, but then the rest of the calls failed.

I'm seeing similar API call flake in #ion Discord channel
https://discord.com/channels/983865673656705025/1177071497974648952/1244473373992681572

**Comment by thdxr** [comment]
is there a reason you cannot use the newer api token system? i think we might have implemented some things that need it

**Comment by itzcull** [comment]
What's new and what's not? I've tried both explicitly defining them in the provider object, and just using the environment variables. Can you link the documentation that explains it?

**Comment by itzcull** [comment]
As per https://ion.sst.dev/docs/start/cloudflare/hono/#set-the-cloudflare-api-token

I've set the required cloudflare environment variables in the `.env` file at the root of my repo, the same level that `sst.config.ts` is located

**Comment by itzcull** [comment]
It'd be good to have documentation on what permissions SST needs from Cloudflare, so I don't have to use my account's global api key.

**Comment by itzcull** [comment]
Thanks Dax, this will help heaps. I'll let you know if it works for me and we can take it from there.

I've seen others ask about what perms are needed for Cloudflare, maybe you should share in Discord if you haven't already.

**Comment by itzcull** [comment]
Running `sst deploy` with those exact token permissions yields the same thing....
![image](https://github.com/sst/ion/assets/49985801/cba4b224-a1d1-46a9-b0c8-e4f61d61fb9e)

**Comment by itzcull** [comment]
https://github.com/sst/ion/blob/prodution/pkg/platform/src/components/cloudflare/worker.ts

I've been looking here trying to figure out what might be needed.

**Comment by itzcull** [comment]
Turns out the keys for my PlanetScale database's credentials were wrong, it happened to be the 15th and 16th position in the plainTextBindings passed to Pulumni. 
![image](https://github.com/sst/ion/assets/49985801/fd6529a2-a66d-4646-8bdd-1c0e5652a18c)

Closing this, thanks for you time.
