### ISSUE TITLE
sst.aws.Router - Request invalidation feature as an option

### ISSUE THREAD

**Issue by ruchernchong** [sst/ion#501]
Invalidation right now are limited to the various JS frameworks like Next.js, Astro, Remix, etc... 

It would be great if we could also have an CloudFront invalidation option for the `sst.aws.Router` as well.

**Comment by thdxr** [comment]
@frank maybe we expose this?

**Comment by ruchernchong** [comment]
@thdxr @fwang it has been awhile. Just checking in to see if this is a good suggestion and will be implemented down the road?

**Comment by fwang** [comment]
@ruchernchong In the next release, u can pass in `invalidation: true` or an object to customize the behavior.
