### ISSUE TITLE
Expose stack outputs to sst shell

### ISSUE THREAD

**Issue by chrisandrewcl** [sst/ion#512]
Currently, it seems only linked resources are injected in the env when running `sst shell` but stack outputs are also very useful in this context.

Is there any supported way to access them when running scripts?

\* I am currently working around it by using a dummy linkable component that exports the stack outputs in its link properties, but it would be nice to have it baked in ion.

**Comment by jayair** [comment]
So any resource gets adding to the shell. It doesn't need to be linked but we have a feature coming soon that'll let you create a resource out of any output and that'll be exposed in the `sst shell` as well.

**Comment by chrisandrewcl** [comment]
The upcoming feature you mentioned sounds like it will do the trick!

\* Also, what I meant to say was "only link**able** resources are currenlty added to the env" 🤦

**Comment by thdxr** [comment]
this is released but not documented yet - you can do

```
new sst.Resource("MyResource", { any: "thing", foo: other.thing } )
```

and it will show up in `sst shell`

**Comment by thdxr** [comment]
it's linkable too
