### ISSUE TITLE
Invalid Component Name when using @pulumi/awsx

### ISSUE THREAD

**Issue by Jhinger** [sst/ion#519]
Trying to create a VPC instance using `@pulumi/awsx` and running into an error during the creation process:

```
  Created     Vpc awsx:ec2:Vpc → Vpc-public-1 aws:ec2:Route (1.2s)
|  Error        Invalid component name "Vpc". Component names must be unique.

×  Failed
   Invalid component name "Vpc". Component names must be unique.
```

This is similar to issue #250 which currently has a PR open #299

**Comment by athammer** [comment]
Have this issue as well, seems to have been reported in the [discord ](https://discord.com/channels/983865673656705025/1177071497974648952/1229178116128378992) too. On SST .408 but also had this issue in the .3xx as well. 

Tried a combination of sst remove/refresh/update with no luck. I would get this when running `sst dev`, not sure if I get this running the other commands, will try later.

**Comment by 0cv** [comment]
Very related issue, albeit a bit different, maybe because I'm running a newer version since June 7th (v0.0.501). 

```
/// <reference path="./.sst/platform/config.d.ts" />
import * as awsx from "@pulumi/awsx";

export default $config({
  app(input) {
    return {
      name: "my-app",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: { aws: true },
    };
  },
  async run() {
    const vpc = new awsx.ec2.Vpc("Vpc", {
      availabilityZoneNames: ["us-west-2a", "us-west-2b"],
      natGateways: { strategy: "Single" },
    });
  },
});
```

> Invalid component name "Vpc-1". Component names must start with an uppercase letter and contain only
alphanumeric characters

My guess is that Pulumi appends a `-1` to the name (despite the name being already unique in my AWS account), which conflicts with the naming convention defined by Ion. Also not sure why Ion enforces such convention to begin with.

**Comment by fwang** [comment]
Relaxed naming convention. This will be possible in the next release.
