### ISSUE TITLE
Not possible to use an existing S3 Bucket

### ISSUE THREAD

**Issue by budmitr** [sst/ion#52]
SST version: `0.0.194`

Discord discussion: [link](https://discord.com/channels/983865673656705025/1177071497974648952/1221080579458469972)

One of the coolest parts of SST was its ability to be used with existing infrastructure by importing existing objects, such as `Buckets` (e.g. https://docs.sst.dev/constructs/Bucket#importing-an-existing-bucket)

This feature seem to be missing from sst/ion completely

As a workaround, I tried to use `pulumi` constructs, but there are several issues:
* `aws.s3.BucketV2` gives errors, only `aws.s3.Bucket` works (sample below)
* `aws.s3.Bucket.onObjectCreated` gives an error when used with `sst` commands (sample below)

---
**Code Sample with `pulumi`**

```
import * as aws from "@pulumi/aws";
import { BucketEventHandler } from "@pulumi/aws/s3";

const processor: BucketEventHandler = async (event) => {
  console.log(event);
};
```

```
async run() {
  const bucketName = process.env.S3_UPLOADS_BUCKET;
  const bucket = aws.s3.Bucket.get("Uploads", bucketName);
  bucket.onObjectCreated("Processor", processor);
}
```

Gives an error when applied with `sst dev` or `sst deploy`

```
~  Deploying

|  Error        Invalid component name "Processor". Component names must be unique.
|  Creating    Uploads aws:s3:Bucket → Processor aws:s3:BucketEventSubscription
|  Created     Uploads aws:s3:Bucket → Processor aws:s3:BucketEventSubscription

×  Failed
   Invalid component name "Processor". Component names must be unique.
```

This error seems straightforward, but no matter how unique/random the resource name is generated, even if the whole stack is deleted and recreated, the error is still there -- looks like an issue with `pulumi` when being invoked with `sst`

<sub>[ION-238](https://linear.app/sst-dev/issue/ION-238/not-possible-to-use-an-existing-s3-bucket)</sub>

**Comment by thdxr** [comment]
using existing resources will work a bit differently in ion

we're still working on this feature but basically you will run something like `sst import MyBucket <my-existing-resource>` which will do a one time import into your state

from there everything will work as though sst created the resource in the first place

the issue you're running into though is unrelated i will look into it

**Comment by thdxr** [comment]
so assume you have an existing bucket provisioned by terraform

you cannot really have two tools that _own_ the same bucket so it does not make sense to do something like the following

```
new sst.aws.Bucket("MyBucket", { importFrom: "existingbucket" })
```

if you change properties on here should it change the underlying bucket? if so then the terraform deployment will see it it as drift and revert it

you basically have to pick which is the source of truth - if it's terraform then you have no need to use `sst.aws.Bucket` - you can just grab the existing one if you need to reference with `aws.s3.getBucket`

if you want to hand off ownership to `sst` then you do a one time `sst import` which will import the state of it into the state file - from then on it's no different than the bucket originally being created by `sst`

**Comment by fwang** [comment]
In v0.0.254, you can now subscribe to a pre-existing bucket like this - https://ion.sst.dev/docs/component/aws/bucket/#static-subscribe.
