### ISSUE TITLE
DynamoDB - Type Error Issue

### ISSUE THREAD

**Issue by Rafaa17** [sst/ion#531]
Hey, there seem to be a an issue when using DynamoDB from version v0.0.399 and above.

![image](https://github.com/sst/ion/assets/26599209/b180e959-97bb-446d-bfdf-93f1bc98da7b)

When manually installing version v0.0.398 this issue does not appear.

**Comment by thdxr** [comment]
fixed in v0.0.418 but would also suggest using the sst.Dynamo component
