### ISSUE TITLE
EventBus needs additional filters

### ISSUE THREAD

**Issue by mckamyk** [sst/ion#533]
I know EventBus for aws isn't quite ready for production yet but just wanted to note this behavior.

I've been playing with getting them working with the existing versions and they do work, but I've noticed there doesn't seem to be any filters applied.

If I have this Event.
```ts
import {event} from 'sst/event'
import {ZodValidator} from 'sst/event/validator'

const buildEvent = event.builder({
  validator: ZodValidator
})

export const FooEvent = buildEvent("app.FooEvent", z.object({ foo: z.string() }))

export const BarEvent = buildEvent("app.BarEvent", z.object({ bar: z.string() }))
```

create handlers with
```ts
import {bus} from "sst/aws/bus"
import {FooEvent} from "./events"

export const handler = bus.subscriber(FooEvent, async properties => {
  console.log(properties.foo)
})
```

And in sst.config.ts...
```ts
// sst.config.ts
const bus = new sst.aws.Bus("MyBus")

bus.subscribe({
  handler: 'path/to/foo.handler',
})
bus.subscribe({
  handler: 'path/to/bar.handler',
})
```

If I then invoke FooEvent by doing...
```ts
// some kind of resource with bus linked
import {bus} from "sst/aws/bus"
import {FooEvent} from "./events"

bus.publish(Resource.MyBus, FooEvent, { foo: "whaa" })
```

I noticed both the `foo` and `bar` subscribers will get invoked. 

To fix this I added the following to my `sst.config.ts`
```ts
bus.subscribe({
  handler: 'path/to/foo.handler'
}, {
  pattern: {
    detailType: ["app.FooEvent"],
    source: [`${$app.name}.${$app.stage}`] // for posterity ig
  }
})

bus.subscribe({
  handler: 'path/to/bar.handler'
}, {
  pattern: {
    detailType: ["app.BarEvent"],
    source: [`${$app.name}.${$app.stage}`]
  }
})
```

**Comment by mckamyk** [comment]
Shamelessly hijacking your attention, `sst dev bun dev` starts my dev server, but it appears `sst dev` does not pass in the `AWS_ACCESS_KEY_ID` and such needed.

running `sst dev` and `sst shell bun dev` works, as it appears `sst shell ...` does load these secrets.

**Comment by jayair** [comment]
@mckamyk Hmm maybe open a new issue for that?

**Comment by thdxr** [comment]
i'm not sure if this is a bug? ion eventbus will default to subscribing to all events (you can do a switch on the event)<br><br>if you do want to break it up into more detailed subscriptions you need to specify the filters as your example

**Comment by mckamyk** [comment]
I guess the reason I brought it up was because V2 EventBus had an extra argument in it.

```ts
  bus.subscribe("fooEvent", {  // I assumed "fooEvent" lead into pattern creation
    handler: "path/to/foo.handler",
    bind: [db],
  });
```

Whereas in Ion, this appears to be more manual.

Fine by me, as long as the docs reflect it.
