### ISSUE TITLE
Bug: sst secret set stuck

### ISSUE THREAD

**Issue by NotLuksus** [sst/ion#553]
When running `sst secret set SECRET_NAME VALUE` it gets stuck
Logs:
```
time=2024-06-13T16:19:30.653+02:00 level=INFO msg="loaded config" app=rapidnotes stage=notluksus
time=2024-06-13T16:19:30.653+02:00 level=INFO msg="INFO getting data key=secret app=rapidnotes stage=notluksus"
time=2024-06-13T16:19:30.828+02:00 level=INFO msg="INFO getting passphrase app=rapidnotes stage=notluksus"
time=2024-06-13T16:19:30.951+02:00 level=INFO msg="INFO putting secrets app=rapidnotes stage=notluksus"
time=2024-06-13T16:19:30.951+02:00 level=INFO msg="INFO putting data key=secret app=rapidnotes stage=notluksus"
time=2024-06-13T16:19:30.951+02:00 level=INFO msg="INFO getting passphrase app=rapidnotes stage=notluksus"
```

I doesn't let me Control + C the process so I have to actually terminate my console window to stop it.

Things I tried:
Change AWS region
Reset the entire sst state
Remove all old secrets

Nothing seemed to work

This is on the latest version of ION

**Comment by NotLuksus** [comment]
Also see my message on Discord for this:
https://discord.com/channels/983865673656705025/1177071497974648952/1248909379252523018

**Comment by jayair** [comment]
Might've missed on Discord if you already answered but did you try it with the `--verbose` flag?

**Comment by NotLuksus** [comment]
This is with the verbose flag

**Comment by jayair** [comment]
OS?

Do other sst commands work?

**Comment by NotLuksus** [comment]
Mac OS Sonoma 14.4
Yeah, everything else works

**Comment by jayair** [comment]
@thdxr What else do we need to debug this?

**Comment by thdxr** [comment]
does `sst secret list` work? and does it have the updated value even though it hung?

**Comment by NotLuksus** [comment]
I upgraded to the latest version and no it seems to be working again, no idea what caused this, probably fine to close
