### ISSUE TITLE
Cannot add Federated Identity Provider to Cognito User Pool

### ISSUE THREAD

**Issue by ianruan** [sst/ion#562]
SST Ion is awesome, but I cannot find a method to add a Federated Identity provider (eg. Google) to a Cognito user pool.

I see it's available in Pulumi: https://www.pulumi.com/registry/packages/aws/api-docs/cognito/identityprovider/

Could we get it exposed in sst? thanks.

**Comment by ianruan** [comment]
I see we can directly use Pulumi components, awesome, thank you.
https://ion.sst.dev/docs/providers#components

**Comment by jayair** [comment]
@ianruan added a PR for it https://github.com/sst/ion/pull/769

**Comment by fwang** [comment]
Merged PR
