### ISSUE TITLE
AWS Lambda Deployment Fails on M1 Mac with npm v10

### ISSUE THREAD

**Issue by gronxb** [sst/ion#578]
## Environment
M1 Mac
npm version v10

* sst.config.ts
```ts
new sst.aws.Remix("CuratorClip", {
  transform: {
    server: {
      nodejs: {
        install: ["@node-rs/argon2", "@node-rs/bcrypt"],
      },
      architecture: "arm64",
    },
   },
});
```

## Problem
I'm using the `@node-rs/*` module.

Deployments succeed, but the application is not accessible. This issue occurs because the node_modules directory uploaded to AWS Lambda is built for Darwin architecture. Starting from npm version 9, the arch and platform options have been changed to cpu and os.

* `--platform` to `--os`
* `--arch ` to `--cpu`

https://docs.npmjs.com/cli/v9/commands/npm-install#cpu

**Comment by thdxr** [comment]
i believe we merged a pr that fixes this - let me know if it's still broken

```
      const cmd = [
        "npm install",
        "--force",
        "--platform=linux",
        input.architecture === "arm64" ? "--arch=arm64" : "--arch=x64",
        // support npm versions 10 and above
        "--os=linux",
        input.architecture === "arm64" ? "--cpu=arm64" : "--cpu=x64",
      ];
```

**Comment by gronxb** [comment]
The issue has been resolved. Thank you.
