### ISSUE TITLE
ApiGatewayV2 does not allow using custom domains and custom stage names together

### ISSUE THREAD

**Issue by vvashisht** [sst/ion#592]
`createDomainMapping()` hard-codes the stage name as `$default` 

This does work for cases where either the intended stage name is `$default` OR custom domain names are not being used.

If custom domains are used, `aws.apigatewayv2.ApiMapping` gets created with `$default` stage. This works.

If in addition, a custom stage name is intended, there is no `ApiMapping` for it. I tried to add it explicitly, but `ApiGatewayV2` does not expose `aws.apigatewayv2.DomainName` in nodes which is needed for `ApiMapping`. 

_In general, in my opinion, `ApiGatewayV2` should allow more extensibility. Either through subclassing, or exposing all underlying components in nodes, or both._

**Comment by jayair** [comment]
This is related to your other issue? https://github.com/sst/ion/issues/587

**Comment by vvashisht** [comment]
Yes, I stumbled on to it because of #587 but felt that this issue can also come up without the situation presented #587.

The workaround for #587 involved abandoning a custom domain name and using a a CloudFront distribution instead and managing my own `aws.apigatewayv2.DomainName`, `aws.apigatewayv2.ApiMapping` and `aws.apigatewayv2.Stage`.

**Comment by fwang** [comment]
Thanks @vvashisht

The next release will expose `nodes.domainName` https://github.com/sst/ion/commit/44e93c478bd460cc3efbe340e9d6cc5a46345cdf
