### ISSUE TITLE
`sst init` fails for a next.js app

### ISSUE THREAD

**Issue by radokristof** [sst/ion#604]
SST CLI version:
Version 0.0.455 already installed

`sst init --verbose` output:
```
⠙  Installing providers...time=2024-06-26T00:55:57.264+02:00 level=INFO msg="config evaluated"
time=2024-06-26T00:55:57.264+02:00 level=ERROR msg="exited with error" err="Error evaluating config: exit status 1\nfile:///mnt/e/Work/github_projects/sample-proj/.sst/eval/eval-1719356157160.mjs:19\n      removal: input?.stage === \"production\" ? \"retain\" : \"remove\",\n                     ^\n\nSyntaxError: Unexpected token '.'\n    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)\n    at async link (internal/modules/esm/module_job.js:42:21)\n"
×  Unexpected error occurred. Please check the logs or run with --verbose for more details.
```

**Comment by radokristof** [comment]
This is even the case for a freshly created app with `create-next-app`

**Comment by radokristof** [comment]
This seems to be an issue on Windows / WSL. On Mac it runs perfectly

**Comment by iliaamiri** [comment]
@radokristof 

Seems like there is a syntax error in your `sst.config.ts` file around `removal: input?.stage === "production" ? "retain" : "remove",`.

That's what your error message is saying.

**Comment by radokristof** [comment]
@iliaamiri thank you for your response. sst.config.ts is generated by sst init and it is not modified by me.

**Comment by iliaamiri** [comment]
> @iliaamiri thank you for your response. sst.config.ts is generated by sst init and it is not modified by me.

I just tried spinning up a fresh Next.js app on AWS with the latest SST Ion as of now [v.0.0.456](https://github.com/sst/ion/releases/tag/v0.0.456) on WSL2 (Windows 11) and it was fine. Not sure why it happens on your end.

**Comment by radokristof** [comment]
Thanks. The only difference I found that on Mac, I had the newest .456 version, WSL 455. 

I checked, there is not that much of difference, maybe I should try the newer version as well

**Comment by thdxr** [comment]
i just tried sst init on a fresh nextjs project - seems to work for me going to close this for now<br><br>feel free to comment if there's still a problem

**Comment by radokristof** [comment]
@thdxr Thanks! Just for the record, I think I found the issue.
WSL had a really old nodejs version, after upgrading to latest LTS version, the issue disappeared.
