### ISSUE TITLE
New component: AWS Kinesis

### ISSUE THREAD

**Issue by EduSantosBrito** [sst/ion#605]
It would be great to have AWS Kinesis component for real-time data streaming and processing large volumes of data.

- [x] AWS Kinesis Data Stream
  - Based on: https://aws.amazon.com/kinesis/
  - PR opened: #574
- [ ] AWS Firehose
  - Based on: https://aws.amazon.com/firehose/
- [ ] AWS Apache Flink
  - Based on: https://aws.amazon.com/managed-service-apache-flink/

**Comment by fwang** [comment]
@EduSantosBrito lemme close this issue for now as KinesisStream is now supported.

Feel free to open a separate issue for Firehose when required.
