### ISSUE TITLE
Incorrect type: 'iam' in interface FunctionArgs for property url.authorization

### ISSUE THREAD

**Issue by vvashisht** [sst/ion#616]
Is: 
`authorization?: Input<"none" | "iam">;`

Should be:
`authorization?: Input<"none" | "aws_iam">;`

Or better yet:
`authorization?: Input<"NONE" | "AWS_IAM">;`

**Comment by cgcompassion** [comment]
Related: https://github.com/sst/ion/issues/611

**Comment by jayair** [comment]
Wait are the docs wrong?
<img width="620" alt="Screenshot 2024-07-03 at 7 48 49 PM" src="https://github.com/sst/ion/assets/53023/ee4a8c35-72d1-451a-a941-14ad8f341cd1">

**Comment by vvashisht** [comment]
Yes and no. They are consistent with [ApiGatewayV1RouteArgs](https://github.com/sst/ion/blob/e7010a50ff35c80ad528c60ab32cbe4048eda134/pkg/platform/src/components/aws/apigatewayv1-lambda-route.ts#L84) and [ApiGatewayV2RouteArgs](https://github.com/sst/ion/blob/e7010a50ff35c80ad528c60ab32cbe4048eda134/pkg/platform/src/components/aws/apigatewayv2-lambda-route.ts#L112) where `auth.iam` is a boolean and if `true`, is translated to `AWS_IAM`.

But in `FunctionArgs.url.authorization` is 'none' | 'iam' and is not translated to `AWS_IAM` and instead just [switched to upper case](https://github.com/sst/ion/blob/e7010a50ff35c80ad528c60ab32cbe4048eda134/pkg/platform/src/components/aws/function.ts#L1475).

**Comment by vvashisht** [comment]
Fixed by c256f29

Released in [v0.0.534](https://github.com/sst/ion/releases/tag/v0.0.534)
