### ISSUE TITLE
CongitoUserPool does not update successfully on deploy

### ISSUE THREAD

**Issue by joshwils82** [sst/ion#617]
When adding a sst.aws.CognitoUserPool, the sst deploy will run successfully on the first deploy but fail on an update with the following error.

```
Error       TestPool sst:aws:CognitoUserPool → TestPoolUserPool aws:cognito:UserPool
|  updating
urn:pulumi:jwilson::test::sst:aws:CognitoUserPool$aws:cognito/userPool:UserPool::TestPoolUserPool: 1
error occurred:
|
|  updating Cognito User Pool (us-east-1_StGlwm27q): cannot modify or remove schema items
```

here is an example sst.config.ts

```
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "test",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
     new sst.aws.CognitoUserPool('TestPool', {})
   // new aws.cognito.UserPool("PPool", {name: "mypool"}, {ignoreChanges: ["schemas"]})
  },
});
```

Please note that the same error occurs with the pulumi aws.cognito.UserPool resource but it can be worked around by adding the `ignoreChanges: ["schemas"]` option.  Currently, the sst construct does not pass the options to the pulumi resource so this work around does not work for sst.

My suggestion would be to support the options on the sst construct as it will likely be useful in other cases as well.

sst ion version: 0.0.473

**Comment by goto3** [comment]
I am also having this issue

**Comment by jayair** [comment]
Oh interesting. Thanks for the pointer.

**Comment by jakubknejzlik** [comment]
Still experiencing this error almost in every deployment (in version `0.0.498`) even with basic configuration and without touching the user pool. Current code:
```
const userPool = new sst.aws.CognitoUserPool("UserPool", {
  usernames: ["email"],
});
const client = userPool.addClient("FrontendApp");
```

What do You think about adding the temporary "fix" till #621 is resolved?
https://github.com/sst/ion/blob/dev/pkg/platform/src/components/aws/cognito-user-pool.ts#L217
```
{ parent, ignoreChanges: ["schemas"] },
```

**Comment by jakubknejzlik** [comment]
Nevermind, it seems that the upstream issue has been closed/fixed:

https://github.com/pulumi/pulumi-aws/issues/1813

**Comment by goto3** [comment]
Same issue in sst 0.0.535

**Comment by jayair** [comment]
Can you try the latest? If they've released it then we should have it too.

**Comment by joshwils82** [comment]
It looks to be working for me now.

**Comment by jayair** [comment]
Nice

**Comment by goto3** [comment]
Working for me too! thanks!
