### ISSUE TITLE
Pass `opts` to wrapped Pulumi resources

### ISSUE THREAD

**Issue by remembell-root** [sst/ion#621]
In many of the custom resources you use to wrap Pulumi's resources (SnsTopic, S3, etc) you don't pass the `opts`, and I see it as an error that needs fixing.

For example, in `SnsTopic` the code is:
```ts
function createTopic() {
  return new aws.sns.Topic(`${name}Topic`, transform(args.transform?.topic, { fifoTopic: fifo }), { parent });
}
```
so, `aws.sns.Topic` only gets `{ parent }` as `opts`.

It can be fixed by doing something similar to:
```ts
function createTopic() {
  return new aws.sns.Topic(`${name}Topic`, transform(args.transform?.topic, { fifoTopic: fifo }), { ...opts, parent });
}
```

**Comment by joshwils82** [comment]
This would also allow a workaround for https://github.com/sst/ion/issues/617

**Comment by jayair** [comment]
Hmm interesting. We'll need to consider the case when there are multiple resources inside a component.

**Comment by dror-weiss** [comment]
@jayair , since there is a `transform` options for Pulumi args you could (breaking) change to `transformArgs` and `transformOpts`. This will solve the case for multiple resources inside a component and be much clearer (in my opinion).

**Comment by fwang** [comment]
@remembell-root 
> so, aws.sns.Topic only gets { parent } as opts.
Pulumi passes a subset of opts to child resources by default, ie. `retainOnDelete`

**Comment by fwang** [comment]
In the latest version of SST, u can transform opts like this
```ts
new sst.aws.Bucket("MyBucket", {
  transform: {
    bucket: (args, opts) => {
      opts.retainOnDelete = true;
    },
  },
});
```

**Comment by dror-weiss** [comment]
@fwang, thanks for implementing this.

I'm sorry, I don't understand why use function transform and not pass the entire `opts` from the constructor (as suggested).

**Comment by jayair** [comment]
Cos the bucket component has multiple resources in it

**Comment by dror-weiss** [comment]
@jayair , could you please make notes for next **major** release to discuss the api change I suggested? It will make my code much cleaner and simpler to understand.
