### ISSUE TITLE
Allow to change lambda name in `api.route` transform

### ISSUE THREAD

**Issue by jorenvh1** [sst/ion#624]
We noticed that SST is trying to make sure all resources have a unique name by giving them random names. In some cases it's possible to adjust the names using the `transform` but for `api.route` it's not possible the change the lambda function's name.

It would be nice to allow this option.

**Comment by JanStevens** [comment]
Relates to the following issue: https://github.com/sst/ion/issues/244

In general I think it would be better to be:

1. Explicit about naming, you can always provide a name (and it will be prefixed with `$app-$stage` as usual), if not then the resource name can be used. This allows users to use whatever naming convention they already have.
2. When linking specify the name to use for linking like: `link: [{ userDB: accountDynamoDb}]` this would expose `accountDynamoDb` as `Resource.userDB`

Regards

**Comment by jayair** [comment]
Can you all share what changing the names helps you with? Is it for finding things in the AWS Console? Is it a policy at your team?

**Comment by JanStevens** [comment]
@jayair Hi, mainly policy and convention. Working for an agency means we have a lot of customers and different developers. If everyone uses the same naming conventions projects are easier to maintain by different developers.

For this issue specifically the route lambda name is not sensible, hence we would like to customize it. It also does not follow our naming convention

**Comment by jorenvh1** [comment]
@jayair Indeed, both of them to be honest. In general I'm confused by the naming conventions of the resources created by sst. But as long as they can be overwritten it's fine I guess 😉

**Comment by fwang** [comment]
You can now pass in `name` for a function - https://ion.sst.dev/docs/component/aws/function/#name

```ts
api.route("GET /", {
  name: "my-function",
  handler: "path/to/handler.index",
});
```
