### ISSUE TITLE
feature: support aws lambda streaming in sst live

### ISSUE THREAD

**Issue by thdxr** [sst/ion#63]
we don't currently support lambda streaming in sst live

streaming is currently very broken on aws lambda so we should wait till they fix it to make it more usable: https://twitter.com/thdxr/status/1772351862521430474

<sub>[ION-215](https://linear.app/sst-dev/issue/ION-215/feature-support-aws-lambda-streaming-in-sst-live)</sub>

**Comment by amir-ziaei** [comment]
Wonder if lambda streaming is more stable now 👀

**Comment by jayair** [comment]
Yeah we confirmed it's fully rolled out.

**Comment by jluisrojas** [comment]
Are the any updates on this? It will be cool to have streaming in dev mode
