### ISSUE TITLE
Can't install `ion` in MacOS

### ISSUE THREAD

**Issue by hungds99** [sst/ion#65]
---
OS: M1 v14.2.1

I tried to install `ion` but I got this issues

```
curl -fsSL https://ion.sst.dev/install | bash
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

**Comment by devRokas** [comment]
I have the same issue

**Comment by frixaco** [comment]
FYI, the issue seems to be introduced here: 40f8c1cc5c474356a98a4fef2f0f6a1f33fbf0b9. It looks like MacOS install script is trying to download different release binaries (`...-darwin-...` instead of `...-mac-...`)

**Comment by thdxr** [comment]
fixing right now, found a few mac related issues

**Comment by thdxr** [comment]
it should be fixed now - might take a bit for github caches to clear
