### ISSUE TITLE
using SST ion without typescript

### ISSUE THREAD

**Issue by pantoninho** [sst/ion#651]
I'm using SST v2 on a project without typescript and I'm interested in trying out migrating to SST Ion.
After running `sst init`, the `sst.config` file created references `$config` function that is declared inside a typescript definition file. I'm struggling to import that function in javascript.

Can I set up sst ion without typescript?

**Comment by jayair** [comment]
So Ion doesn't need your project to be in TS, you can leave the config in TS.

Or are you trying to use the config in JS?

**Comment by pantoninho** [comment]
Did not think about that. It works.

Thank you, closing!
