### ISSUE TITLE
Build error. No loader for .node files

### ISSUE THREAD

**Issue by telgueta** [sst/ion#657]
This is my stt.config code
```
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./.sst/platform/config.d.ts" />
import "sst";

export default $config({
  app(input) {
    return {
      name: "vecna-ts2",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    const vpc = new sst.aws.Vpc("VecnaVpc2");
    const rds = new sst.aws.Postgres("VecnaPostgres2", { vpc });
   const internalApi = new sst.aws.Function("MyApi2", {
      url: true,
      link: [rds],
      handler: "api/mscEdiReader/handler.handler",
      });

    return {
      api: internalApi.url,
    };
  },
});

```

Im trying to use the _ssh2-sftp-client_ library inside my _MyApi2_ function code. But when executing it throws the next error:
`|  ↳ No loader is configured for ".node" files: node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node
node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/crypto.js:30:20`

I tried forcing the bundle of the node packages inside the config files like this:
```

export default $config({
  app(input) {
    return {
      name: "vecna-ts2",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    const vpc = new sst.aws.Vpc("VecnaVpc2");
    const rds = new sst.aws.Postgres("VecnaPostgres2", { vpc })
    const internalApi = new sst.aws.Function("MyApi2", {
      url: true,
      link: [rds],
      handler: "api/mscEdiReader/handler.handler",
      nodejs: {
        esbuild: {
          external: ["ssh2-sftp-client"], // Asegúrate de que ssh2-sftp-client no sea empaquetado por esbuild
        },
      },
      });

    return {
      api: internalApi.url,
    };
  },
});

```
But it wont work.
Im 100% sure that the error happens when trying to initialize the _"ssh2-sftp-client_ client.
What can i do? I also tried to force the esbuild bundle

**Comment by jayair** [comment]
Can you try this instead? https://ion.sst.dev/docs/component/aws/function/#nodejs-install

**Comment by thdxr** [comment]
you should set `ssh2-sft-client` to `nodejs.isntall`

**Comment by CTC97** [comment]
I see this issue is marked as completed, so sorry to comment on here - but I see this is a recent issue so shooting my shot that you guys found a solution.

I'm getting this same error when I try to synth my AWS stack - added:

```
"nodejs": {
    "install": [
      "ssh2-sftp-client"
    ]
  }
```

to my package.json per @thdxr's suggestion, but am still getting the issue. Any advice?

**Comment by telgueta** [comment]
I fixed it adding this: 
` nodejs: {
        loader: {
          ".node": "file",
        },
      },
`

**Comment by CTC97** [comment]
I'm not using sst but this solution worked for me in CDK. I added the following to my lamba's NodejsFunction declaration: 

```
bundling: {
        loader: {
          ".node": "file",
        },
      },
```

Hopefully this helps anyone dealing with the same issue in cdk. Thanks @telgueta for the lightning fast and very helpful reply. ⚡ :godmode: ⚡

**Comment by kierianlee** [comment]
Is there a way to also add the nodejs.install option to `new sst.aws.Remix`?

**Comment by jayair** [comment]
@kierianlee I don't think so. Maybe open a new issue?
