### ISSUE TITLE
Monorepo setup doesn't resolve imported infra correctly

### ISSUE THREAD

**Issue by shmuli9** [sst/ion#659]
I am trying to split up my existing stack into a monorepo style:

```typescript
// sst.config.ts

/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "MyApp",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: {
        aws: {
          region: "eu-west-2",
        },
        cloudflare: true,
      },
    };
  },
  async run() {
    const infra = await import("./infra");

    return {
      url: infra.remix.url,  // <-- this line is erroring
    };
  },
});
```

Strangely when I run `sst deploy` I get this error:

```
|  Error
|  TypeError: Cannot read properties of undefined (reading 'url')
|      at run (file:///home/code/app/sst.config.ts:22:24)
|      at run (file:///home/code/app/.sst/platform/src/auto/run.ts:36:20)
|      at file:///home/code/app/eval.ts:8:22
```

Using `SST ❍ ion 0.0.501`

If I remove the `url` returned from the `run()` function, everything works as expected

**Comment by jayair** [comment]
Hmm we do it here: https://github.com/sst/ion/blob/dev/examples/aws-monorepo/sst.config.ts

**Comment by shmuli9** [comment]
So I think the issue was a top level wait in my `./infra/remix.ts` file. For whatever reason this wasn't working nicely. 

I solved this by moving all my async code into async functions, and exported `const remix = await getRemix();` which works fine. 

In hindsight, this may not be a bug, but maybe could do with some async examples in docs? (FYI: I am using an async fn to prepare my layer files, and zip them up)

**Comment by jayair** [comment]
Yeah closing for now
