### ISSUE TITLE
error: no such bucket on a new fresh project

### ISSUE THREAD

**Issue by veritem** [sst/ion#661]
Hey, thank you so much for this library!!!

I have played around with ion 2 months ago, which really was nice. however, I'm trying it again and getting an error that I don't know what's going on. 

<img width="1067" alt="image" src="https://github.com/sst/ion/assets/53856673/fdcc6b60-189d-4939-a9f0-8a54ae15c6ef">

this error is showing up on every sst ion project I create on my laptop. I guess it has to do with my configurations, but I can't tell which. I have all my aws  credentials in the right place. Has anyone ever dealt with something like this? PS: I'm not even using s3 bucket in my projects.

**Comment by shmuli9** [comment]
I am seeing the same issue - weird cos my existing projects work as expected

**Comment by jayair** [comment]
Did you remove the state bucket from your AWS account? You can read a bit more about this https://ion.sst.dev/docs/providers/#state

**Comment by veritem** [comment]
@jayair I might have deleted something(I'm learning as I go), but even running `sst refresh` outputs the same error

**Comment by shmuli9** [comment]
I don't recall deleting anything, but let's say I did. What's the path to fixing this? `sst refresh` doesn't seem to help

**Comment by thdxr** [comment]
can you go to SSM parameters in aws console and find the `/sst/bootstrap` one and look at its value? it should point to an s3 bucket that exists - if it doesn't it seems that you deleted it.

recreating it should fix

**Comment by veritem** [comment]
thank you so much dax!!! i got it working

for anyone who will face this error, check SSM parameter in aws console and make sure all s3 buckets (listed under`/sst/bootstrap`, `/sst/bootstrap/asset`) exists in the same region. if they don't exist create them. That was the issue for me.
