### ISSUE TITLE
ApiGatewayV2 route without a handler

### ISSUE THREAD

**Issue by 0cv** [sst/ion#664]
For example, a route could be a proxy, something like this:
```
httpApi.route("$default", "", {
  transform: {
    integration: {
      description: "Example with a load balancer",
      integrationType: "HTTP_PROXY",
      integrationUri: service.nodes.loadBalancer.arn,
      integrationMethod: "ANY",
      connectionType: "VPC_LINK",
      connectionId: vpcLink.id,
    },
  },
});
```
But specifying `null`, `undefined` or `""` to the handler will throw an exception at the moment.

With CDK, the equivalent above was relatively concise:
```
httpApi.addRoutes({
  path: "/{proxy+}",
  methods: [HttpMethod.ANY],
  integration: new HttpAlbIntegration("alb-integration", listener, {
    vpcLink,
  }),
});
```

**Comment by fwang** [comment]
@0cv added `routeUrl()`. Doc here - https://ion.sst.dev/docs/component/aws/apigatewayv2/#routeurl

It will be available in the next release.

**Comment by 0cv** [comment]
@fwang thanks, but this doesn't address my issue. There is a relatively large list of possible integration options, and I think that this PR handles only the `HTTP URI` redirection
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/44be2129-e195-4508-97f8-9ff3b8662937">

However, I've been looking to send the request to a VPC link and Load Balancer in my VPN (the option Private resource in the screenshot above).

Using a mix of Ion with Pulumi, this is how this looks like at the moment:

```
const httpApi = new sst.aws.ApiGatewayV2("HttpApi");
const httpAuthorizer = httpApi.addAuthorizer({
  name: "HttpApiAuthorizer",
  jwt: {
    audiences: [userPoolClient.id],
    issuer: $interpolate`https://cognito-idp.${region}.amazonaws.com/${userPool.id}`,
  },
});

$resolve([
  httpApi.nodes.api.id,
  httpAuthorizer.id,
]).apply(
  async ([
    httpApiId,
    httpAuthorizerId,
  ]) => {
    const integration = new aws.apigatewayv2.Integration("Default", {
      apiId: httpApiId,
      description: "Integration to the load balancer",
      integrationType: "HTTP_PROXY",
      integrationUri: elbListener.arn,
      integrationMethod: "ANY",
      connectionType: "VPC_LINK",
      connectionId: vpcLink.id,
    });

    new aws.apigatewayv2.Route("Get", {
      apiId: httpApiId,
      authorizationType: "JWT",
      authorizerId: httpAuthorizerId,
      target: $interpolate`integrations/${integration.id}`,
      routeKey: "GET /{proxy+}",
    });
  }
);
```

For simplicity, I've purposefully omitted the Load Balancer, VPC Link, etc.

**Comment by 0cv** [comment]
@jayair @fwang not sure my latest message has been seen, but in short the initial issue has not been addressed. The title of the issue was certainly not clear and I've updated it.

**Comment by jayair** [comment]
Interesting, so are you looking for support for all these integrations?

**Comment by 0cv** [comment]
@jayair not all, just the Private Resource. Would it not make sense that the API Gateway you're supporting integrates with the ELB you're supporting?

**Comment by jayair** [comment]
It's really based on what people request. Can you open a new issue for this instead?
