### ISSUE TITLE
feature: sst.aws.Bus

### ISSUE THREAD

**Issue by thdxr** [sst/ion#67]
implement the event bus concept with typed events

<sub>[ION-222](https://linear.app/sst-dev/issue/ION-222/feature-sstawsbus)</sub>

**Comment by eduardokanema** [comment]
Hi @thdxr, I'm happy to do the implementation of this component. Any specifications that I should follow?

**Comment by jamlen** [comment]
This is a definite blocker for us moving to v3 as we use EventBridge extensively to decouple.

**Comment by kieranm** [comment]
Bus is available, it's just undocumented at the moment:
https://github.com/sst/ion/tree/dev/examples/aws-bus

**Comment by joshsutheran-habitude** [comment]
Agreed with @jamlen - leverage EventBridge heavily to decouple - would be great to prioritise this.

**Comment by kieranm** [comment]
@joshsutheran-habitude It has been implemented already - see the link I posted above

**Comment by ajotaos** [comment]
What approach there is for referencing the default bus using this component? I tried to follow the import option but it said that it would not let me assign "default" as a name.

**Comment by eduardokanema** [comment]
> What approach there is for referencing the default bus using this component? I tried to follow the import option but it said that it would not let me assign "default" as a name.

Hi @ajotaos, maybe because the resources need to start with Capital letters? Try `Default`

**Comment by ajotaos** [comment]
No luck sorry, if I do that:

```
new sst.aws.Bus(prefixComponentName('Default'), {
	transform: {
		bus: (args, opts) => {
			args.name = 'Default' // or even if I omit this line

			opts.import = 'default'
		}
	}
})
```

The CLI rejects it with:

```
✕  Failed
   ComicbookPagesDefault sst:aws:Bus → ComicbookPagesDefaultBus aws:cloudwatch:EventBus
   inputs to import do not match the existing resource

Set the following in your transform:
   - `args.name = "default";`
```

Otherwise if I do this instead:

```
new sst.aws.Bus(prefixComponentName('Default'), {
	transform: {
		bus: (args, opts) => {
			args.name = 'default'

			opts.import = 'default'
		}
	}
})
```

The CLI rejects it with:

```
✕  Failed
   ComicbookPagesDefault sst:aws:Bus → ComicbookPagesDefaultBus aws:cloudwatch:EventBus
   aws:cloudwatch/eventBus:EventBus resource 'ComicbookPagesDefaultBus' has a problem: invalid value for name (cannot be 'default'). Examine values at 'ComicbookPagesDefaultBus.name'.
```

**Comment by wedgybo** [comment]
As this feature isn't fully finished I thought I'd raise a simple issue here when importing partner buses. Because of the long name given to the bus when it's a partner one it breaks the character limit when trying to create the rule and target.

```
export const shopify = new sst.aws.Bus('Shopify', {
    transform: {
        bus: (args, opts) => {
            args.name = 'aws.partner/shopify.com/XXXXXXXXXX/together-dev-jsutherland'
            // opts.import = 'aws.partner/shopify.com/XXXXXXXXX/together-dev-jsutherland'
        }
    }
})
```

```
Failed AwspartnershopifycomXXXXXXXXXXtogetherdevjsutherlandSubscriberHrtotzRule aws:cloudwatch:EventRule could not make instance of 'aws:cloudwatch/eventRule:EventRule': name 'AwspartnershopifycomXXXXXXXXXXtogetherdevjsutherlandSubscriberHrtotzRule-' plus 7 random chars is longer than maximum length 64
```

```
Failed AwspartnershopifycomXXXXXXXXXXtogetherdevjsutherlandSubscriberHrtotzTarget aws:cloudwatch:EventTarget aws:cloudwatch/eventTarget:EventTarget resource 'AwspartnershopifycomXXXXXXXXXXtogetherdevjsutherlandSubscriberHrtotzTarget' has a problem: "target_id" cannot be longer than 64 characters: "AwspartnershopifycomXXXXXXXXXXtogetherdevjsutherlandSubscriberHrtotzTarget-e1e5c79". Examine values at 'AwspartnershopifycomXXXXXXXXXXtogetherdevjsutherlandSubscriberHrtotzTarget.targetId'.
```

This is the workaround below incase anyone else is running into the same issues

```
// We overwrite the generated rule names when subscribing
// as they are too long when importing a partner event bus.
events.shopify.subscribe('services/upload/src/events.shopify', {
  transform: {
    rule: (args, opts) => {
      args.name = 'new_rule_name'
    },
    target: (args, opts) => {
      args.targetId = 'new_target_id'
    }
  }
})
```

**Comment by exceptionrambler** [comment]
> @joshsutheran-habitude It has been implemented already - see the link I posted above

We are relatively new to SST but use EventBus heavily in v2. 
Do you happen to have an example implementation of EventBus in Ion?
We think it makes sense for us to migrate but are hesitant to do so without this being documented.

**Comment by ajotaos** [comment]
I ended up using the static function of Bus.subscribe and getting the ARN from the pulumi aws module function.

**Comment by mckamyk** [comment]
> > @joshsutheran-habitude It has been implemented already - see the link I posted above
> 
> We are relatively new to SST but use EventBus heavily in v2. Do you happen to have an example implementation of EventBus in Ion? We think it makes sense for us to migrate but are hesitant to do so without this being documented.

`sst.config.ts`
https://github.com/sst/ion/blob/3cc1603bba6a1eb8a4a178134450f808fb253ddb/examples/aws-bus/sst.config.ts

`publisher`
https://github.com/sst/ion/blob/3cc1603bba6a1eb8a4a178134450f808fb253ddb/examples/aws-bus/src/index.ts

`subscriber`
https://github.com/sst/ion/blob/3cc1603bba6a1eb8a4a178134450f808fb253ddb/examples/aws-bus/src/receiver.ts

I'd recommend adding filters if you have more than one subscriber.
mentioned in #533

**Comment by kieranm** [comment]
@jsadoski-rockhall What's the blocker? Did you see it's been implemented above?

**Comment by eduardokanema** [comment]
Hey guys, maybe send a message using https://sst.dev/discord the dev team usually don't read the threads here, but they promptly replied there.

**Comment by jayair** [comment]
Yeah the feedback here helps us prioritize this. We do go through the issues here.

There's still a bit of work to do before we release this.

**Comment by ajotaos** [comment]
Is the source code for bus with queues as a target open sourced someplace?

**Comment by silberistgold** [comment]
Yes, we definitely need this to be stable before migrating to v3 and it is currently the only feature missing in v3 that we depend on.

**Comment by hannahhoward** [comment]
FWIW we are also blocked on EventBus as SST v2 users -- https://github.com/storacha-network/w3infra

**Comment by MaximBuz** [comment]
This would be the last building block for us to migrate over to v3

**Comment by knoffi** [comment]
Our team would also strongly depend on a stable and reliable version of this , otherwise a migration to v3 would be out of the question for us.

**Comment by JohnG45** [comment]
Just to be clear, the current implementation (as of 3.0.91) does not work if you need publish messages to your bus, which presumably is a requirement for most apps. This is because it's not possible to link the bus to a function - see [#918](https://github.com/sst/ion/issues/918#issuecomment-2325096892).

**Comment by ryanpeggs** [comment]
Same here, bus is the last blocker for us migrating to ion

**Comment by thdxr** [comment]
we fixed the issue related to linking a bus to apig

**Comment by AdditionAddict** [comment]
bit confused, what's the issue here given it's getting used in [terminaldotshop](https://github.com/terminaldotshop/terminal/blob/dev/infra/bus.ts)?

**Comment by 5o50** [comment]
this one is a blocker too https://github.com/sst/ion/issues/1086
