### ISSUE TITLE
feature: sst preview

### ISSUE THREAD

**Issue by thdxr** [sst/ion#68]
get a preview of changes without actually deploying them

<sub>[ION-223](https://linear.app/sst-dev/issue/ION-223/feature-sst-preview)</sub>

**Comment by JanStevens** [comment]
Small addition, right now `deploy` will start deploying without confirmation. In pulumi and terraform you can review the changes and go for a `yes` or `no`.

IMO thats great DX and gives me some ease / pease of mind

**Comment by dankochetov** [comment]
Seems like this is now implemented as `sst diff`
https://sst.dev/docs/reference/cli#diff

**Comment by jayair** [comment]
Yup closing
