### ISSUE TITLE
Uploading Ion/esbuild generated sourcemaps to Sentry

### ISSUE THREAD

**Issue by paolostyle** [sst/ion#681]
So there is [an article](https://docs.sst.dev/advanced/source-maps#sentry) on how to do this in SST v2 but I don't think it has any use with Ion as there doesn't seem to be anything like `hooks`. I tried using Sentry's esbuild plugin but there were some cryptic error messages and then I found #568 so I guess that's not an option. In general I'm looking for a way to generate the sourcemaps, _not_ upload them to AWS during the deployment, and still be able to do something with them post-deployment (i.e. use the Sentry CLI).

**Comment by jayair** [comment]
I guess you could upload it as a part of your deployment process right?

**Comment by paolostyle** [comment]
Sure. I guess at the end of the day it's not that important to me when or how that happens, I just want to have it uploaded for every production release.

I still feel like providing a way to use esbuild plugins is the way to do it as Sentry's plugin does all the heavy lifting but if you have other ideas I'm all for it

**Comment by jayair** [comment]
Yeah we'll need to figure out a good way to allow for this.

**Comment by jayair** [comment]
Yeah I see. Let's look at the esbuild plugin issue here https://github.com/sst/ion/issues/568
