### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Jonathanchan1996** [sst/ion#687]
It has been observed that Live Lambda does not work properly over a Docker container, even when using a Docker volume. To address this issue, it is recommended to update the code directly inside the Docker container.

**Comment by thdxr** [comment]
sst uses your OS's file watching api to listen to file changes - it's possible that that isn't working correctly when in a docker container?<br><br>can you tell me more about the setup so i can try it out

**Comment by Jonathanchan1996** [comment]
I think that is not a sst issue. I guess sst use linux inotify to trigger it but I am using windows 11 host to docker container. when the host updating the volume, the host's file system cannot trigger the container's file system. Nothing sst can do in this case. Thanks man 

> sst uses your OS's file watching api to listen to file changes - it's possible that that isn't working correctly when in a docker container?can you tell me more about the setup so i can try it out

**Comment by jayair** [comment]
Closing for now
