### ISSUE TITLE
deploying on different stage fails when domain name is configured with cloudflare

### ISSUE THREAD

**Issue by veritem** [sst/ion#695]
I have a domain name configured with Cloudflare, which works perfectly with Ion. However, I'm trying to deploy my app on a stage other than the default one, but it's failing with the following error: `expected DNS record to not already be present but already exists`

**Comment by thdxr** [comment]
can i see the code for this? if you have two stages they can't both have the same domain name

**Comment by veritem** [comment]
I had my app already deployed on the default stage. However, changing it to production results in the error above. 

this my sst.config.ts

```ts
/// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app(input) {
    return {
      name: "notes",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: { cloudflare: true }
    };
  },
  async run() {
    new sst.aws.Astro("MyWeb", {
      domain: {
        name: $app.stage == "production" ? "my-domain.com" : $app.stage + "-my_subdomain.com",
        dns: sst.cloudflare.dns({
          zone: "my_zone_id"
        })
      }
    });
  },
});
```

I removed my wn credentials (this is internet lol)

**Comment by veritem** [comment]
to make it work, i had to run `sst remove` and then `sst deploy --stage production`. it would be nice if SST had an option to detect stage change and handle domain creation properly
