### ISSUE TITLE
Lambad trigger policy is missing when using transform in congito

### ISSUE THREAD

**Issue by imdkbj** [sst/ion#697]
Cognito lambda is throwing error **PreTokenGeneration invocation failed due to error AccessDeniedException**

<img width="640" alt="image" src="https://github.com/user-attachments/assets/12f103c4-c672-4349-80cd-68be7fe3ae5e">

 The reason to use transform here is that if we pass triggers in args then it is not working for imported lambda from another file.
 
 Suspected code block
 
<img width="821" alt="image" src="https://github.com/user-attachments/assets/52b1a886-d360-4803-8c44-8b615719899b">

**Comment by jayair** [comment]
Can you tell me more about this?

> not working for imported lambda from another file

**Comment by imdkbj** [comment]
Hi @jayair Please find. Am i doing something wrong!

<img width="747" alt="Screenshot 2024-07-22 at 12 01 09 AM" src="https://github.com/user-attachments/assets/87ada61a-4098-40c5-a753-13f3e870486c">


```js
import { config } from 'dotenv'

const _stage = $app.stage
const parsedENV = config({ path: `./lambda/.env.${_stage}` }).parsed

export const lambda = new sst.aws.Function('CognitoHandler', {
  handler: './lambda/index.handler',
  environment: {
    ...parsedENV,
    MAX_ATTEMPTS: 3
  },
  description: 'cognito-handlers',
  runtime: 'nodejs20.x',
  timeout: '10 seconds',
  memory: '1024 MB',
  permissions: [
    {
      actions: ['ses:SendEmail', 'ses:SendRawEmail'],
      resources: ['*']
    },
    {
      actions: ['sns:Publish', 'sns:Subscribe'],
      resources: ['*']
    }
  ],
  logging: {
    retention: '3 year' // for audit purpose
  },
  transform: {
    function: {
      name: `${_stage}-sso-cognito-handler`
    }
  }
})
```

**Comment by fwang** [comment]
@imdkbj When you pass in function ARNs via `transform`, you are responsible for creating the function and assigning the required permissions. So you'd have to create the `aws.lambda.Permission` resources as shown in ur code block above.

Btw, why r the functions created separately? Can't you create them inline?

**Comment by imdkbj** [comment]
Hey @fwang Thanks for the inputs.

1. Agree with the transform point.
2. I am creating seprate lamda as only one lambda is being assigned to all event. Lambda is being created in same sst deploy session not isolated anyhow.
3. Can you check why last photo why that is giving promise error. That can solver the underlying permission issue.

If required, I can share the all codes here.

**Comment by fwang** [comment]
@imdkbj `triggers` expects path to the handler, not ARN of existing functions. Give this a try:
```ts
new sst.aws.CognitoUserPool("MyUserPool", {
  transform: {
    userPool: {
      lambdaConfig: {
        createAuthChallenge: lambda.arn,
        defineAuthChallenge: lambda.arn,
        ...
      }
    }
  }
});
```

Feel free to reopen this if issue persist.

**Comment by imdkbj** [comment]
Hi @fwang Thanks.
As you can see in my screenshot, I am using the exactly same. But how we can make use without transformer where a single lambda will be used for multiple triggers as if we use path then multiple lambda will be created.

**Comment by jayair** [comment]
I'm confused, are you saying you don't want to use the `transform`?

**Comment by imdkbj** [comment]
Hey, Yes! I can skip transform if we can get the option to pass path/arn to the function handler.
