### ISSUE TITLE
Cluster.addService - option to pull container image instead of build

### ISSUE THREAD

**Issue by elijahmorg** [sst/ion#706]
Add the ability to bypass building docker images and instead pull an already existing image. It could look something like this.

https://www.pulumi.com/registry/packages/docker/api-docs/remoteimage/

Reason for this is our containers are built in a different pipeline and already pushed into ECR. But being able to pull both from a public registry or private ECR would be good.

```ts
    const cluster = new sst.aws.Cluster("MyCluster", { vpc });
    const remoteImage = new docker.RemoteImage("ubuntu", { name: "ubuntu:precise" });

    cluster.addService("MyService", {
      public: {
        ports: [{ listen: "80/http" }],
      },
      transform: {
        image: {
          remoteImage: remoteImage,
        }
      }
    });
```

**Comment by fwang** [comment]
@elijahmorg `Cluster` switched to use the new `DockerBuild` component now - https://www.pulumi.com/registry/packages/docker-build/api-docs/image/

Does it support what you are trying to do?

/cc @arpadgabor

**Comment by fwang** [comment]
Supported in the latest version. `image` takes ie. `nginx:latest`.
