### ISSUE TITLE
Handle CORS in API Gateway

### ISSUE THREAD

**Issue by hukedd** [sst/ion#707]
I see that the old SST version has a cors property further configure the specifics if necessary: https://sst.dev/chapters/handle-cors-in-serverless-apis.html

Defaults are fine for most things but if you're wanting to build a secure app it will be necessary to specify a more restrictive CORS configuration.

How can this be done in Ion? 

Can't see anything documented or in the source API: https://ion.sst.dev/docs/component/aws/apigatewayv2/

**Comment by gusugusu1018** [comment]
Please refer to this link.

https://github.com/gusugusu1018/sst-ion-serverless-todoapp/blob/main/infra/api.ts

**Comment by steduardo** [comment]
@gusugusu1018 thanks!

Great repo. Looks like you're applying an authorizer implicitly on https://github.com/gusugusu1018/sst-ion-serverless-todoapp/blob/1c0e6f367afefabb7eef3967ebe25bbce91a9df3/infra/api.ts#L25

but if I try it does not recognise the audiences property; 

`

 object literal may only specify known properties, and 'audiences' does not exist in type 'Input<{ authorizer: Input<string>; scopes?: Input<Input<string>[]> | undefined; }>'

`

**Comment by jayair** [comment]
@gusugusu1018 nice!

@fwang we should top level this probably?

**Comment by fwang** [comment]
Released in v0.1.9 - https://ion.sst.dev/docs/component/aws/apigatewayv2#cors

**Comment by gusugusu1018** [comment]
@steduardo Thanks!

I just checked and it worked on 0.0418.
Version 0.0.546 gave me this error, so I'm assuming it's an ion issue.

> @gusugusu1018 thanks!
> 
> Great repo. Looks like you're applying an authorizer implicitly on https://github.com/gusugusu1018/sst-ion-serverless-todoapp/blob/1c0e6f367afefabb7eef3967ebe25bbce91a9df3/infra/api.ts#L25
> 
> but if I try it does not recognise the audiences property;
> 
> `object literal may only specify known properties, and 'audiences' does not exist in type 'Input<{ authorizer: Input<string>; scopes?: Input<Input<string>[]> | undefined; }>'`

**Comment by gusugusu1018** [comment]
@steduardo 
It's a little late, but I updated!

https://github.com/gusugusu1018/sst-ion-serverless-todoapp/commit/b6fdcf72fd095449efadb106f4924e34f6e60db9

> @steduardo Thanks!
> 
> I just checked and it worked on 0.0418. Version 0.0.546 gave me this error, so I'm assuming it's an ion issue.
> 
> > @gusugusu1018 thanks!
> > Great repo. Looks like you're applying an authorizer implicitly on https://github.com/gusugusu1018/sst-ion-serverless-todoapp/blob/1c0e6f367afefabb7eef3967ebe25bbce91a9df3/infra/api.ts#L25
> > but if I try it does not recognise the audiences property;
> > `object literal may only specify known properties, and 'audiences' does not exist in type 'Input<{ authorizer: Input<string>; scopes?: Input<Input<string>[]> | undefined; }>'`
