### ISSUE TITLE
Unable to set batchSize for queue subscriber

### ISSUE THREAD

**Issue by shen-lin** [sst/ion#716]
I was trying to set batchSize based on sst documentation: https://ion.sst.dev/docs/component/aws/queue/#transform-1. Based on the documentation, subscribe function takes a 2nd argument QueueSubscriberArgs. So I was trying to apply transform config in QueueSubscriberArgs.transform.eventSourceMapping.batchSize.

```
const taskQueueSubscriber = taskQueue.subscribe({
  handler: "...",
  link: [database, updateQueue],
}, {
  transform: {
     eventSourceMapping: {
        batchSize: 1,
        functionName: ''
     }
  }
});
```

The problem is functionName is a mandatory field in type eventSourceMapping. It requires subscriber's arn or name to be provided. But the subscriber instance is not available until calling subscribe.

Since the subscribe function instantiates the subscriber internally, can it set eventSourceMapping.functionName internally?

Or can we have a function to apply transform after `taskQueueSubscriber` is instantiated and returned from `taskQueue.subscribe` function?

**Comment by fwang** [comment]
@shen-lin The code u shared works for me.

Are you getting a type error, or error on deploy?

**Comment by shen-lin** [comment]
> functionName: ''

Hi @fwang,

Thanks for looking into this. The code would result in error during deploy. Because I left "functionName" empty in my code. 

My main problem is not able to benefit from the convenience from sst (btw, Thank for the great work and I have been really spoiled by the convenience offered by sst). In this specific case, I expected to provide the functionName as:

`functionName: taskQueueSubscriber.function.arn`

But taskQueueSubscriber is not instantiated before` taskQueue.subscribe()` call. 

Of course, I can predict the sst naming of taskQueueSubscriber and hardcode the value for "functionName" property. But as a spoiled developer, I am wondering if there is better way of doing it.

**Comment by brunocleite** [comment]
@shen-lin I am using just like you, and it is not requiring me the `functionName` property as mandatory. 

Anyway, I worked on a PR #762 to add support for setting `batchSize` directly, so that may fix your issue also.

**Comment by fwang** [comment]
@shen-lin Just added support for batch size https://github.com/sst/ion/pull/756

In the next release, you can set batch size like this:
```ts
    queue.subscribe("subscriber.handler", {
      batch: {
        size: 100,
      },
    });
```
