### ISSUE TITLE
Unable to find ApiGatewayV1 in sst package

### ISSUE THREAD

**Issue by athapliyal** [sst/ion#717]
Hi Team,

Just tried using ApiGatewayV1 for REST API but the code for it is not present in the sst package

<img width="524" alt="Screenshot 2024-07-19 at 3 12 05 pm" src="https://github.com/user-attachments/assets/a913a007-60e8-482c-9588-a67ab88eb87a">

I am getting an error

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/11ecbcbd-fa6b-4732-856b-30093e3b2e9d">

**Comment by jayair** [comment]
Weird https://github.com/sst/ion/blob/dev/platform/src/components/aws/index.ts#L1

Can you check the latest?

**Comment by athapliyal** [comment]
Hey @jayair , here is a video of a brand new setup using ```sst init```. ApiGatewayV1 is missing in the export

https://github.com/user-attachments/assets/394aefb3-e923-414f-8b53-6c639c0373ca

**Comment by jayair** [comment]
That's weird. What version of the CLI do you have?

<img width="696" alt="Screenshot 2024-07-19 at 5 34 18 PM" src="https://github.com/user-attachments/assets/908ad652-4ef6-4fee-a281-234414670e3b">

**Comment by athapliyal** [comment]
My bad, I thought I updated the CLI. It is present in latest version
