### ISSUE TITLE
Cloudflare bucket resource types missing

### ISSUE THREAD

**Issue by beeirl** [sst/ion#735]
### Expected outcome
Resource should be added to `.sst/types.generated.ts` to make it accessible via `Resource.MyBucket`.

### Actual outcome
Resource is missing in `.sst/types.generated.ts`

```
/* tslint:disable */
/* eslint-disable */
import "sst"
declare module "sst" {
  export interface Resource {
  }
}
export {}
```

### Steps to reproduce
 1. Run `sst init`
 2. Select Cloudflare
 3. Add `new sst.cloudflare.Bucket("MyBucket");` to `sst.config.ts` `run()`
 4. Add `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_DEFAULT_ACCOUNT_ID` env vars to your `.env` file
 5. Run `sst deploy`

**Comment by thdxr** [comment]
i did find a bug related to this but it wasn't the same thing you produced<br><br>when i run the `examples/cloudflare-hono` example i get the following types with latest sst (v0.1.10)

```
/* tslint:disable */
/* eslint-disable */
import "sst"
declare module "sst" {
  export interface Resource {
  }
}
// cloudflare 
declare module "sst" {
  export interface Resource {
    MyBucket: import("@cloudflare/workers-types").R2Bucket
  }
}
export {}
```

**Comment by beeirl** [comment]
my bad @thdxr. works for me as well with latest sst (v0.1.17). at the time of writing the ticket, my sst version was v0.0.413. I ran `sst upgrade` a week ago or so but apparently it didn't update even though I got a success message. Installed sst using homebrew on my mac and had to run `brew upgrade sst` - missed that in the CLI docs.
