### ISSUE TITLE
npm: `npx sst upgrade` does not work

### ISSUE THREAD

**Issue by shmuli9** [sst/ion#737]
When installing sst with `npm` and executing it with `npx` sst does not actually get upgraded

> \> npx sst upgrade
> ✓  Upgraded 0.1.1 ➜ 0.1.8
>
> \> npx sst version
> 0.1.1

**Comment by shmuli9** [comment]
Pretty sure the solution is going to revolve around triggering npm to actually update and install the sst binary in the package.json/node_modules (or wherever npx stores its binaries)

If that is out of scope, maybe disable the `upgrade` command for npm installs? Or add a warning that it won't work?

**Comment by thdxr** [comment]
yeah that's right we probably need to do what v2 did and switch to just ugprading package.json<br><br>need to look into how to reliably detect if it's running via a local install in node_modules, have a few things that depend on this

**Comment by yyaskriloff** [comment]
I'm having the same issue  #739 I originally downloaded sst using homebrew then used `curl -fsSL https://ion.sst.dev/install | bash` and got 

```
> sst upgrade
Warning: You are using a global installation of SST but you also have a local installation specified in your package.json. The local installation will be used but you should typically run it through your package manager.
✔︎  Upgraded 0.1.12 ➜ 0.1.29
> sst version
Warning: You are using a global installation of SST but you also have a local installation specified in your package.json. The local installation will be used but you should typically run it through your package manager.
0.1.12
```

**Comment by shmuli9** [comment]
> yeah that's right we probably need to do what v2 did and switch to just ugprading package.json<br><br>need to look into how to reliably detect if it's running via a local install in node_modules, have a few things that depend on this

Thanks @thdxr, looks like you pushed the npm upgrade logic in the past couple days. Works great!
