### ISSUE TITLE
Updating SST package

### ISSUE THREAD

**Issue by yyaskriloff** [sst/ion#739]
This might be my ignorance but to my understanding the sst upgrade updates the sst cli but I'm currently on sst 3.0.37 is there a way to update the package to latest ion version. As stated in the docs while installing the @ion tag must be appended so calling sst@latest would install v2. Unless my TS server is wrong, when i try to add new fields recently added to some constructors it says those fields don't exist.

Is there a way to update the npm ion package without changing the version number manually?

**Comment by thdxr** [comment]
I'm a bit confused because there shouldn't be anything different about this vs other packages.

The latest version published to npm tagged under `sst@ion` includes BOTH the cli and the sdks so that's all you should need to update<br><br>Once updating if you run any sst command (or run sst install) everything shoudl get updated so that your ts definitions match what's latest

**Comment by yyaskriloff** [comment]
Maybe theres an issue with how i set it up. In my package.json I have "sst": "^3.0.37" a s a dependency.

```ts
 const zipQueue = new sst.aws.Queue('ZipQueue', {
      dlq: zipDLQ.arn
    })
``` 

The above code gives me a ts error 
`Object literal may only specify known properties, and 'dlq' does not exist in type 'QueueArgs'`

i ran `sst upgrade ` and `sst install` but still got this error.

**Comment by the-simian** [comment]
ok I'm also confused I *had* version 3.0.37 in my package.json but after running upgrade it changed to 0.1.12

Should the version we see in the CLI match the version in package json? as of a few hours ago now it does, but yesterday and all the time preceding it was as @yyaskriloff says, ^3.0.37


However I am *now* getting a warning that I wasn't before:
```
❯ sst upgrade
Warning: You are using a global installation of SST but you also have a local installation specified in your package.json. The local installation will be used but you should typically run it through your package manager.
✔︎  Already on latest 0.1.12
```

what should all this stuff be? should it all be 0.1.12? do we run like `sst upgrade` or `bunx sst upgrade`? whats most correct? everything does seem to be working, but I came across this issue because I was also confused about what package.json should be saying

**Comment by iamandrewluca** [comment]
@the-simian 3.0.37 it's not a `ion` version. And upgrade it seems it upgrade to `ion` tag version

**Comment by the-simian** [comment]
@iamandrewluca so in the cli if I did `sst version` I'd see the 0.x.xxx versions. these used to be like 0.0.547 until the recent 0.1.x versions. However, in the package.json I saw version 3.0.37 just as the others said. this was installing using the `@ion` tag. Today I did an upgrade and the package.json changed too. 

So should the package.json and the cli  both show 0.1.12 currently? was 3.0.37 never supposed to be in there? This is what I'm trying to sort out. It was somehow working with 3.0.37 for months in the devDependencies.

**Comment by iamandrewluca** [comment]
For me now both versions are showing 0.1.12

**Comment by yyaskriloff** [comment]
```
aaronskriloff@Aarons-Mac-Studio % sst upgrade
✔︎  Upgraded 0.1.10 ➜ 0.1.12
aaronskriloff@Aarons-Mac-Studio% sst version
0.1.10
```

Now I'm getting this

**Comment by iamandrewluca** [comment]
I usually run the install script again to install the last version.

```
curl -fsSL https://ion.sst.dev/install | bash
```

**Comment by yyaskriloff** [comment]
The comment above should probably be a diffrent issue because it seems to be an issue with the cli tool not the js package which is the original problem i was having.

**Comment by yyaskriloff** [comment]
installed it with homebrew

**Comment by iamandrewluca** [comment]
For me homebrew was creating some other problems, so I went with `curl` always.

**Comment by the-simian** [comment]
I also used `curl -fsSL https://ion.sst.dev/install | bash` but then was doing `sst upgrade` daily to stay up to date.

**Comment by yyaskriloff** [comment]
now that I used `curl -fsSL https://ion.sst.dev/install | bash` I'm getting the warning about global installations

**Comment by the-simian** [comment]
@yyaskriloff what do you see in package.json? is it still 3.0.37 or did it change?

**Comment by yyaskriloff** [comment]
it's 0.1.12 but i ran `pnpm i sst@ion` to make that change

**Comment by yyaskriloff** [comment]
am i not supposed to have sst as a local dependency because when i remove it the warning goes away?

**Comment by the-simian** [comment]
@yyaskriloff running sst update is currently updating the package.json now, I saw it advance today to 0.1.17 You can probably close this issue

**Comment by iamandrewluca** [comment]
Probably this fixed it https://github.com/sst/ion/commit/38c28933386dee43da557be58812933a5bc9df5f

**Comment by yyaskriloff** [comment]
@the-simian Nothings changed by me. I believe I'm having the same issue as #737 so I'm gonna close this issue
