### ISSUE TITLE
sst.vercel.dns fails to set apex domain record

### ISSUE THREAD

**Issue by klaemo** [sst/ion#744]
I wanted to assign a domain to my production deployment, but it failed with the following error:

```
Error creating DNS Record: Could not create DNS Record, unexpected error: invalid_name - Please specify a name or use an ALIAS Record instead, if you're attempting to set a CNAME value for the apex domain.
```

Makes sense because it generated the following record. Vercel's DNS doesn't like that:

```ts
{
  domain: 'my-domain.de',
  type: 'CNAME',
  name: '',
  value: 'd34xxxxxxxbev.cloudfront.net',
  teamId: undefined,
  ttl: 60
}
```

A transform to an `ALIAS` record fixed it.
```ts
domain: {
  name: "my-domain.de",
  dns: sst.vercel.dns({
    domain: "my-domain.de",
    transform: {
      record(record) {
        if (record.name === "" && record.type === "CNAME") {
          record.type = "ALIAS"
        }
      },
    },
  }),
}
```

I think this could/should be done by default in `sst.vercel.dns` when `record.name === args.domain`.

**Comment by fwang** [comment]
Fixed https://github.com/sst/ion/commit/55524f5d6697d62f813e6d66ff6da270cd1cf4a3

**Comment by klaemo** [comment]
I'm not sure this is fixed. I removed the `transform` I had in place, deployed and now the `ALIAS` record is gone and my site is broken.

`SST ❍ ion 0.1.93`

It looked like it created an alias record, but it doesn't exist in the my vercel dns records
```
|  Created     Frontend sst:aws:Remix → FrontendCdnALIASRecordMyDomainde vercel:index:DnsRecord
|  Deleted     Frontend sst:aws:Remix → FrontendCdnCNAMERecordMyDomainde vercel:index:DnsRecord
```

**Comment by klaemo** [comment]
Okay, so I removed the custom domain from the sst config and deployed. Then re-added it, but first got the following error:

```
✕  Failed
   Frontend sst:aws:Remix → FrontendCdnDistribution aws:cloudfront:Distribution
   updating urn:pulumi:production::neugekocht::sst:aws:Remix$sst:aws:CDN$aws:cloudfront/distribution:Distribution::FrontendCdnDistribution: 1 error occurred:
                                                                                                                             
   CloudFront: UpdateDistribution, https response error StatusCode: 400, RequestID: dcb78a2b-c18b-432c-95ea-17c81c45c9c1, IllegalUpdate: Only one viewer certificate change may be in progress at a time.
```

Ran it again a little while later and it worked. The `ALIAS` record got created. So, I guess it is working after all?!
