### ISSUE TITLE
`sst dev` ignores architecture config for lambdas 

### ISSUE THREAD

**Issue by apetta** [sst/ion#749]
I've noticed setting ` architecture: "arm64",` on a function config seems to be ignored by `sst dev` when checking the deployed lambda. However, when using `sst deploy` the architecture is correctly set on AWS for the deployed lambda.

**Comment by arpadgabor** [comment]
I think this is intended. In dev mode lambdas run on your local machine and what sst deploys into the cloud is a basically a "proxy" to your local machine (it actually uses AWS IoT Core to forward lambda invocations to your local machine if I'm not mistaken).

**Comment by jayair** [comment]
Yeah we mention this in the docs: https://ion.sst.dev/docs/live/

<img width="792" alt="Screenshot 2024-07-26 at 5 46 39 PM" src="https://github.com/user-attachments/assets/6e8dd5df-5409-4ed4-91c8-6f105c0baa49">

**Comment by apetta** [comment]
Thanks guys 👍
