### ISSUE TITLE
Error: [Secret variable] is not linked

### ISSUE THREAD

**Issue by f1lander** [sst/ion#751]
I have a problem with sst secrets, I deployed the app to prod, no errors but when this loads, it says the error about the secret is not linked.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/a930fa43-ff3b-427f-b4bc-8db2da91f6e0">

 my sst config file
 
 ```typescript
 /// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: 'drosera',
      removal: input?.stage === 'production' ? 'retain' : 'remove',
      home: 'aws',
      providers: { aws: true },
    };
  },
  async run() {
    const WalletConnectionProjectId = new sst.Secret('WalletConnectionProjectId');
    const AlchemyApiKey = new sst.Secret('AlchemyApiKey');
    const bucket = new sst.aws.Bucket("DroseraBucket", {
      public: true,
    });
    new sst.aws.Nextjs('Drosera', {
      link: [WalletConnectionProjectId, AlchemyApiKey, bucket],
    });
  },
});

```

**Comment by jayair** [comment]
And you set the secret for the prod as well `sst secret set --stage prod`?

**Comment by thdxr** [comment]
this is a nextjs thing - you cannot use serverside code on the frontend<br>if you would like to pass information to the frontend you need to do it through an environment variable prefixed `NEXT_PUBLIC_`

**Comment by f1lander** [comment]
> And you set the secret for the prod as well `sst secret set --stage prod`?

Yes sir

**Comment by f1lander** [comment]
> this is a nextjs thing - you cannot use serverside code on the frontendif you would like to pass information to the frontend you need to do it through an environment variable prefixed `NEXT_PUBLIC_`

So sorry I was OOO, I ended doing this

```typescript
async run() {
    const WalletConnectionProjectId = new sst.Secret(
      'WalletConnectionProjectId',
    );
    const AlchemyApiKey = new sst.Secret('AlchemyApiKey');
    const bucket = new sst.aws.Bucket('DroseraBucket', {
      public: true,
    });
    new sst.aws.Nextjs('Drosera', {
      link: [WalletConnectionProjectId, bucket],
      domain: {
        name: 'app.devnet.drosera.io',
        dns: sst.cloudflare.dns(),
      },
      environment: {
        NEXT_PUBLIC_WALLET_CONNECTION_PROJECT_ID:
          WalletConnectionProjectId.value,
        NEXT_PUBLIC_ALCHEMY_API_KEY: AlchemyApiKey.value,
      },
    });
  },
```

setting the secrets values using the `sst secret add` and access to them in the run method and then set the values in the environment prop in the nextjs app instance, I was trying access in the code itself as thedocs says.

```
import { Resource } from "sst";

console.log(Resource.MySecret.value);
```

and I could access but when the problem was when I deploy tell me the resources is not linked as you see the error.

@thdxr
