### ISSUE TITLE
 SST 0.1.42: sst dev errors after updating

### ISSUE THREAD

**Issue by South-Paw** [sst/ion#764]
Updating installed version of SST to 0.1.42 and now running the following command that used to work

```bash
sst dev "npm run dev:web"
```

just returns the following error

```
Ensure `sst dev` session is running where you sst.config.ts is. If you do not want to use the multiplexer you can start `sst dev --mode=basic` instead.
```

- Project is a npm workspaces monorepo
- The `sst.config.ts` is at the root of the project where the command is being run
- `npm run dev:web` runs `vite` within the `packages/web` folder
- Adding `--mode=basic` returns the same error

According to all the docs, this command should still work as expected - right?

**Comment by South-Paw** [comment]
Nit: There is also a typo in the error

"Ensure `sst dev` session is running where you`r` sst.config.ts is."

**Comment by rnnyrk** [comment]
I encounter the same issue. Just following a long with the docs, but unable the run the project. `sst init` creates the `sst.config.ts` file, but unable to run the project locally

**Comment by benjamindell** [comment]
I'm also seeing the same issue. Completely stuck... not sure what to do from here.

**Comment by ThomSMG** [comment]
Related to discussion in discord: https://discord.com/channels/983865673656705025/1177071497974648952/1266395036871032902

**Comment by rnnyrk** [comment]
@ThomSMG Not sure what I'm missing? 

<img width="994" alt="Screenshot 2024-07-26 at 17 04 43" src="https://github.com/user-attachments/assets/3e8b9474-45fa-48ea-bc15-71101bf56ef5">

**Comment by thomasklein** [comment]
@rnnyrk there seem to be [several causes](https://hatchjs.com/npx-could-not-determine-executable-to-run/) why npx returns you that error.  
I have sst ion installed globally via `curl -fsSL https://ion.sst.dev/install | bash` as well as a project dependency `"sst": "ion"`. If you don't have it like that, you could try matching it and retry `npx sst dev`

**Comment by LukasMurdock** [comment]
Started seeing the

```
Ensure `sst dev` session is running where you sst.config.ts is. If you do not want to use the multiplexer you can start `sst dev --mode=basic` instead.
```

error in [0.1.32](https://github.com/sst/ion/releases/tag/v0.1.32). Moving back to 0.1.29 seems to resolve.

**Comment by klaemo** [comment]
Make sure to remove `sst dev` from your `dev` script in `package.json`. The new multiplexer does that for you. So, you want your `package.json#scripts` to look something like this

```json
"scripts": {
  "dev": "vite dev"
}
```

and not like this

```json
"scripts": {
  "dev": "sst dev vite dev"
}
```

**Comment by benjamindell** [comment]
Oh, thats interesting @klaemo. The sst setup wizard auto added "sst dev" to the dev script. But we should remove it?

**Comment by LukasMurdock** [comment]
In my case I needed to update the dev script in `package.json` as @klaemo pointed out.

Then I started getting this error when running `npm run dev`

```
It does not look like SST links are active. If this is in local development and you are not starting this process through the multiplexer, wrap your command with `sst dev -- <command>`
```

It seems instead of running `npm run dev` you now start by running `npx sst dev`

**Comment by klaemo** [comment]
> Oh, thats interesting @klaemo. The sst setup wizard auto added "sst dev" to the dev script. But we should remove it?

Yes, that's correct. Recent sst versions (they iterate quickly 😅) might've already fixed that. 

> It seems instead of running `npm run dev` you now start by running `npx sst dev`?

That's correct!

**Comment by jayair** [comment]
Yeah I'm still updating the docs but yeah `npx sst dev` if you have `sst@ion` in your `package.json`. I updated all the quick starts. Here's an example: https://ion.sst.dev/docs/start/aws/api/

**Comment by mkysft** [comment]
Running into the same issue as @LukasMurdock .

```
sdk-v2/provider2.go:385 sdk.helper_schema: error creating worker script: Uncaught Error: It does n
ot look like SST links are active.
```
My worker script has a "link" to a Cloudflare D1 component so I guess that's what it's referring to but it's a pretty simple setup. Not sure what the issue is all of a sudden.

```typescript
export default $config({
  app(input) {
    return {
      name: "creative-app-name",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "cloudflare",
    };
  },
  async run() {
    const db = new sst.cloudflare.D1("DB");

    const api = new sst.cloudflare.Worker("API", {
      handler: "packages/api/index.ts",
      link: [db],
      url: true,
    });

    new sst.cloudflare.StaticSite("WEB", {
      environment: {},
      build: {
        command: "yarn run build",
        output: "packages/web/dist",
      },
    });

    return {
      API: api.url,
      DB: db.id,
    };
  },
});
```

**Comment by Thourum** [comment]
> Yeah I'm still updating the docs but yeah `npx sst dev` if you have `sst@ion` in your `package.json`. I updated all the quick starts. Here's an example: https://ion.sst.dev/docs/start/aws/api/

I recently upgraded sst package in our mono repo with 4 apps, lambda functions, Postgres, etc.. And I was getting this error:
```
✕  You are currently trying to run a frontend or some other process on its own - starting from sst v0.1.32 `sst dev` can bring up all of the processes in your application in a single window. Simply run `sst dev` in the same directory as your `sst.config.ts`. If this is not clear check out the monorepo example here: https://github.com/sst/ion/tree/dev/examples/aws-monorepo

   If you prefer running your processes in different terminal windows, you can start just the deploy process by running `sst dev --mode=basic` and then bring up your process with `sst dev -- <command>` in another terminal window.
```

So it's no longer possible to run a single app in monorepo with local db, instead we have to start `sst dev` and recreating the whole infrastructure? Is there a workaround?

**Comment by benjamindell** [comment]
Argh, now suddenly i'm getting this error:

```
Error: It does not look like SST links are active. If this is in local development and you are not starting this proce
ss through the multiplexer, wrap your command with `sst dev -- <command>`
```

My package 'dev' entry is "dev": "next dev" and i run sst via "npx sst dev"

What am i doing wrong?

**Comment by benjamindell** [comment]
> Argh, now suddenly i'm getting this error:
> 
> ```
> Error: It does not look like SST links are active. If this is in local development and you are not starting this proce
> ss through the multiplexer, wrap your command with `sst dev -- <command>`
> ```
> 
> My package 'dev' entry is "dev": "next dev" and i run sst via "npx sst dev"
> 
> What am i doing wrong?

I discovered that the issue is that i was trying to access a secret (via Resource.AuthSecret.value) in my nextjs middleware.ts file. Hard coding it to a string (for testing purposes) removes the error quoted above. I need to be able to access secrets in teh middleware though, so if i'm investigating that next. Hopefully the docs mention this somewhere...

**Comment by rnnyrk** [comment]
> @rnnyrk there seem to be [several causes](https://hatchjs.com/npx-could-not-determine-executable-to-run/) why npx returns you that error. I have sst ion installed globally via `curl -fsSL https://ion.sst.dev/install | bash` as well as a project dependency `"sst": "ion"`. If you don't have it like that, you could try matching it and retry `npx sst dev`

I've installed sst as mentioned above. After that I got a AWS credentials error. I had credentials in my `.env` file, but apparently that wasn't working either. Add an `~/.aws/credentials` and run `sst dev` (without an npm script) and now I got it working

**Comment by thdxr** [comment]
if you run this again it should give you a more descriptive error.<br><br>this started happening because we introduced the multiplexer - i would update to latest and just try running `sst dev` in the root of your application and wait for it to finish - you might find it automatically does everything you need<br><br>check docs here for cutomization or opting out of it: [https://ion.sst.dev/docs/reference/cli/#flags-1](https://ion.sst.dev/docs/reference/cli/#flags-1)

**Comment by South-Paw** [comment]
Thanks @thdxr

**Comment by Meeeeez** [comment]
I am still getting the Error: It does not look like SST links are active. If this is in local development and you are not starting this proce
ss through the multiplexer, wrap your command with `sst dev -- <command>`. I have a turborepo with a nextjs app where sst is installed in drop in mode. When i access a linked api in my nextjs app with Resources.Api.url this error occurs. I am starting the app with npx sst dev in the nextjs project.

**Comment by jayair** [comment]
@Meeeeez can you open a new issue with steps to reproduce?

**Comment by Meeeeez** [comment]
> @Meeeeez can you open a new issue with steps to reproduce?

I figured out what was wrong: 

The error occurs if i have hyphens in my resource names.
