### ISSUE TITLE
Replace OAI with OAC for S3 origin in CloudFront Distribution

### ISSUE THREAD

**Issue by garysassano** [sst/ion#766]
Ion currently utilizes the legacy Origin Access Identity (OAI) method for [restricting access to an S3 origin](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html).

Prior to 1.0 release, it would be beneficial to [migrate to the more modern Origin Access Control (OAC)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#migrate-from-oai-to-oac) approach.

**Comment by fwang** [comment]
Fix in https://github.com/sst/ion/commit/f9c580005d7daf378b0773dbcc4a11cce72cee9d

Will be in the next release.
