### ISSUE TITLE
Flaky Deployments: Sometimes fail due to 'x-amz-content-sha256' header mismatch

### ISSUE THREAD

**Issue by janus-reith** [sst/ion#772]
Sometimes the deployment fails with:

```
Failed    
SomeName sst:aws:Nextjs → SomeNameAssetFiles sst:aws:BucketFiles
The provided 'x-amz-content-sha256' header does not match what was computed.
```

It doesn’t happen constantly and subsequent deployment succeed.
Something seems to be flaky - Maybe that header is computed at a time where the build process still changes files?

**Comment by fwang** [comment]
We made some changes to building `Nextjs` this week. Can you update to the latest version and see if the issue still happens?

^ to add some context, `Nextjs` builds the app to `.open-next` (using OpenNext), and the files get uploaded after the build completed. Is there's another build process happening at the same time?

**Comment by janus-reith** [comment]
I seems like it  was fixed in some more recent versions of ion, at least it doesn’t occur anymore. I can’t pinpoint which release it was.

No, there should not be a separate build  affecting the .open-next  folder. An Astro site is part of the same stack, but they are both in separate folders and I believe their builds run sequentially so I don’t think it would affect that.

I manually had specified the latest open/next version 3.0.8 instead of 3.0.2 which was the default at the time of opening, so the fix must’ve been somewhere within Ion. Glad it is resolved :)
