### ISSUE TITLE
No resource plugin 'pulumi-resource-aws' found

### ISSUE THREAD

**Issue by Firdaus-prog** [sst/ion#774]
Hi, im pretty new with sst ion, just about a month into it. it's working fine till today. This morning when I do the  `sst deploy --stage=development`, I get this error:

`SST ❍ ion   ready!

➜  App:        omni-sales
   Stage:      uizwmuha

~  Deploy

|  Error       default_6_47_0 pulumi:providers:aws
|  no resource plugin 'pulumi-resource-aws' found in the workspace at version v6.47.0 or on your $PATH

✕  Failed    
   default_6_47_0 pulumi:providers:aws
   no resource plugin 'pulumi-resource-aws' found in the workspace at version v6.47.0 or on your $PATH`

**Comment by Firdaus-prog** [comment]
UPDATE: i notice there's a problem with latest ion version 0.1.56 after the pulumi v6.47.0 update 3 days ago. we revert out ion version to 0.1.51 and everything works fine. Is it the right way to approach it?

**Comment by Firdaus-prog** [comment]
@penzur try checking your version with `sst version`. I'm downgrading mine using this `curl -fsSL https://ion.sst.dev/install | VERSION=0.1.51 bash`.

**Comment by penzur** [comment]
@Firdaus-prog that's what I did. Did you make some changes to your CI/CD build config before running it with the reverted version?

**Comment by Firdaus-prog** [comment]
This is in my pipeline:
`- npm ci
          - mkdir -p ~/.aws
          - curl -fsSL https://ion.sst.dev/install | VERSION=0.1.51 bash
          - source /root/.bashrc
          - echo -e "[default]\naws_access_key_id =
            $AWS_CENTRAL_ACCESS_KEY_ID\naws_secret_access_key =
            $AWS_CENTRAL_SECRET_ACCESS_KEY" > ~/.aws/credentials
          - echo -e "[profile ads-dev]\nrole_arn = SOMEVALUE
            = default" > ~/.aws/config
          - export AWS_DEFAULT_PROFILE=ads-dev
          - export AWS_SDK_LOAD_CONFIG=1
          - export AWS_DEFAULT_REGION=us-east-1
          - sst secret set ClientId
            SOMEVALUE
          - sst secret set ClientSecret
            SOMEVALUE
            --stage=development
          - sst version
          - sst deploy --stage=development`

**Comment by FaisterCarvalho** [comment]
I managed to avoid the issue by manually downgrading `node_modules/sst-linux-x64/bin/sst` to the `v0.1.54` binary I downloaded from here: https://github.com/sst/ion/releases/tag/v0.1.54

**Comment by Firdaus-prog** [comment]
Issue Fixed with ion V0.1.64
