### ISSUE TITLE
NextJs in ion doesn't have a timeout property

### ISSUE THREAD

**Issue by benjamindell** [sst/ion#779]
The LambdaTimeoutError error is being triggered in my NextJs app. Looking at SST v2 I notice that there's a timeout property i can set on the NextjsSite object, but there doesn't seem to be an equivalent property on the ion NextJs object. Is there a reason for this or is it due to be added soon by any chance?

**Comment by benjamindell** [comment]
Ahh i realised this is something you can update via the transform construct. For anyone else needing help with this, here's the transform entry you need to add to your Nextjs() initialisation.

```
transform: {
    server: {
        timeout: "40 seconds",
    },
},
```

**Comment by nyacg** [comment]
Just spotted this also :/

**Comment by intersean** [comment]
Did you all confirmed this works. I checked all my lambdas after deploy and non of them updated with either

```
const web = new sst.aws.Nextjs("MyWeb", {
      transform: {
        function: {
          timeout: "3 minutes",
        },
      },
```

or 

```
const web = new sst.aws.Nextjs("MyWeb", {
      transform: {
        sever: {
          timeout: "3 minutes",
        },
      },
```

**Comment by jayair** [comment]
I'll try it out.

**Comment by jayair** [comment]
Tested this

```
new sst.aws.Nextjs("MyWeb", {
  transform: {
    server: {
      timeout: "1 minute",
    },
  },
});
```

It works.

<img width="488" alt="Screenshot 2024-10-05 at 4 51 32 PM" src="https://github.com/user-attachments/assets/0266e727-5fd1-4485-ac23-3269d3ef5ec3">

**Comment by sshadmand** [comment]
> Tested this
> 
> ```
> new sst.aws.Nextjs("MyWeb", {
>   transform: {
>     server: {
>       timeout: "1 minute",
>     },
>   },
> });
> ```
> 
> It works.
> 
> <img alt="Screenshot 2024-10-05 at 4 51 32 PM" width="488" src="https://private-user-images.githubusercontent.com/53023/373907174-0266e727-5fd1-4485-ac23-3269d3ef5ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjY5MDcsIm5iZiI6MTcyODI2NjYwNywicGF0aCI6Ii81MzAyMy8zNzM5MDcxNzQtMDI2NmU3MjctNWZkMS00NDg1LWFjMjMtMzI2OWQzZWY1ZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAyMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NjE1NGEyMGYzMGJkNzE5ZDYyODVkMWIyZTg0NTliYjI3ZTM3MmRkM2FmMzk1NGYyYTU5NmFkOTk1YTRmNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xqOcTv925jU4q-M0J7JQ2Cza13ZEg0XEV3eFZZIl21M">

Confirmed works for me now as well.  Thanks.
