### ISSUE TITLE
Can I use local AWS resources?

### ISSUE THREAD

**Issue by pablote** [sst/ion#786]
Can I point SST to a local DynamoDB instance using Amazon's [dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local) docker image? Same question for say an S3 bucket running locally using [LocalStack](https://www.localstack.cloud/)? Or is this always expected to run against AWS?

thanks

**Comment by thdxr** [comment]
sst is designed around the idea that you get a mostly fully copy of your stuff in your aws account (for resources that scale to $0)<br><br>ultimately getting that to work with localstack has a lot of challenges so this isn't something we're likely going to support
