### ISSUE TITLE
Operation error SSM when running sst dev

### ISSUE THREAD

**Issue by brapifra** [sst/ion#792]
When running `sst dev` in the latest version (0.1.64), I get the following error when SST tries to run my next.js app locally:

```
Error initializing aws:                                                                                                                                                                                         
operation error SSM: GetParameter, https response error StatusCode: 400, RequestID: 15121642-ee5d-459d-bca1-c3f763315863, api error AccessDeniedException: User: arn:aws:sts::USER:assumed-role/project-stage-WebDevServerRole-useast1/sst-dev is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:975050252324:parameter/sst/bootstrap because no identity-based policy allows the ssm:GetParameter action 
```

However, if I downgrade to `0.1.29` (before the new UI was the default), it works fine!

**Comment by thdxr** [comment]
your aws credential does not have permission to read SSM values - this is required for sst to start

**Comment by brapifra** [comment]
But how come is this working in previous versions but not in the latest one? Also, shouldn't a user with AdministratorAccess be enough? @thdxr 

![image](https://github.com/user-attachments/assets/3fc91179-43ea-4c59-bf21-f5318b76ab81)

**Comment by brapifra** [comment]
Yeah, I'm 100% sure this is a bug @thdxr 

I've now been able to make it work by running `sst dev --mode=basic` and `sst dev -- next dev` in a separate tab with the **latest version**

But again, if I run `sst dev` normally with the latest version, I get the SSM error mentioned above.

**Comment by ThomSMG** [comment]
Same here. I upgraded to sst 0.1.76 and it started happening.

**Comment by blakegreendev** [comment]
Also seeing this error with AdminAccess on the profile I'm authenticating with

**Comment by brapifra** [comment]
Okay so it seems that this was caused by having `sst dev` as the dev script in my package.json. Changing it to `next dev` makes everything work:
![image](https://github.com/user-attachments/assets/ebf6fe95-f5b9-4ff5-9e6e-f2ba5b4e0cb5)

**Comment by thdxr** [comment]
^ thanks for posting here - i updated the error message in v0.1.77 to help make this more clear

**Comment by jjongsma-provi** [comment]
Also running into this with 0.1.77 - Expired token error from SSM client. Downgrading to .64 (the last version that worked without errors for me) fixed it. It's not an actual IAM permission issue, seems to be something in SST.

**Comment by jayair** [comment]
Let me check.

**Comment by thdxr** [comment]
@jjongsma-provi do you have `sst dev` in a package.json script?
