### ISSUE TITLE
Resource option retainOnDelete not working on sst.aws.Postgres

### ISSUE THREAD

**Issue by chrisandrewcl** [sst/ion#805]
I have ion config set to `retain` on removal and explicitly set `retainOnDelete: true` in `sst.aws.Postgres`, but it was removed anyway in a deployment update, so ion doesn't seem to be forwarding it to the underlying pulumi resource. 

\* As a workaround, it should be possible to set it via transform (with `finalSnapshotIdentifier` for good measure), but I still need to test it.

**Comment by fwang** [comment]
Fixed here https://github.com/sst/ion/commit/643fd4e80039fab4a6cf984a65eeee31c03e90d9

Will be in the v0.1.87 release.

Thanks @chrisandrewcl!
