### ISSUE TITLE
sst remove fails to delete AWS EventBus

### ISSUE THREAD

**Issue by brendankerrison** [sst/ion#809]
When setting up an EventBus with something like:

```
    const eventBus = new sst.aws.Bus("Bus");
    eventBus.subscribe({
      handler: "src/myhandler.handler",
      link: [email],
    }, { 
      pattern: {
        // source is the app name and app stage
        source: [`${$app.name}.${$app.stage}`],
        detailType: ["myevent"],
      }
     });
```

Running `sst remove` throws this error:

```
×  Failed
   Bus sst:aws:Bus → BusBus aws:cloudwatch:EventBus
   EventBridge: DeleteEventBus, https response error StatusCode: 400, RequestID: 00c020d6-a364-4291-9a7c-101780d57fee,
error ValidationException: EventBus can't be deleted since it has rules.
```

I am on:
```
❯ sst version
0.0.467
```

**Comment by fwang** [comment]
hmm.. if u run `sst remove` again, does the bus get removed successfully?

**Comment by brendankerrison** [comment]
Yes.

Strangely when I redeployed and then removed again it did not repeat the issue 🤷

**Comment by fwang** [comment]
It sounds like a timing issue. The bus rules are always removed before the bus gets removed. But there's a chance the bus still sees the rules (due to eventual consistency).

If more ppl run into this, we need to figure out a workaround.
