### ISSUE TITLE
fetch failed error during deploys

### ISSUE THREAD

**Issue by mbhoward73** [sst/ion#814]
We're intermittently seeing the following error during deploys

|  Error       Web sst:aws:SvelteKit → WebCdnWaiter sst:aws:DistributionDeploymentWaiter
|  fetch failed

✕  Failed    
   Web sst:aws:SvelteKit → WebCdnWaiter sst:aws:DistributionDeploymentWaiter
   fetch failed

**Comment by joshwils82** [comment]
I'm seeing this as well.

**Comment by thdxr** [comment]
what version of sst is this?

**Comment by thdxr** [comment]
also does it fail immediately? or after some time

**Comment by mbhoward73** [comment]
we're running sst 0.1.80.  when it fails, it always fails after some time.  5+ minutes approximately.  maybe we're hitting some sort of timeout?  it's intermittent but we are seeing it fairly frequently.  it happened 3 times in a row on CI builds recently.

**Comment by thdxr** [comment]
this is fixed as of [v0.1.89](https://github.com/sst/ion/releases/tag/v0.1.89) - turns out nodejs native fetch has a 5min timeout that isn't modifiable (wtf?) <br><br>we switched to using the `http` module and it works now

**Comment by mbhoward73** [comment]
awesome, thanks.  we just upgraded to 0.1.90.  I'll let you know if we see it again.
