### ISSUE TITLE
set secret command sets secret for incorrect stage

### ISSUE THREAD

**Issue by bachiitter** [sst/ion#816]
When attempting to set a secret for the 'dev' stage using the SST CLI, the secret is incorrectly being set for the 'bachitter' stage instead. This occurs despite explicitly specifying the 'dev' stage in the command.

`sst secret set AuthKey --"$(cat key.txt)" --stage dev`
   
`✓  Set "AuthPublicKey" for stage "bachitter". Run "sst deploy" to update.`

Expected Behavior:
The secret 'AuthKey' should be set for the 'dev' stage.

Actual Behavior:
The secret 'AuthKey' is set for the 'bachitter' stage instead of the 'dev' stage.

**Comment by thdxr** [comment]
if you do the double — it will not forward the args after that<br><br>you can actually do `sst secret set --stage=dev < key.txt`

**Comment by bachiitter** [comment]
> if you do the double — it will not forward the args after that<br><br>you can actually do `sst secret set --stage=dev < key.txt`

got it thanks
