### ISSUE TITLE
Go error when running dev mode

### ISSUE THREAD

**Issue by mattalco** [sst/ion#818]
I recently updated my SST CLI to `0.1.80` from `0.1.2`. When running the frontend portion of one of my projects, I receive the following error. I don't see any relevant info in the logs regarding this error, but can provide those too if it would be helpful.

`level=ERROR msg="exited with error" err="json: cannot unmarshal number into Go value of type map[string]string"`

![Screenshot 2024-08-06 at 10 37 15](https://github.com/user-attachments/assets/164c6553-146b-41e2-a673-e87f1355c056)

**Comment by thdxr** [comment]
do you have a primary `sst dev` terminal up? when it's up can you hit `http://localhost:13557/api/env?directory=path/to/frontend` and see what comes back?

**Comment by mattalco** [comment]
Thanks for getting back to me @thdxr.

I seem to be having some kind of bootstrap or local cache issues. Running things this morning produced the following console error and log error. It's also odd to me that version `0.1.80` is being shown here when the command line reports `0.1.87` - I only have a local version of SST so I don't think it's picking up a system wide installation from Homebrew or NPM. 

Another thing that's strange is my stage `malcorn` is what things should be running on but the mosaic console shows `malcorn2` which is an old test stage I was trying yesterday to see if a fresh stage would work.

My other projects are deploying just fine. Do you have any guidance on what steps I need to take to wipe any cache files or bootstraps. I can't find any related Buckets or Parameters in AWS and the sst folder in Application Support has been previously cleaned in an attempt to clear out any old/corrupted artifacts.

### Mosaic Console
![Screenshot 2024-08-08 at 11 00 53](https://github.com/user-attachments/assets/f395df39-30b0-4334-8c07-524d593afa3c)

### Error in sst.log
![Screenshot 2024-08-08 at 10 59 47](https://github.com/user-attachments/assets/ac438ee9-7c36-42fc-8dc0-fe9a6d7a70b5)

### SST Version
![Screenshot 2024-08-08 at 11 01 27](https://github.com/user-attachments/assets/c463a6e8-cc0d-46dd-93d2-550ae3a7b3fc)

**Comment by mattalco** [comment]
After a series of reboots and clearing some AWS items, it's back up and running! Thanks for your help here.
