### ISSUE TITLE
SST 0.1.81+, local dev, all APIs returning 500 responses, bridge.go error

### ISSUE THREAD

**Issue by South-Paw** [sst/ion#822]
Updated local install of SST to `0.1.83`

Running `sst dev` command

APIs are being invoked, but return a 500 service error response to the web app

No logs in SST CLI about the error occurring, lambdas build and are invoked

Dug through AWS, checked the specific Lambda logs and found the following:

```
  | 2024-08-08T01:25:23.439Z | 2024/08/08 01:25:23 INFO dialing lambda runtime api
  | 2024-08-08T01:25:24.457Z | panic: timed out waiting for request from sst dev
  | 2024-08-08T01:25:24.457Z | goroutine 1 [running]:
  | 2024-08-08T01:25:24.457Z | main.main()
  | 2024-08-08T01:25:24.457Z | /home/runner/work/ion/ion/platform/functions/bridge/bridge.go:69 +0x2b
  | 2024-08-08T01:25:24.460Z | RequestId: 241e55a7-b81d-40b8-ae68-9d226336b2c7 Error: Runtime exited with error: exit status 2 Runtime.ExitError
```

Looks like `bridge.go` received changes in commit 5fc4c6660cbf31731c0546cb0c1ec9da77827cd2 which was released in `0.1.81`

I have rolled back my local to SST version `0.1.80` and our APIs are now responding to the web app correctly again

**Comment by thdxr** [comment]
we added an aggressive timeout in 0.1.81 - let me try increasing it

**Comment by thdxr** [comment]
can you try v0.1.84?

**Comment by South-Paw** [comment]
Seems to work with 0.1.84

Unsure if related (or how the timing works) but a lot of our "Done" timings after Lambdas return are _very_ close to 2 seconds (1.7s - 1.962s). If these are somewhat related, then 2 seconds might still be a bit low

**Comment by arpadgabor** [comment]
@thdxr we are seeing a possibly related issue. We have some lambdas that are triggered by SQS that do some longer running jobs. Until 0.1.80 everything is fine, 0.1.81 introduced some bug that causes these lambdas to stop their execution randomly. It's completely random, the function is built (seen in logs) but then the execution stops at some point or another. We added logs to see if our code was the problem, but every time we tested it hanged somewhere else.

![image](https://github.com/user-attachments/assets/970e8529-2c51-4b5b-93a1-0d80b5682a83)

See an example above with 3 separate invocations and each doing something different. No errors.

**Comment by arpadgabor** [comment]
Yeah I managed to reproduce the bug, this code logs a number every second. My lambda is set to timeout after 30s but the bridge kills it after just 2. https://github.com/arpadgabor/sst-repros

**Comment by thdxr** [comment]
i did see something like this yesterday let me look into it deeper

**Comment by thdxr** [comment]
disabled the timeout for now in v0.1.87
