### ISSUE TITLE
`sst install --stage {stage}` not generating stage file (sst 0.1.87)

### ISSUE THREAD

**Issue by arpadgabor** [sst/ion#823]
What the title says.

**Comment by thdxr** [comment]
what do you mean by stage file? if you're referring to `.sst/stage` that will not get updated when running `sst install --stage` - it's meant to be used as the default stage when one isn't specified which is useful for local development

**Comment by arpadgabor** [comment]
Ahhh I was actually thinking of something else... I read something in the docs that --stage will generate the stage file and assumed install --stage will create the .sst folder and create the stage file with that specific stage (someone on my team tried it earlier today).

I'm tired. I'll close this.
