### ISSUE TITLE
Cannot Specify Custom Name for AppSync API

### ISSUE THREAD

**Issue by rauthf** [sst/ion#824]
Issue Description
I am encountering an issue where I am unable to specify a custom name for my AppSync API using SST/Ion. Here is a snippet of my code:

```
export const appSync = new sst.aws.AppSync(`NameA`, {
  schema: "./packages/appsync/src/graphql/schema.graphql",
  transform: {
    api: {
      name: `NameB`,
      authenticationType: "AMAZON_COGNITO_USER_POOL",
    }
  }
});
```

In the above code, I am trying to set the AppSync API name to NameB, but it does not seem to apply as expected. The API name is not reflecting the specified custom name.

Steps to reproduce:

Define the AppSync API as shown in the code snippet.
Deploy the stack using SST/Ion.
Observe the name of the deployed AppSync API.
Expected behavior:
The AppSync API should be created with the custom name specified (NameB).

Actual behavior:
The API name does not reflect the specified custom name.

I would appreciate any guidance on how to correctly specify the name of the AppSync API. Thank you.

**Comment by fwang** [comment]
Hey @rauthf, this should be [fixed recently](https://github.com/sst/ion/issues/633). Can you try the latest version?

Feel free to re-open if issue persist.

**Comment by rauthf** [comment]
I noticed that when running the live or dev deploy, the name didn't change. When I did the deploy in a 'production' environment, the name was as expected.
Maybe my local version was outdated, and in the other environment, it is always downloaded updated by the pipeline.

Thank you.
