### ISSUE TITLE
`sst dev` lambdas fail quite often

### ISSUE THREAD

**Issue by apetta** [sst/ion#828]
When running `sst dev`, any lambdas that are triggered often result in `internal server error` a few times before they start working. Then they randomly stop working after a few uses. Running `sst dev` again sometimes fixes this, but often `sst remove` and then `sst dev` is needed for it to start working again - the internal server error the first few times is always there though.

Queues with lambda handlers are also very flakey - they quite often do not trigger in `sst dev`.

Currently on `0.1.90`

**Comment by thdxr** [comment]
we changed the implementation recently, must have some issues under some scenarios i'll be looking into it today

**Comment by apetta** [comment]
@thdxr It Seems to be happening when deployed to dev staging as well.

If the lambda has to cold boot, I'm getting this randomly every now and then:
![image](https://github.com/user-attachments/assets/f435f2fc-6872-4c21-ae9c-6815b6c9adcd)

If I redeploy, it starts working for a bit but then if we come back to it later then we get the same error. Really strange, there are no modules that should be causing this as I'm lazy loading most things like DB connections, SQS connections etc. in the handler

I'm not sure on the implementation details of ion->pulumi->terraform->aws, but could this be related to loading the handler code on a fresh instance (I think it comes from S3?) or something else like this?

**Comment by apetta** [comment]
> @thdxr It Seems to be happening when deployed to dev staging as well.
> 
> If the lambda has to cold boot, I'm getting this randomly every now and then: ![image](https://private-user-images.githubusercontent.com/33671231/358018540-f435f2fc-6872-4c21-ae9c-6815b6c9adcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzQ0MDMsIm5iZiI6MTcyMzY3NDEwMywicGF0aCI6Ii8zMzY3MTIzMS8zNTgwMTg1NDAtZjQzNWYyZmMtNjg3Mi00YzIxLWFlOWMtNjgxNWI2YzlhZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyMjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTM2NmZlOWNlZjViZTYyYmMwMzJhMmYxYmY3NGMxNDgwNzEwMzc0ZTcwYWY5ZjllYWYwM2Q3MDI3OTVmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dyrq8w9RmOCxxgeuRXaTe_IPPjuwwCFhMa0Cpqa1ZVc)
> 
> If I redeploy, it starts working for a bit but then if we come back to it later then we get the same error. Really strange, there are no modules that should be causing this as I'm lazy loading most things like DB connections, SQS connections etc. in the handler
> 
> I'm not sure on the implementation details of ion->pulumi->terraform->aws, but could this be related to loading the handler code on a fresh instance (I think it comes from S3?) or something else like this?

Ok so this might be because there's a VPC on the lambda, and I had a public subnet applied to the lambda instead of just the private subnets ([see discussion](https://stackoverflow.com/questions/51373609/why-aws-lambda-functions-in-a-vpc-sometimes-timeout-and-sometimes-work-fine)). Will report back to see if this was the issue!

**Comment by apetta** [comment]
Can confirm that this was a VPC issue as per above. Sorry!
