### ISSUE TITLE
Feature: Allow direct use of sst.aws.Cdn

### ISSUE THREAD

**Issue by ian-pascoe** [sst/ion#831]
It would be cool to leverage the Cdn object you have for fronting objects in S3.

The sst.aws.Cdn object is marked as internal only and I have run into issues when I try to use it for the above use case.

Request is to make it public and documented so that users can create their own Cdn objects with custom domains.

**Comment by ian-pascoe** [comment]
The reason is that cert management and domains for the default pulumi distribution object is annoying and it seems like this object already has that figured out.

**Comment by fwang** [comment]
I hear u!

For now, u can use the `Router` component and transform on  the `cdn` https://ion.sst.dev/docs/component/aws/router/#transform-cdn

**Comment by ian-pascoe** [comment]
@fwang - That is my current workaround. Def don't love that it's calling a lambda every time! But I'll take it for now.

**Comment by fwang** [comment]
Releasing v3.1.10 with `Router` routing directly to s3 bucket.

Here's an example https://github.com/sst/ion/blob/dev/examples/aws-router-bucket/sst.config.ts
