### ISSUE TITLE
ability to copy output from console in dev mode

### ISSUE THREAD

**Issue by mbhoward73** [sst/ion#836]
it would be nice if we could copy output from the console in dev mode.  I'm running in linux and I've tried all the usual copy commands but I can't seem to get selected output into the clipboard.  one use case for this is when I'm looking at a long unformatted json string and I want to copy to another window and format it so it's more human readable

**Comment by jayair** [comment]
Are we talking about the CLI? Because of the multiplexer copy is implemented a little differently. If you click-drag and highlight some text, it should copy that to you clipboard. Give that a try?

**Comment by mbhoward73** [comment]
I'm talking about the console where the output of my functions go when running sst dev (screen shot # 1).  Click-drag and highlighting some text doesn't copy to the clipboard.  When I select something I see that the console prompts me to hit enter to copy (screen shot # 2) but hitting enter also doesn't copy to the clipboard.  I'm running wayland but my colleague is seeing the same thing on x11.

![sst_console1](https://github.com/user-attachments/assets/6c4d2c4e-8f59-4456-9d27-b945b9941faa)
![sst_console2](https://github.com/user-attachments/assets/dc024cf1-9745-4bad-ad36-fef6ec7c86d0)

**Comment by thdxr** [comment]
what terminal is this? we might need to handle it specially if it doesn't handle OSC52 codes

**Comment by mbhoward73** [comment]
I'm using terminator on ubuntu with wayland
https://gnome-terminator.org/

My colleague who is seeing the same issue is using ST on arch with X11
https://st.suckless.org/

**Comment by thdxr** [comment]
unfortunately seems like that terminal does not support OSC52: [https://gitlab.gnome.org/GNOME/vte/-/issues/125](https://gitlab.gnome.org/GNOME/vte/-/issues/125)<br><br>would suggest a more modern terminal or stick with `sst dev --mode=basic`
