### ISSUE TITLE
Using a custom domain with Nextjs

### ISSUE THREAD

**Issue by this-fifo** [sst/ion#838]
Hi there, thank you for this awesome framework! I use it in lots of projects and like it a lot.

For the first time in my projects I've needed to deploy a Nextjs site using a custom domain that is registered with Namecheap and not available in Route 53.

I am trying to follow the documentation here https://ion.sst.dev/docs/custom-domains/ but I am a little confused, would appreciate more guidance and advice. 🙏

1. Validate domain ownership in AWS
This step feels straightforward, it links to AWS' documentation.

2. Set the certificate ARN as the `cert` and set `dns` to `false`.
Straightforward again.

3. Add the DNS records in your provider to point to the CloudFront distribution, API Gateway, or load balancer URL.
This part is where I need help. 🙇‍♂️

Since I haven't deployed anything yet, and this is a new project, how would I know the CloudFront distribution ahead of time? Isn't this created by the deployment? It felt like a cyclical dependency step and I got lost. (Apologies if my question sounds naive, I am new to this)

Thank you!

**Comment by fwang** [comment]
hey @this-fifo, step 3 is done after the site is deployed.

**Comment by ekasprzyk** [comment]
@this-fifo  We do this as part of our flow and it just means making an API call to your DNS provider(e.g. Cloudflare in our case) and saying "link the URL of the cloudfront distribution to this url".  You'll need the URL of the just deployed site.

**Comment by this-fifo** [comment]
Thank you so much everyone, that worked! I don't know why but I was under the impression the deployment would fail and I wouldn't be able to obtain the CloudFront distribution url.

As a minor feedback, I did had the deployment fail a couple times because the certificate could not be found and was going bananas here until I realize that the tutorial had a separate section that stated the certificate must be created in **us-east-1** region. — I think it would be nice to reinforce that in the same paragraph that says to create a certificate for speedy/skimmy readers like myself 🙈 😅 🙇‍♂️

Cheers!

**Comment by jayair** [comment]
Yup I'll make that more prominent in the docs.
