### ISSUE TITLE
Ion migration Issue

### ISSUE THREAD

**Issue by oldschoolbg** [sst/ion#840]
(this has been raised before but was closed with no comments - [Issue 48](https://github.com/sst/ion/issues/48))

I am in the process of migrating from V2 to V3 (ion) and have been following the migration guide. When I attempt to start the new V3 sst I get the following error:

`failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded`.

My sst.config.ts is super simple:

`export default $config({
  app(input) {
    return {
      name: "honeycomb",
      removal: "retain",  // input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: {
        aws: {
          region: 'eu-west-2'
        }
      }
    };
  },
  async run() {},
});
`

**Comment by tsato1** [comment]
Do you have credentials file in ~/.aws?

I encountered this too. My fix was 
1. Create an IAM user under my aws account
2. Run 'aws configure' to put the access key and secret in the credentials file

**Comment by oldschoolbg** [comment]
Hi thanks for the suggestion.

We use AWS SSO. Not sure how that interacts but that's a useful additional snippet about our setup I forgot to provide.

**Comment by thdxr** [comment]
you need to specify the profile in AWS_PROFILE=xxx env variable or pass itin the provider config

**Comment by oldschoolbg** [comment]
thank you - that worked. Much appreciate the help.
