### ISSUE TITLE
Provisioned concurrency for lambda

### ISSUE THREAD

**Issue by apetta** [sst/ion#855]
Is there a way to set provisioned concurrency for a lambda? I can see the option in pulumi docs [here](https://www.pulumi.com/blog/aws-lambda-provisioned-concurrency-no-cold-starts/)

**Comment by jayair** [comment]
For now, I think you'll need to use the transform?

**Comment by fwang** [comment]
@apetta provisioned concurrency requires enabling lambda versioning. Do you have versions enabled?

**Comment by apetta** [comment]
> @apetta provisioned concurrency requires enabling lambda versioning. Do you have versions enabled?

Ah, I don't think so, let me circle back on this

**Comment by fwang** [comment]
Supported in the latest version.
