### ISSUE TITLE
feature: implement sst import

### ISSUE THREAD

**Issue by thdxr** [sst/ion#86]
we need to expose the import command so people can add existing resources to their state file

<sub>[ION-240](https://linear.app/sst-dev/issue/ION-240/feature-implement-sst-import)</sub>

**Comment by Rafaa17** [comment]
Hey, what's the status of this? Are there any updates? Such an important feature.

**Comment by jayair** [comment]
Not yet, but it'll be done before we ask people to start migrating from SST2.

**Comment by Rafaa17** [comment]
In the meantime that this is being implemented can we use the `import` argument code-wise?

```
/**
     * When provided with a resource ID, import indicates that this resource's provider should import its state from
     * the cloud resource with the given ID. The inputs to the resource's constructor must align with the resource's
     * current state. Once a resource has been imported, the import property must be removed from the resource's
     * options.
     */
    import?: ID;```

**Comment by jayair** [comment]
Yeah actually you can. We just need to document it better on our side.

**Comment by jayair** [comment]
Sorta I'm going to document both of these in the next week.
