### ISSUE TITLE
Could not open a new TTY when running sst install

### ISSUE THREAD

**Issue by iamandrewluca** [sst/ion#869]
Running `npx sst install` in GitLab CI using `node:20-alpine3.20` image.

But I'm getting an error about TTY. Can anyone point me out in the right direction? Is this a sst issue, or no.

```
time=2024-08-16T13:12:12.566Z level=ERROR msg="exited with error" err="could not open a new TTY: open /dev/tty: no such device or address"
```

Running it locally inside a docker image using `node:20-alpine3.20` fails at a different step.
Running it locally inside a docker image using `node:20` finishes with success 🤔 

<details><summary>Dockerfile</summary>
<p>

```
FROM node:20

WORKDIR /app
COPY . .

RUN npm install
RUN npx sst install --verbose
```

</p>
</details> 

ChatGPT recommended this:

**1. Avoid TTY Requirement:** Some commands or scripts try to access TTY to ask for user input or display certain messages in a specific format. Ensure that none of your commands require interaction. If possible, look for flags that disable interactive prompts or TTY requirements. For example, if the SST command can run in non-interactive mode, try enabling that.
**2. Modify the Command:** Sometimes, adding --no-tty or similar flags to your command can prevent it from trying to use a TTY. However, SST may not support this directly, so you might need to check SST’s documentation or issues.

<details><summary>npx sst install --verbose</summary>
<p>

```
time=2024-08-16T13:12:06.390Z level=INFO msg="checking for pulumi" path=/root/.config/sst/bin/pulumi
time=2024-08-16T13:12:06.390Z level=INFO msg="pulumi install"
time=2024-08-16T13:12:06.391Z level=INFO msg="pulumi downloading" url=https://github.com/pulumi/pulumi/releases/download/v3.115.2/pulumi-v3.115.2-linux-x64.tar.gz
time=2024-08-16T13:12:11.037Z level=INFO msg="checking for bun" path=/root/.config/sst/bin/bun
time=2024-08-16T13:12:11.038Z level=INFO msg="bun install"
time=2024-08-16T13:12:11.038Z level=INFO msg="bun downloading" url=https://github.com/oven-sh/bun/releases//download/bun-v1.1.0/bun-linux-x64-baseline.zip
time=2024-08-16T13:12:12.566Z level=ERROR msg="exited with error" err="could not open a new TTY: open /dev/tty: no such device or address"
✕  Unexpected error occurred. Please check the logs or run with --verbose for more details.
```

</p>
</details>

**Comment by thdxr** [comment]
hm this is odd we should be detecting tty to see what mode to run in - not erroring if it's not there<br><br>i'll check

**Comment by thdxr** [comment]
what version of sst is this?

**Comment by iamandrewluca** [comment]
ion, don't remember exactly which one. Now, I'm trying to reproduce in a repo.

stuck at install

https://gitlab.com/iamandrewluca/sst-test/-/pipelines

**Comment by iamandrewluca** [comment]
Now I'm getting issues at sst install (either via npm or global)

Logs are empty https://gitlab.com/iamandrewluca/sst-test/-/jobs/7615923932#L25 🤔

**Comment by iamandrewluca** [comment]
@thdxr I'm checking now the git commits history, and in package.json I had `sst@ion`, but in lock file is `sst@0.1.98`

And now, locally, Installing `npm install sst@ion`, will install `sst@0.1.111`
Installing `npm install sst@latest`, will install `sst@3.0.43`

I will give one more try tomorrow, and will make sure that is v3

**Comment by thdxr** [comment]
we fixed the tags in npm, latest now properly points to latest<br><br>also we added `--print-logs` if you want them to print out to stdout so you can see what's going on in CI without dumping logs

**Comment by iamandrewluca** [comment]
Added `--print-logs`. Would it be better to hide this message when `--print-logs` is added? 🤔 

> ✕  Unexpected error occurred. Please check the logs in .sst/log/sst.log

**Comment by likeablob** [comment]
Hi, I had the same issue and was able to workaround this by explicitly specifying the stage with `--stage`,  like `sst install --stage ci`.

It seems like the root cause is that `sst install` allocates tty to start the input prompt when `.sst/stage` doesn't exist.

**Comment by iamandrewluca** [comment]
Wow, it worked

https://gitlab.com/iamandrewluca/sst-test/-/jobs/7731349416

**Comment by thdxr** [comment]
ah i see thanks for tracking this down, i'll fix

**Comment by thdxr** [comment]
we return a better error in v3.0.103
