### ISSUE TITLE
either 'content' (presen t: true) or 'data' (present: false) must be provided - cloudflare

### ISSUE THREAD

**Issue by 0xthierry** [sst/ion#872]
Hello everyone,

I'm setting up the ApiGateway custom domain with Cloudflare DNS, but I'm receiving the following error:

```bash
 sdk-v2/provider2.go:385: sdk.helper_schema: either 'content' (present: true) or 'data' (present: false) must be provided: provider=cloudflare @5.36.0
```

Investigating it looks like the Cloudflare API doesn't have the parameter value anymore, you can only send content or data.

What do you think about bumping the Pulumi Cloudflare package?

```ts
const api = new sst.aws.ApiGatewayV2("myapi", {
      domain: {
        name:
          $app.stage === "production"
            ? "mydomain.com"
            : `${$app.stage}-mydomain.com`,
        dns: sst.cloudflare.dns({
          zone: "myzone",
        }),
      },
    });
```

**Comment by 0xthierry** [comment]
It's weird the message showing this cloudflare@5.36.0 but is installed "@pulumi/cloudflare": "5.24.1" in the current version of sst/ion

**Comment by 0xthierry** [comment]
I found it, it was because of the provider version.

```ts
app(input) {
    return {
      name: "parse",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: {
        cloudflare: {
          version: "5.24.1",
        },
      },
    };
  },
```

**Comment by zdenham** [comment]
This is related to https://github.com/cloudflare/terraform-provider-cloudflare/issues/3590
