### ISSUE TITLE
When deploying Remix it drops layers I defined for Lambda

### ISSUE THREAD

**Issue by fuksito** [sst/ion#887]
I am using `sst.aws.Remix` to deploy my remix app.
I need some layers to serve libraries not available in runtime.
I added layers via AWS Console to my function.
But after deploy, sst does not preserve those layers.
Also I don't see how can I configure specific layers for `sst.aws.Remix`.

Is there a standard way to deal with it?

**Comment by fuksito** [comment]
That would be great if `npx sst deploy --stage production` would create new version of the function, instead of creating new one.

**Comment by jayair** [comment]
We'll look at the Remix issue here.

For the new version thing, open a new issue and clarify what you mean by create new version?

**Comment by fwang** [comment]
In v3.0.59, u can add layers via `server.layers`

```ts
{
  server: {
     layers: ["arn:aws:lambda:us-east-1:123456789012:layer:my-layer:1"]
  }
}
```

**Comment by fuksito** [comment]
Great, this is what I needed. Thank you!
