### ISSUE TITLE
Autodeployment with StaticSite fails at build-time

### ISSUE THREAD

**Issue by jontmy** [sst/ion#891]
When auto-deploying a StaticSite, `sst:Run` on the build command fails. This does not happen when deploying to the same stage on a local machine.

<img width="602" alt="Screenshot_2024-08-16_at_08 31 14" src="https://github.com/user-attachments/assets/67727e25-6dc0-4c43-ad3a-ac3c25d736c5">

After reproducing the autodeployment workflow with GitHub actions, printing out the `sst.log` reveals these errors:

![image](https://github.com/user-attachments/assets/122881ae-3427-45eb-80d1-e1a695ee22af)

**Comment by thdxr** [comment]
damn thank you for tracking this down - i'm looking into it right now

**Comment by thdxr** [comment]
is it possible to run this again and also cat out `.sst/log/pulumi.log` ?

**Comment by thdxr** [comment]
are these logs truncated somehow? we added `--print-logs` to the latest sst which you can try running with

**Comment by thdxr** [comment]
we also made it so you can add `SST_PRINT_LOGS=1` to your autodeploy config in the console and it'll output there so you don't have to hack through github actions

**Comment by thdxr** [comment]
sorry for so many messages but can i see the build command for your static site?

**Comment by jontmy** [comment]
> is it possible to run this again and also cat out .sst/log/pulumi.log ?
> we also made it so you can add SST_PRINT_LOGS=1 to your autodeploy config in the console and it'll output there so you don't have to hack through github actions

I've set up autodeployment using the SST console, if you're able to view it, it's here:

https://console.sst.dev/lfg-travel/lfg/dev/autodeploy/hjbznzyshg3q5pdxaxjn2j8n

Otherwise, I've also uploaded it as a gist:

https://gist.github.com/jontmy/1187a9321da83285ac1b5fc38da726c0

The output from `pulumi.log` gets shoved into one long line so I've also formatted the output of `pulumi.log` starting from line 2719 of the gist.

> sorry for so many messages but can i see the build command for your static site?

We're running a monorepo with two StaticSite constructs for `Cms` and `Web`, both of which use `sst shell vite build`.

Some extra information if it helps:

#### Directory structure
```
+ apps
  + cms
    + dist
    + src
    - package.json (build command: sst shell vite build)
  + web
    + dist
    + src
    - package.json (build command: sst shell vite build)
+ infra
  - apps.ts (exports sst.aws.StaticSite)
- sst.config.ts (dynamically imports infra/apps.ts)
```

#### apps.ts
```ts
import { Api } from "./api";

export const Cms = new sst.aws.StaticSite("Cms", {
    path: "apps/cms",
    build: {
        command: "pnpm build",
        output: "dist",
    },
});

export const Web = new sst.aws.StaticSite("Web", {
    path: "apps/web",
    build: {
        command: "pnpm build",
        output: "dist",
    },
});
```

**Comment by jontmy** [comment]
@thdxr Looks like the `sst shell` indeed caused the error, managed to deploy successfully using the SST console. Apologies for the trouble!
