### ISSUE TITLE
import.meta.env.PROD no longer correctly set with sst deploy

### ISSUE THREAD

**Issue by arjunyel** [sst/ion#894]
Removing this line in my project fixed it https://github.com/sst/ion/commit/168b1c1f804a7aaaeef941551637cd37fbfefc41

**Comment by jayair** [comment]
Sorry what's going on?

**Comment by arjunyel** [comment]
@jayair sorry for the confusion.

In my deployed Remix app, import.meta.env.PROD was suddenly coming up false, and how other libraries detect if its in prod were also broken, for example React Query devtools for example started showing in my prod deployment. So the frontend was basically not configured in production mode. When I manually rolled back the commit mentioned above it started working again, meaning that commit started the issue.
