### ISSUE TITLE
ApiGatewayV2 log group fails when deploying two stages in the same account

### ISSUE THREAD

**Issue by bjorntechTobbe** [sst/ion#907]
When using the same aws account for a local stage and dev I get the error:

`✕  Failed    
   Api sst:aws:ApiGatewayV2 → ApiAccessLog aws:cloudwatch:LogGroup
   Logs: CreateLogGroup, https response error StatusCode: 0, RequestID: , request send failed, Post "https://logs.eu-north-1.amazonaws.com/": dial tcp: lookup logs.eu-north-1.amazonaws.com: no such host
   ApiRouteZoxosa sst:aws:ApiGatewayV2LambdaRoute → ApiRouteZoxosaHandlerLogGroup aws:cloudwatch:LogGroup
   Logs: CreateLogGroup, https response error StatusCode: 400, RequestID: f50f61ce-a631-4cf9-90f3-52f7874fa077, ResourceAlreadyExistsException: The specified log group already exists`

**Comment by jayair** [comment]
Hmm this shouldn't happen. What are the two stage names? And can you share the part of the sst config that defines this API?

**Comment by bjorntechTobbe** [comment]
The name of the local stage is 'tobbe' and the dev stage name is 'dev'

`    const api = new sst.aws.ApiGatewayV2('Api', {
      transform: {
        route: {
          handler: {
            link: [
              xxxxx
            ],
          },
        },
      },
    })`

**Comment by jayair** [comment]
That seems okay to me. Can you give me the steps to reproduce this? Ideally on a clean setup.

**Comment by bjorntechTobbe** [comment]
Sure, 

`/// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app(input) {
    return {
      name: 'api-issue',
      removal: input?.stage === 'prod' ? 'retain' : 'remove',
      home: 'aws',
      region: 'eu-north-1',
      providers: {
        aws: true,
        cloudflare: true
      },
    }
  },
  async run() {

    const api = new sst.aws.ApiGatewayV2('Api', {
    })

    api.route(
      'GET /trigger-token-queue', {
      name: 'ApiRouteTriggerTokenQueue',
      handler: 'packages/functions/src/queue_refresh.main',
    });
    api.route('GET /oauth-redirect', {
      name: 'ApiRouteOauthRedirect',
      handler: 'packages/functions/src/oauth_redirect.main',
    });
    api.route('POST /fortnox-websocket-message', {
      name: 'ApiRouteFortnoxWebsocketMessage',
      handler: 'packages/functions/src/fortnox/websocket/message.main',
    });

  },
})`

`bun run sst dev`

then

`bun run sst deploy --stage dev`

Just discovered that the issue occurs only if api.route is used.

**Comment by jayair** [comment]
It's likely the `name: 'ApiRouteFortnoxWebsocketMessage'`.

If you are naming it on your own, you need to ensure that it doesn't thrash across stages.

https://sst.dev/docs/component/aws/function/#name

**Comment by bjorntechTobbe** [comment]
Aaaa, understand. My bad. Thanks a lot for a great product!
