### ISSUE TITLE
Astro preset

### ISSUE THREAD

**Issue by jayair** [sst/ion#912]
@fwang is this right

```
import aws from "astro-sst";

export default defineConfig({
  output: "server",
  adapter: aws(),
});
```

based on the README https://github.com/sst/sst/tree/master/packages/astro-sst

Or what we do in our docs?

```
import sst from "astro-sst";

export default defineConfig({
  adapter: sst(),
});
```

I need to update the preset https://github.com/sst/ion/commit/4f55966b36f4854f5a256d8c46d2e3e051dab919 and the quick start https://github.com/sst/ion/pull/852

**Comment by iamandrewluca** [comment]
> Or what we do in our docs?

I looked through the source code, the outcome of both examples is the same.

Astro default output is `static` [link](https://docs.astro.build/en/basics/rendering-modes/#server-output-modes)

`astro-sst` will change `output` to `server` if `deploymentStrategy` is different than `static` [link](https://github.com/sst/sst/blob/5d0fd843c240253148c25e8513d84afd01da0879/packages/astro-sst/src/adapter.ts#L76-L92)

**Comment by jayair** [comment]
Thanks @iamandrewluca
