### ISSUE TITLE
Errors running sst ion commands when running another app on v2

### ISSUE THREAD

**Issue by mdnorman** [sst/ion#919]
Commands like `sst refresh` are failing with when I'm running an app on sst v2 at the same time:

Error from pulumi:
```
   Failed to call RPC: <!DOCTYPE html>
<html lang="en">                      
<head>                                
<meta charset="utf-8">                
<title>Error</title>                  
</head>                               
<body>                                
<pre>Cannot POST /rpc</pre>           
</body>                               
</html>                               
```

I'm running version `3.0.68`

**Comment by coronapl** [comment]
Apparently, it is also not possible to run a deployment.

**Comment by jayair** [comment]
Explain this again? So you have a v2 app? and you are trying to deploy a v3 app with the same name?

**Comment by mdnorman** [comment]
Not the same name. We have a big app that's on sst2. I'm creating a new service with a completely different name in sst3. I can't run the new service in sst3 or do a deployment in sst3 while the sst2 app is running. This means I can't test my main app running on sst2 against the new service running on sst3.

**Comment by jayair** [comment]
So you have `sst dev` running for v2? And you can't run commands on v3?

**Comment by mdnorman** [comment]
Yes, that's correct.

**Comment by thdxr** [comment]
upgrade to v3.0.105 which has some extra logging

1. start the v2 project
2. try to run the v3 command that fails, eg `sst refresh`
3. check `.sst/log/sst.log` to see a line "server port assigned" and tell me which one it is

**Comment by thdxr** [comment]
also we did fix an issue related to rpc using the wrong port but you need to update to latest, run an sst refresh while v2 is NOT running and that should fix it going forward

**Comment by thdxr** [comment]
gotcha - so the bug here is sst v3 thinks it can use port 13557 even though it's currently being taken so it doesn't try an alternative port - i'll figure this out ty!

**Comment by thdxr** [comment]
potentially fixed in v3.0.109

**Comment by mdnorman** [comment]
Unfortunately still doesn't work in `v3.0.113`:

```
time=2024-09-05T15:58:16.324-05:00 level=INFO msg="server port assigned" port=13557
time=2024-09-05T15:58:16.324-05:00 level=INFO msg="getting endpoint"
time=2024-09-05T15:58:16.325-05:00 level=INFO msg=server addr=0.0.0.0:13557
time=2024-09-05T15:58:16.326-05:00 level=INFO msg="deployer waiting for trigger"
```

**Comment by thdxr** [comment]
hm ok can you run just sst v2 and check if `localhost:13557` is responding? i don't understand why v3 thinks it can listen on the same port when it can't

**Comment by mdnorman** [comment]
this is what I get when I run `curl -i http://localhost:13557`:
```
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 145
Date: Fri, 06 Sep 2024 05:19:45 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /local/</pre>
</body>
</html>
```

And when I turn off sst2, it doesn't respond, so this is definitely sst2's port.

I'm on mac btw. Not sure if it matters.

**Comment by thdxr** [comment]
can you try latest?

**Comment by mdnorman** [comment]
woot! it works!
