### ISSUE TITLE
Docs: Granular permissions when linking to resources

### ISSUE THREAD

**Issue by ryands17** [sst/ion#936]
Given a lambda and SQS queue:

```ts
    const app = new sst.aws.Function('PublisherFn', {
      handler: 'publisher.handler',
      link: [queue],
      url: true,
    });

```

Is it possible to provide granular permissions via `link` instead of `sqs:*`?

**Comment by jayair** [comment]
Yeah I'll try and put an example together but https://sst.dev/docs/component/linkable#static-wrap the queue and specify your own permissions.

**Comment by jayair** [comment]
Here it is https://sst.dev/docs/component/linkable#modify-built-in-links
