### ISSUE TITLE
[ION-242] Feat: Expose Architecture for Auth and Router on Aws

### ISSUE THREAD

**Issue by claughinghouse** [sst/ion#94]
The `sst.aws.Router` and `sst.aws.Auth` do not expose the ability to specify the architecture as `x86_64` or the `arm64` like the option that is avaliable under `sst.aws.Function`. It would be nice if this were possible or if it could be set at the provider level versus on the individual construct. 

[Link for Function reference](https://ion.sst.dev/docs/component/aws/function/#architecture)

<sub>[ION-242](https://linear.app/sst-dev/issue/ION-242/feat-expose-architecture-for-auth-and-router-on-aws)</sub>

**Comment by fwang** [comment]
For Auth, `authenticator` takes full function args:
```ts
{
  authenticator: {
    architecture: "arm64"
  }
}
```

Can u clarify for you are looking to set for `sst.aws.Router`? Lambda is not involved.

**Comment by claughinghouse** [comment]
Ah, I was one key above for the authenticator architecture. 

For the `sst.aws.Router`, I missed that CloudFront was being used to add routes. I assumed that `Router` will have a javascript implementation to allow it to function on AWS and Cloudflare versus just AWS. 

In the future, will it be possible to set the `architecture:` at a provider level with the option to override for specific functions?

**Comment by fwang** [comment]
> In the future, will it be possible to set the architecture: at a provider level with the option to override for specific functions?
like a way to set ie. `architecture`, `timeout` for all functions in the app?

**Comment by claughinghouse** [comment]
Yes, exactly this.

**Comment by fwang** [comment]
Gotcha. It is on the roadmap. Let's track it here https://github.com/sst/ion/issues/103

Close this
