### ISSUE TITLE
new sst.cloudflare.Worker() does not work if CLOUDFLARE_API_TOKEN is not set

### ISSUE THREAD

**Issue by bjorntechTobbe** [sst/ion#944]
new sst.cloudflare.Worker() only works if the environment variable CLOUDFLARE_API_TOKEN is set. 

It should also work if setting apiToken in "providers". 

Other services, such as D1 deploy without problems with providers only

`      
providers: {
        cloudflare: {
          apiToken: 'xxxxxx'
        },
      },
`

**Comment by bjorntechTobbe** [comment]
It fails with:

Error: A request to the Cloudflare API (/accounts/xxxxxxxxx/workers/subdomain) failed.

{ code: 10000, message: 'Authentication error' }

**Comment by bjorntechTobbe** [comment]
Possibly found the reason for this. It seems like cfFetch in "platforms>src>components>platforms>helpers>fetch.ts" is using process.env.CLOUDFLARE_API_TOKEN as authorization.

`export async function cfFetch<ResultType>(
  resource: string,
  init: RequestInit = {},
) {
  const ret = await fetch(`${CLOUDFLARE_API_BASE_URL}${resource}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${CLOUDFLARE_API_TOKEN}`,
      ...init.headers,
    },
  });
  const json = (await ret.json()) as FetchResult<ResultType>;
  // ie.
  // {
  //   "result": {
  //     "subdomain": "wangfanjie"
  //   },
  //   "success": true,
  //   "errors": [],
  //   "messages": []
  // }
  if (json.success) {
    return json;
  }

  const error = new Error(
    `A request to the Cloudflare API (${resource}) failed.`,
  );
  // @ts-expect-error attach the errors to the error object
  error.errors = json.errors;
  // @ts-expect-error attach the messages to the error object
  error.messages = json.messages;
  throw error;
}`

cfFetch is used only by "worker-url", "zone-lookup" and "kv-data" and explains why setting the token in providers is working for other services such as D1.

**Comment by thdxr** [comment]
should be fixed in v3.0.104
