### ISSUE TITLE
Feat: option to prevent outputs from beeing logged

### ISSUE THREAD

**Issue by iOSonntag** [sst/ion#954]
It would be great to have an option in the deploy cli to prevent the outputs from actually being logged.

We create some google service account keys with sst and put them in the outputs so that we can store the outputs.json in a github action workflow artifact so that it can be downloaded later by another github action in the deploy process. (needed by fastlane to publish the app to android play store).

Now we don't care that the credentials are shortlived in the outputs.json as it gets remoed after the workflow run, what we do care about is that the entire output file gets logged after the deploy command finished. (And therefore be available in the github actions insight section)

If there is another approach of handling it please let us know

**Comment by iOSonntag** [comment]
Another approach I could imagine would be to add an option for the `new sst.Secret()` component to set the value during deployment e.g.:

```ts
new sst.Secret('SecretGoogleServiceAccountKey', {
  value: googleServiceAccountKey.privateKey
});
```

And then add an option to the `sst secret` command to retrieve a single secret (not all of them via `list`) like:

```shell
goole_service_account_key="$(sst secret get SecretGoogleServiceAccountKey)"
```

This way the output will not be abused for secrets, I dont know (all just suggestions maybe I am wrong)

**Comment by jayair** [comment]
Let me understand this, you want the outputs to be printed to a file but not logged on to the screen?

**Comment by iOSonntag** [comment]
Exactly

**Comment by jayair** [comment]
I see, one workaround  could be to just write to a file as a part of your sst config.

**Comment by iOSonntag** [comment]
How we actually do that? By the time we create the privatekey it is a pulumi output (`$util.Output<string>`) which will be resolved based on dependencies in the deployment process. 

Is there some "post deployment" hook we can insert somewhere?

**Comment by thdxr** [comment]
you can do something like this

```
$resolve([var1, var2, var3]).apply(([var1, var2, var3]) => {
  // write resolved values
})
```

**Comment by thdxr** [comment]
since this workaround likely works going to close this issue
