### ISSUE TITLE
Cannot use 'in' operator to search for 'getSSTLink' in undefined when removing links

### ISSUE THREAD

**Issue by paolostyle** [sst/ion#976]
NGL, what I'm doing is probably completely against what you'd like the users to do, but I guess you might want to be interested in this anyway.

So generally in my company we're storing all kinds of secrets in the AWS Secrets Manager; after we started using SST, the way I've been handling it is through a custom script that essentially fetches the secret through AWS SDK, writes it to a .env file and runs `sst secret load .env`, but it seems to be a constant pain point for other team members when setting up a project, so I was looking for a solution where SST would handle it end-to-end.

I came up with something like this (this is in the sst.config.ts):

```
    const { secretString } = await aws.secretsmanager.getSecretVersion({
      secretId: `secret`,
    });

    const secrets = Object.fromEntries(
      Object.entries(JSON.parse(secretString)).map(([key, value]) => [
        key,
        new sst.Secret(key, String(value)),
      ]),
    );

    // ...then just link it through `Object.values(secrets)`
```

Overall it's not ideal; I'm not 100% sold on not having the secrets explicitly listed in the config (but it does generate correct sst-env.d.ts which is great) as sometimes I do need to refer to them by name (i.e. in one case it's just linked as `Object.values(secrets)` but somewhere else it's through `link: [secrets.SomeSecret]` and obviously it's not strictly typed). I suppose it also somewhat wastefully saves these values in an S3 bucket under the hood when I'd rather just use them directly from the Secrets Manager. But overall it's working quite well.

Unfortunately, it stops working when you remove an entry from the secret. On the next deploy after the change in the secret, SST throws an error:

```
   TypeError: Cannot use 'in' operator to search for 'getSSTLink' in undefined
       at isLinkable (file:///home/paolo/code/project/.sst/platform/src/components/link.ts:97:12)
       at file:///home/paolo/code/project/.sst/platform/src/components/link.ts:102:22
       at Array.filter (<anonymous>)
       at Object.build2 [as build] (file:///home/paolo/code/project/.sst/platform/src/components/link.ts:102:8)
       at file:///home/paolo/code/project/.sst/platform/src/components/aws/function.ts:1195:60
       at /home/paolo/code/project/.sst/platform/node_modules/@pulumi/output.ts:402:31
       at Generator.next (<anonymous>)
       at /home/paolo/code/project/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
       at new Promise (<anonymous>)
       at __awaiter (/home/paolo/code/project/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12) {
     promise: Promise { <rejected> [Circular *1] }
   }
   TypeError: Cannot use 'in' operator to search for 'getSSTLink' in undefined
       at isLinkable (file:///home/paolo/code/project/.sst/platform/src/components/link.ts:97:12)
       at Array.filter (<anonymous>)
       at file:///home/paolo/code/project/.sst/platform/src/components/link.ts:121:20
       at /home/paolo/code/project/.sst/platform/node_modules/@pulumi/output.ts:402:31
       at Generator.next (<anonymous>)
       at /home/paolo/code/project/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
       at new Promise (<anonymous>)
```

Like I mention at the beginning, I _am_ aware that this is probably an unsupported behavior but a) perhaps this could work and it's a simple fix b) maybe you can suggest a better solution for handling the secrets. I guess I could probably create a Linkable resource but that would be a larger change as I'd have to adjust all the `Resource` usages in the codebase.

**Comment by thdxr** [comment]
have you considered creating a single `Linkable` that contains all of these values? [https://sst.dev/docs/component/linkable](https://sst.dev/docs/component/linkable)

**Comment by paolostyle** [comment]
I did, yes, that's what I meant by

>I could probably create a Linkable resource but that would be a larger change as I'd have to adjust all the Resource usages in the codebase

It is definitely cleaner, but there are some downsides, I'm pretty sure it won't autogenerate the types, i.e. if I did something like this:
```
const { secretString } = await aws.secretsmanager.getSecretVersion({
  secretId: `secret`,
});

new sst.Linkable("AllSecretValues", {
  properties: JSON.parse(secretString)
});
```

I suppose that `AllSecretValues` would just be of type `any`, unless I do `JSON.parse(secretString) as SomeInterface`, right? I did not try it, though, I will check tomorrow.

If I did explicitly specify `properties`, there is one more downside - every property would be realistically of type `string | undefined`. With "regular" usage of `Secret`s SST will throw if a secret is undefined and it doesn't have a placeholder, and in the approach I tried if a secret I would expect to exist is not there, it won't appear in `sst-env.d.ts` so I'd get a TypeScript error if I attempted to use it in the app code. I suppose I could use some validator like zod to check the `JSON.parse`d output but it feels a bit strange when there is a built in way.

Ultimately I will probably have to either live with these downsides or just leave it as it is, but I wonder how others are populating the secrets, on CI level I suppose it can be automated as most CI providers offer some kind of storage for secrets, but what about distributing it between developers? Every company I worked at had a different way of doing it and it almost always felt wrong, the Secrets Manager feels the most "correct" I guess but I'm pretty sure it's not a standard at all.

**Comment by thdxr** [comment]
the problem is the only way for us to fix this is by ignoring undefined values in the link array which might be unintentional<br><br>can you filter out undefined after doing Object.values ?

**Comment by paolostyle** [comment]
...oh gosh now I feel like an idiot. I had `secrets.SomeSecretThatIJustRemoved` explicitly linked in a different `Function` and that's what was causing the error, not `Object.values` as that one didn't have any undefined values. Welp. Sorry about that.

To your point, though, is there actually any case where `undefined` in the link array would be intentional or wanted? As you can see here it just causes the error and to be fair I didn't notice what caused it (I do have a pretty large sst.config.ts file but still). Perhaps you could throw an error when `link` array contains falsy values, or even non-Linkable elements? I can see the same error when I pass something stupid like `link: ['123']`. So for example something like

```
new sst.aws.Function('MyFunction', {
  link: [undefined, '123']
});
```

would throw immediately with `MyFunction contains non-Linkable elements`.

This is definitely more of a nice-to-have but at least it would (probably) prevent people from creating stupid GitHub issues 🙃. I could prepare a PR if you'd be interested as it sounds pretty easy.

**Comment by thdxr** [comment]
yeah our code for this is a bit of a mess though - you suggestion is good i implemented a better error message
