### ISSUE TITLE
bug: realtime - mqtt.MqttClient is not a constructor

### ISSUE THREAD

**Issue by magicspon** [sst/ion#980]
Example: https://sst.dev/docs/start/aws/realtime/#4-create-a-connection

this is throwing an error:

`TypeError: mqtt.MqttClient is not a constructor`

I've tried various versions of `aws-iot-device-sdk-js-v2` and `sst`, no disco.

Any ideas?

**Comment by danielfyhr** [comment]
Might be related to this https://github.com/aws/aws-iot-device-sdk-js-v2/issues/524

**Comment by magicspon** [comment]
Smashing... i'll update this ticket when there is news

**Comment by thdxr** [comment]
i also tried moving to mqtt5 and it still seemed to have the same issue but still exploring

**Comment by thdxr** [comment]
seems like they reverted the change so going to close this for now
