### ISSUE TITLE
Unable to connect to Postgres using provided credentials

### ISSUE THREAD

**Issue by otothea** [sst/ion#984]
I am trying to migrate an existing project that uses Sequelize over to SST. I'm getting timeouts while connecting to the database created by SST.

I'm following these guides as starting point:
[https://sst.dev/docs/component/aws/postgres](https://sst.dev/docs/component/aws/postgres)
[https://sst.dev/docs/start/aws/drizzle](https://sst.dev/docs/start/aws/drizzle)

---

> The VPC configured for the function does not have NAT enabled. Enable NAT by configuring "nat" on the "sst.aws.Vpc" component.

First of all, I am seeing this error 👆 if I create a Vpc component and include it on a Cron component. I'm not sure if I need to set the `vpc` property on each component or if just using `link` is enough. The guides show it being done both ways. I do NOT see this error if I only include `vpc` on the Nextjs component.

For now, I am using `link` on both and I am including `vpc` on Nextjs but not on Cron. Regardless, both show timeout error when connecting to database.

---

> ConnectionError \[SequelizeConnectionError\]: connect ETIMEDOUT 10.0.13.135:5432

I am seeing this error 👆 when attempting to connect to the database during runtime. Here is the SST config and Sequelize connection code. What am I missing?

sst.config.ts

```
export default $config({
  app(input) {
    return {
      name: "xxxxxxx",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    const vpc = new sst.aws.Vpc('MyVpc');

    const database = new sst.aws.Postgres('MyDatabase', { vpc });

    const bucket = new sst.aws.Bucket("MyBucket", {
      public: true,
    });

    const email = new sst.aws.Email('MyEmail', {
      sender: 'xxxx@xxxxxxxx.com',
    });

    new sst.aws.Cron("CronMonitorCheck", {
      job: {
        handler: "src/server/index.check",
        link: [bucket, database, email],
      },
      schedule: "rate(5 minutes)",
    });

    const nextjs = new sst.aws.Nextjs("MyWeb", {
      environment: {
        NEXT_PUBLIC_BUCKET_DOMAIN: bucket.domain,
      },
      link: [bucket, database],
      vpc,
    });

    return {
      bucket_name: bucket.name,
      web_url: nextjs.url,
      database_username: database.username,
      database_password: database.password,
      database_host: database.host,
      database_port: database.port,
      database_database: database.database,
      database_clusterarn: database.clusterArn,
      database_clusterid: database.clusterID,
      database_secretarn: database.secretArn,
      database_urn: database.urn,
      email: email.sender,
    };
  },
});
```

src/server/index.ts

```
const sequelize = new Sequelize({
    host: Resource.MyDatabase.host,
    port: Resource.MyDatabase.port,
    database: Resource.MyDatabase.database,
    username: Resource.MyDatabase.username,
    password: Resource.MyDatabase.password,
    dialect: 'postgres',
    dialectOptions: {
      ssl: true,
    },
});
```

g

**Comment by thdxr** [comment]
you need to set the `nat` property on the `Vpc` component if you are going to use it with lambda functions - it's a requirement<br><br>are you running into this error in dev mode? or when deployed?

**Comment by otothea** [comment]
This is all happening in dev mode. I did also try setting the `nat` property. There is a mismatch between the allowed value in typescript and what it says in the docs. Should it be "gateway" or "managed"?

<img width="961" alt="image" src="https://github.com/user-attachments/assets/4e48e06a-791c-4c43-af06-868db0d59de9">

---

I tried setting it to "managed" and adding the `vpc` prop:

```
const vpc = new sst.aws.Vpc('MyVpc', { nat: 'managed' });

const database = new sst.aws.Postgres('MyDatabase', { vpc });

new sst.aws.Cron("CronMonitorCheck", {
  job: {
    handler: "src/server/index.check",
    link: [bucket, database, email],
    vpc
  },
  schedule: "rate(5 minutes)",
});

...
```

Now I'm running into this issue. I was not having this issue when I tried previously:

```
|  Error       CronMonitorCheck sst:aws:Cron → CronMonitorCheckHandlerFunction aws:lambda:Function
|  updating urn:pulumi:oscararmstrong::policy-tracker::sst:aws:Cron$sst:aws:Function$aws:lambda/function:Function::CronMonitorCheckHandlerFunction: 1 e
rror occurred:
|
|  InsufficientRolePermissions: The function's execution role doesn't have permission to perform this operation.
```

**Comment by thdxr** [comment]
in dev mode your code is running locally so it won't be able to connect to rds that way.  i suggest looking closely at the examples/aws-rds example we have - we specifically avoid needing to put our functions in a vpc by using the data api

**Comment by thdxr** [comment]
if you need to use sequelize which maybe does not support data api you will need to do much more advanced setup in dev mode where you create a tunnel to your database - or run the database locally and conditionally connect to it<br><br>also conditionally set your lambda in a vpc only in non-dev mode

**Comment by otothea** [comment]
Okay, that makes sense. I will take the second approach and use a local postgres during development for now. Thank you.
